//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TToolbarItem.h"

@interface TQuickLookToolbarItem : TToolbarItem
{
    struct vector<TNotificationCenterObserver, std::__1::allocator<TNotificationCenterObserver>> _observers;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)flagsDidChange:(id)arg1;
- (void)flagsMayHaveChanged;
- (void)setImageFromFlags:(unsigned long long)arg1;
- (id)initWithItemIdentifier:(id)arg1 entry:(const struct ToolbarItemInfo *)arg2 controller:(id)arg3 propertyList:(id)arg4 willBeInsertedIntoToolbar:(_Bool)arg5;

@end

