//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPConnection.h"

__attribute__((visibility("hidden")))
@interface CPRemoteViewConnection : CPConnection
{
}

- (void)requestRefresh;
- (void)updateDeviceWithData:(id)arg1 MIMEType:(id)arg2 textEncodingName:(id)arg3 baseURL:(id)arg4 description:(id)arg5 type:(int)arg6 displayURL:(id)arg7;
- (void)connectWithUUID:(id)arg1;
- (void)disconnect;
- (void)receivedMessage:(id)arg1;

@end

