//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCOCO18NotificationCenter17NotificationsList10Controller5Model5Group : _TtCs12_SwiftObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: title
    // Error parsing type: , name: groupingIdentifier
    // Error parsing type: , name: notifications
    // Error parsing type: , name: animatingExpandCollapse
    // Error parsing type: , name: state
}

@end

