//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/_NSDocumentSerializationObject.h>

__attribute__((visibility("hidden")))
@interface _NSDocumentActivity : _NSDocumentSerializationObject
{
    CDUnknownBlockType _cancellationHandler;
    BOOL _cancelled;
    BOOL _cachedCancellationHandlerResponse;
}

@property(getter=isCancelled) BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(copy) CDUnknownBlockType cancellationHandler; // @synthesize cancellationHandler=_cancellationHandler;
- (void)cancelAndFinishAsynchronously:(char *)arg1;
- (void)dealloc;

@end

