//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RWIProtocolJSONObject.h"

@class NSString;

@interface WDProtocolAutomationInputSource : RWIProtocolJSONObject
{
}

@property(nonatomic) long long sourceType;
@property(copy, nonatomic) NSString *sourceId;
- (id)initWithSourceId:(id)arg1 sourceType:(long long)arg2;
- (id)initWithProtocolObject:(id)arg1;
- (id)initWithPayload:(id)arg1;

@end

