//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <WebKit/NSWindowDelegate-Protocol.h>

@class NSArray, NSString, NSView;

__attribute__((visibility("hidden")))
@interface WKFullScreenWindowController : NSWindowController <NSWindowDelegate>
{
    NSView *_webView;
    struct WebPageProxy *_page;
    struct RetainPtr<WebCoreFullScreenPlaceholderView> _webViewPlaceholder;
    struct RetainPtr<NSView> _clipView;
    struct RetainPtr<NSView> _backgroundView;
    struct CGRect _initialFrame;
    struct CGRect _finalFrame;
    struct RetainPtr<NSTimer> _watchdogTimer;
    struct RetainPtr<NSArray> _savedConstraints;
    long long _fullScreenState;
    double _savedScale;
    struct RefPtr<WebKit::GenericCallback<>> _repaintCallback;
    float _savedTopContentInset;
}

@property(readonly) struct CGRect finalFrame; // @synthesize finalFrame=_finalFrame;
@property(readonly) struct CGRect initialFrame; // @synthesize initialFrame=_initialFrame;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_watchdogTimerFired:(id)arg1;
- (void)_startExitFullScreenAnimationWithDuration:(double)arg1;
- (void)_startEnterFullScreenAnimationWithDuration:(double)arg1;
- (void)_replaceView:(id)arg1 with:(id)arg2;
- (struct WebFullScreenManagerProxy *)_manager;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidFailToExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowDidFailToEnterFullScreen:(id)arg1;
- (void)window:(id)arg1 startCustomAnimationToExitFullScreenWithDuration:(double)arg2;
- (void)window:(id)arg1 startCustomAnimationToEnterFullScreenWithDuration:(double)arg2;
- (id)customWindowsToExitFullScreenForWindow:(id)arg1;
- (id)customWindowsToEnterFullScreenForWindow:(id)arg1;
- (void)close;
- (void)performClose:(id)arg1;
- (void)completeFinishExitFullScreenAnimationAfterRepaint;
- (void)finishedExitFullScreenAnimation:(_Bool)arg1;
- (void)beganExitFullScreenWithInitialFrame:(const struct IntRect *)arg1 finalFrame:(const struct IntRect *)arg2;
- (void)requestExitFullScreen;
- (void)exitFullScreen;
- (void)finishedEnterFullScreenAnimation:(_Bool)arg1;
- (void)beganEnterFullScreenWithInitialFrame:(const struct IntRect *)arg1 finalFrame:(const struct IntRect *)arg2;
- (void)enterFullScreen:(id)arg1;
- (void)cancelOperation:(id)arg1;
@property NSArray *savedConstraints;
- (id)webViewPlaceholder;
- (BOOL)isFullScreen;
- (void)dealloc;
- (id)initWithWindow:(id)arg1 webView:(id)arg2 page:(struct WebPageProxy *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

