//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iTermLocatedString.h"

@class NSAttributedString, NSMutableAttributedString;

@interface iTermLocatedAttributedString : iTermLocatedString
{
    NSMutableAttributedString *_attributedString;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (void)removeOcurrencesOfString:(id)arg1;
- (void)trimTrailingWhitespace;
- (void)dropFirst:(long long)arg1;
- (long long)length;
- (void)erase;
- (void)appendAttributedString:(id)arg1 at:(CDStruct_1ef3fb1f)arg2;
- (void)appendString:(id)arg1 withAttributes:(id)arg2 at:(CDStruct_1ef3fb1f)arg3;
- (id)string;
- (id)init;

@end

