//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MediaPlayer/NSCopying-Protocol.h>

@class MPMediaLibrary, MPModelPlaylist, MPSectionedCollection, NSNumber, NSString, UIImage;

@interface MPModelLibraryPlaylistEditChangeRequest : NSObject <NSCopying>
{
    BOOL _shouldCreatePlaylist;
    BOOL _didSetPlaylistUserImage;
    MPMediaLibrary *_mediaLibrary;
    MPSectionedCollection *_playlistEntries;
    NSString *_playlistDescription;
    NSString *_playlistName;
    UIImage *_playlistUserImage;
    NSNumber *_publicPlaylist;
    NSNumber *_visiblePlaylist;
    NSNumber *_curatorPlaylist;
    NSNumber *_isOwner;
    NSString *_authorStoreIdentifier;
    MPModelPlaylist *_parentPlaylist;
    MPModelPlaylist *_playlist;
}

+ (id)requiredPlaylistEntryProperties;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL didSetPlaylistUserImage; // @synthesize didSetPlaylistUserImage=_didSetPlaylistUserImage;
@property(retain, nonatomic) MPModelPlaylist *playlist; // @synthesize playlist=_playlist;
@property(nonatomic) BOOL shouldCreatePlaylist; // @synthesize shouldCreatePlaylist=_shouldCreatePlaylist;
@property(retain, nonatomic) MPModelPlaylist *parentPlaylist; // @synthesize parentPlaylist=_parentPlaylist;
@property(copy, nonatomic) NSString *authorStoreIdentifier; // @synthesize authorStoreIdentifier=_authorStoreIdentifier;
@property(copy, nonatomic) NSNumber *isOwner; // @synthesize isOwner=_isOwner;
@property(copy, nonatomic, getter=isCuratorPlaylist) NSNumber *curatorPlaylist; // @synthesize curatorPlaylist=_curatorPlaylist;
@property(copy, nonatomic, getter=isVisiblePlaylist) NSNumber *visiblePlaylist; // @synthesize visiblePlaylist=_visiblePlaylist;
@property(copy, nonatomic, getter=isPublicPlaylist) NSNumber *publicPlaylist; // @synthesize publicPlaylist=_publicPlaylist;
@property(retain, nonatomic) UIImage *playlistUserImage; // @synthesize playlistUserImage=_playlistUserImage;
@property(copy, nonatomic) NSString *playlistName; // @synthesize playlistName=_playlistName;
@property(copy, nonatomic) NSString *playlistDescription; // @synthesize playlistDescription=_playlistDescription;
@property(copy, nonatomic) MPSectionedCollection *playlistEntries; // @synthesize playlistEntries=_playlistEntries;
@property(retain, nonatomic) MPMediaLibrary *mediaLibrary; // @synthesize mediaLibrary=_mediaLibrary;
- (id)newOperationWithLocalPersistenceResponseHandler:(CDUnknownBlockType)arg1 completeResponseHandler:(CDUnknownBlockType)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

