//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "NSCopying.h"

@class NSString;

@interface FBSSceneSpecification : NSObject <NSCopying, BSDescriptionProviding>
{
    BOOL _forLocalSynchronousSceneClientProvider;
}

+ (id)specification;
+ (void)initialize;
+ (CDUnknownFunctionPointerType)_swizzleMethodOnClass:(Class)arg1 originalSelector:(SEL)arg2 block:(id)arg3;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)_copyForLocalSynchronousSceneClientProvider;
- (BOOL)isValid;
@property(readonly, nonatomic) Class transitionContextClass;
@property(readonly, nonatomic) Class clientSettingsClass;
@property(readonly, nonatomic) Class settingsClass;
@property(readonly, nonatomic) Class clientAgentClass;
@property(readonly, nonatomic) Class hostAgentClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

