//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, SFPasswordSharingInfo, SFPasswordSharingService;

@protocol SFPasswordSharingServiceDelegate
- (void)service:(SFPasswordSharingService *)arg1 receivedNetworkInfo:(SFPasswordSharingInfo *)arg2;

@optional
- (BOOL)service:(SFPasswordSharingService *)arg1 shouldPromptForNetwork:(NSString *)arg2;
@end

