//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OAETGroup : NSObject
{
}

+ (id)mapGroup:(id)arg1 state:(id)arg2;
+ (void)transferChildrenInSubgroup:(id)arg1 toArray:(id)arg2 sourceGroup:(id)arg3 state:(id)arg4;
+ (void)finalizeGroupsAmongDrawables:(id)arg1 state:(id)arg2;
+ (void)fixBoundsInGroup:(id)arg1 state:(id)arg2;
+ (void)increaseChildAnchoringPrecisionInGroup:(id)arg1 state:(id)arg2;

@end

