//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NSTextField;

@interface IndicatorImageView : NSImageView
{
    struct CGPoint mSavedOrigin;
    NSTextField *mParent;
}

- (void).cxx_destruct;
@property __weak NSTextField *parent; // @synthesize parent=mParent;
- (void)setSavedFrameOrigin:(struct CGPoint)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

