//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class FRAnalyticsReferral, NSString, NSURL;

@interface FRFeedViewContext : NSObject <NSSecureCoding>
{
    BOOL _showSubscribedAlert;
    long long _presentationReason;
    long long _feedPickerSection;
    long long _feedPickerType;
    NSURL *_sourceURL;
    NSString *_sourceApplication;
    NSString *_sourceSearchText;
    NSString *_userActivityType;
    long long _displayRank;
    long long _externalAnalyticsFeedReferrer;
    FRAnalyticsReferral *_referral;
    NSString *_previousArticleID;
    long long _previousArticleVersion;
    NSString *_adPreviewID;
    NSString *_adPreviewSessionID;
    NSString *_adQToken;
    long long _maximumAdRequestsForCurrentAdPreviewID;
}

+ (id)feedViewContextFrom:(id)arg1;
+ (BOOL)supportsSecureCoding;
+ (id)feedContextForForYouTabWithAdPreviewSessionID:(id)arg1 adPreviewID:(id)arg2 maximumAdRequestsForCurrentAdPreviewID:(long long)arg3;
+ (id)feedContextForQuickActions;
+ (id)feedContextForReturnFromArticleView;
+ (id)feedContextForSuccessfulSubscriptionFromEndOfArticle;
+ (id)feedContextForSuccessfulSubscriptionFromPlacard;
+ (id)feedContextForSuccessfulSubscriptionFromRenewal;
+ (id)feedContextForSuccessfulSubscriptionFromAd;
+ (id)feedContextForLocalNotification;
+ (id)feedContextForHandoff;
+ (id)feedContextForStateRestoration;
+ (id)feedContextForRelatedArticles;
+ (id)feedContextForMorePubArticles;
+ (id)feedContextForUserActivityWithSourceApplication:(id)arg1 userActivityType:(id)arg2;
+ (id)feedContextForRelatedArticlesTopicSelection;
+ (id)feedContextForExcerptTopicSelection;
+ (id)feedContextForHistory;
+ (id)feedContextForSaved;
+ (id)feedContextForLinkOpenedFromEditorialHomePageWithURL:(id)arg1 sourceApplication:(id)arg2 previousArticleID:(id)arg3 previousArticleVersion:(id)arg4 adPreviewSessionID:(id)arg5 adPreviewID:(id)arg6 maximumAdRequestsForCurrentAdPreviewID:(long long)arg7;
+ (id)feedContextForLinkWithURL:(id)arg1 sourceApplication:(id)arg2 previousArticleID:(id)arg3 previousArticleVersion:(id)arg4 adPreviewSessionID:(id)arg5 adPreviewID:(id)arg6 adQToken:(id)arg7 maximumAdRequestsForCurrentAdPreviewID:(long long)arg8;
+ (id)feedContextForSearchWithText:(id)arg1 displayRank:(long long)arg2;
+ (id)feedContextForDefaultFeedOnLaunch;
+ (id)unknownFeedContext;
+ (id)feedContextForPresentationReason:(long long)arg1;
- (void).cxx_destruct;
@property(nonatomic) BOOL showSubscribedAlert; // @synthesize showSubscribedAlert=_showSubscribedAlert;
@property(nonatomic) long long maximumAdRequestsForCurrentAdPreviewID; // @synthesize maximumAdRequestsForCurrentAdPreviewID=_maximumAdRequestsForCurrentAdPreviewID;
@property(copy, nonatomic) NSString *adQToken; // @synthesize adQToken=_adQToken;
@property(copy, nonatomic) NSString *adPreviewSessionID; // @synthesize adPreviewSessionID=_adPreviewSessionID;
@property(copy, nonatomic) NSString *adPreviewID; // @synthesize adPreviewID=_adPreviewID;
@property(nonatomic) long long previousArticleVersion; // @synthesize previousArticleVersion=_previousArticleVersion;
@property(copy, nonatomic) NSString *previousArticleID; // @synthesize previousArticleID=_previousArticleID;
@property(retain, nonatomic) FRAnalyticsReferral *referral; // @synthesize referral=_referral;
@property(nonatomic) long long externalAnalyticsFeedReferrer; // @synthesize externalAnalyticsFeedReferrer=_externalAnalyticsFeedReferrer;
@property(nonatomic) long long displayRank; // @synthesize displayRank=_displayRank;
@property(copy, nonatomic) NSString *userActivityType; // @synthesize userActivityType=_userActivityType;
@property(copy, nonatomic) NSString *sourceSearchText; // @synthesize sourceSearchText=_sourceSearchText;
@property(copy, nonatomic) NSString *sourceApplication; // @synthesize sourceApplication=_sourceApplication;
@property(copy, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(nonatomic) long long feedPickerType; // @synthesize feedPickerType=_feedPickerType;
@property(nonatomic) long long feedPickerSection; // @synthesize feedPickerSection=_feedPickerSection;
@property(nonatomic) long long presentationReason; // @synthesize presentationReason=_presentationReason;
- (id)ts_feedViewContext;
- (void)resetCurrentAdPreviewSession;
- (void)validateMaximumNumberOfAdRequestsForCurrentAdPreview;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

