//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _UIStretchableShadow : NSObject
{
}

+ (id)_generateShadowWithRadius:(double)arg1 cornerRadius:(double)arg2 isContinuousCorner:(BOOL)arg3 color:(id)arg4;
+ (struct CGImage *)shadowWithRadius:(double)arg1 cornerRadius:(double)arg2 isContinuousCorner:(BOOL)arg3 white:(double)arg4;
+ (struct CGImage *)shadowWithRadius:(double)arg1 cornerRadius:(double)arg2 white:(double)arg3;
+ (struct CGImage *)shadowWithRadius:(double)arg1 cornerRadius:(double)arg2;

@end

