//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <iCloudDrive/ICDBROperation.h>

#import <iCloudDrive/NSProgressReporting-Protocol.h>

@class ICDBRGlobalProgressProxy, NSOperationQueue, NSProgress, NSString, NSURL;

@interface ICDBRUploadAllFilesForLogOutOperation : ICDBROperation <NSProgressReporting>
{
    ICDBRGlobalProgressProxy *_progress;
    CDUnknownBlockType _uploadAllFilesCompletionBlock;
    NSOperationQueue *_opQueue;
    NSProgress *_evictProgress;
    BOOL _shouldKeepDataLocal;
    NSURL *_rootURL;
}

@property BOOL shouldKeepDataLocal; // @synthesize shouldKeepDataLocal=_shouldKeepDataLocal;
@property(retain) ICDBRGlobalProgressProxy *progress; // @synthesize progress=_progress;
@property(copy) CDUnknownBlockType uploadAllFilesCompletionBlock; // @synthesize uploadAllFilesCompletionBlock=_uploadAllFilesCompletionBlock;
- (void).cxx_destruct;
- (void)finishWithResult:(id)arg1 error:(id)arg2;
- (void)main;
- (BOOL)evictAllFiles;
@property(readonly, copy) NSString *description;
- (void)cancel;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

