//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <iCloudDrive/NSCopying-Protocol.h>
#import <iCloudDrive/NSFileProviderItemDecorating-Protocol.h>
#import <iCloudDrive/NSFileProviderItem_Private-Protocol.h>
#import <iCloudDrive/NSSecureCoding-Protocol.h>

@class ICDBRFileObjectID, NSArray, NSData, NSDate, NSDictionary, NSError, NSFileProviderItemVersion, NSMutableDictionary, NSNumber, NSPersonNameComponents, NSSet, NSString, NSURL;
@protocol NSFileProviderItemFlags;

@interface ICDBRQueryItem : NSObject <NSFileProviderItem_Private, NSFileProviderItemDecorating, NSSecureCoding, NSCopying>
{
    NSString *_appLibraryID;
    NSString *_logicalName;
    NSString *_bookmarkData;
    ICDBRFileObjectID *_fileObjectID;
    ICDBRFileObjectID *_parentFileObjectID;
    ICDBRFileObjectID *_shareRootFileObjectID;
    NSNumber *_size;
    NSNumber *_mtime;
    NSNumber *_btime;
    NSNumber *_lastUsedTime;
    NSNumber *_favoriteRank;
    NSNumber *_childItemCount;
    NSURL *_url;
    NSNumber *_parentZoneRowID;
    NSNumber *_zoneRowID;
    NSData *_contentVersion;
    NSData *_structureVersion;
    NSMutableDictionary *_attrs;
    id _replacement;
    union {
        struct {
            unsigned int downloadStatus:2;
            unsigned int uploadStatus:2;
            unsigned int itemStatus:2;
            unsigned int conflicted:1;
            unsigned int preCrashMarker:1;
            unsigned int isUploadActive:1;
            unsigned int isDownloadActive:1;
            unsigned int isDownloadRequested:1;
            unsigned int shareOptions:3;
            unsigned int isSharedFolderSubItem:1;
            unsigned int possiblyContainsSharedToMeItem:1;
            unsigned int possiblyContainsSharedByMeItem:1;
            unsigned int editedSinceShared:1;
            unsigned int isHiddenExt:1;
            unsigned int isTrashed:1;
            unsigned int itemMode:3;
            unsigned int isEvictable:1;
            unsigned int fromReadOnlyDB:1;
            unsigned int isExcluded:1;
            unsigned char ICDBRQueryItemKind;
            unsigned char kind;
        } ;
        unsigned long long value;
    } _flags;
    long long _logicalHandle;
    long long _physicalHandle;
    unsigned int _documentID;
    unsigned short _diffs;
    BOOL _isNetworkOffline;
    NSDictionary *_xattrs;
}

+ (id)containerItemForContainer:(id)arg1 forceScan:(BOOL)arg2;
+ (BOOL)supportsSecureCoding;
+ (void)initialize;
- (void).cxx_destruct;
- (id)attributesForNames:(id)arg1;
- (id)attributeNames;
- (id)valueForKey:(id)arg1;
- (id)attributeForName:(id)arg1;
@property(nonatomic) id replacement;
- (void)updateURLBasedOnParent:(id)arg1;
- (void)mergeProgressUpdate:(id)arg1;
- (void)merge:(id)arg1;
- (BOOL)canMerge:(id)arg1;
- (void)setAttribute:(id)arg1 forKey:(id)arg2;
- (id)attributeForKey:(id)arg1;
- (void)_mergeURL:(id)arg1;
- (void)_mergeAttrs:(id)arg1;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToQueryItem:(id)arg1;
@property(readonly, nonatomic) NSString *path;
@property(readonly, copy) NSString *description;
- (id)subclassDescription;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithQueryItem:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)attachLogicalExtension:(id)arg1 physicalExtension:(id)arg2;
- (void)setURL:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *fp_spotlightDomainIdentifier;
- (id)sharedItemRole;
- (BOOL)isHiddenExt;
@property(readonly, nonatomic) BOOL isEvictable;
@property(readonly, nonatomic, getter=isTrashed) BOOL trashed;
@property(readonly, nonatomic) BOOL editedSinceShared;
@property(readonly, nonatomic) BOOL isDocument;
@property(readonly, nonatomic) BOOL isFinderBookmark;
@property(readonly, nonatomic) BOOL isSymlink;
@property(readonly, nonatomic) BOOL isPackage;
@property(readonly, nonatomic) BOOL isDirectory;
@property(readonly, nonatomic) BOOL isUploadActive;
@property(retain, nonatomic) NSNumber *isDownloadRequested;
@property(readonly, copy, getter=isDownloadRequested) NSNumber *downloadRequested;
@property(nonatomic) BOOL isDownloadActive;
@property(nonatomic) BOOL isPreCrash;
- (void)clearDiffs;
- (void)markDead;
@property(readonly, nonatomic) BOOL isDead;
@property(readonly, nonatomic) BOOL isLive;
@property(readonly, nonatomic) BOOL isConflicted;
@property(readonly, nonatomic) BOOL isInTransfer;
@property(readonly, nonatomic) unsigned int icd_shareOptions;
@property(readonly, nonatomic) unsigned short icd_uploadStatus;
@property(nonatomic) unsigned short icd_downloadStatus;
@property(nonatomic) BOOL isNetworkOffline;
@property(readonly, nonatomic) NSData *versionIdentifier;
@property(readonly, nonatomic) NSNumber *favoriteRank;
@property(readonly, copy, nonatomic) NSData *tagData;
@property(readonly, copy, nonatomic) NSDate *lastUsedDate;
@property(readonly, nonatomic) NSNumber *lastUsedTime;
@property(readonly, nonatomic) NSNumber *btime;
@property(readonly, nonatomic) NSNumber *mtime;
@property(readonly, nonatomic) NSNumber *size;
@property(readonly, nonatomic) NSString *appLibraryID;
@property(readonly, nonatomic) NSString *physicalName;
@property(readonly, nonatomic) NSString *logicalName;
@property(readonly, nonatomic) ICDBRFileObjectID *parentFileObjectID;
@property(readonly, nonatomic) ICDBRFileObjectID *fileObjectID;
@property(readonly, nonatomic) unsigned short diffs;
@property(readonly, copy) NSString *containerDisplayName;
@property(readonly, nonatomic) NSURL *url;
@property(readonly, copy) NSString *sharingPermissions;
@property(readonly, nonatomic) NSPersonNameComponents *mostRecentEditorNameComponents;
@property(readonly, nonatomic) NSPersonNameComponents *ownerNameComponents;
- (id)owner;
@property(readonly, nonatomic, getter=fp_isLastModifiedByCurrentUser) BOOL fp_lastModifiedByCurrentUser;
@property(readonly, nonatomic, getter=isSharedByCurrentUser) BOOL sharedByCurrentUser;
- (BOOL)_isSharedFolderSubItem;
@property(readonly, nonatomic, getter=isTopLevelSharedItem) BOOL topLevelSharedItem;
@property(readonly, nonatomic, getter=isShared) BOOL shared;
@property(readonly, copy) NSNumber *hasUnresolvedConflicts;
@property(readonly, copy, nonatomic) NSError *downloadingError;
- (id)downloadingStatus;
@property(readonly, copy, nonatomic) NSError *uploadingError;
@property(readonly, nonatomic, getter=isUploading) BOOL uploading;
@property(readonly, nonatomic, getter=isUploaded) BOOL uploaded;
@property(readonly, nonatomic, getter=isMostRecentVersionDownloaded) BOOL mostRecentVersionDownloaded;
@property(readonly, nonatomic, getter=isDownloading) BOOL downloading;
@property(readonly, nonatomic, getter=isDownloaded) BOOL downloaded;
@property(readonly, nonatomic, getter=isExcludedFromSync) BOOL excludedFromSync;
- (id)filePath;
@property(readonly, copy, nonatomic) NSDate *contentModificationDate;
@property(readonly, copy, nonatomic) NSDate *creationDate;
- (id)fileSize;
@property(readonly, copy, nonatomic) NSNumber *childItemCount;
@property(readonly, nonatomic) NSDictionary *extendedAttributes;
@property(readonly, nonatomic) id <NSFileProviderItemFlags> flags;
@property(readonly, nonatomic) unsigned long long capabilities;
@property(readonly, nonatomic) NSArray *decorations;
@property(readonly, nonatomic) NSDictionary *userInfo;
@property(readonly, copy) NSURL *fileURL;
- (BOOL)_isInSharedZone;
@property(readonly, getter=isHidden) BOOL hidden;
@property(readonly, nonatomic) NSFileProviderItemVersion *itemVersion;
@property(readonly, copy, nonatomic) NSNumber *documentSize;
@property(readonly, copy, nonatomic) NSString *typeIdentifier;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly, copy, nonatomic) NSString *filename;
@property(readonly, copy, nonatomic) NSString *parentItemIdentifier;
@property(readonly, copy, nonatomic) NSString *itemIdentifier;
@property(readonly, copy) NSString *fp_cloudContainerIdentifier;
@property(readonly) BOOL fp_isContainerPristine;
@property(readonly) BOOL fp_isContainer;
- (id)containerIDIfDesktopOrDocuments;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *fileSystemFilename;
@property(readonly, nonatomic, getter=fp_isAddedByCurrentUser) BOOL fp_addedByCurrentUser;
@property(readonly, nonatomic) NSPersonNameComponents *fp_addedByNameComponents;
@property(readonly, copy) NSSet *fp_cloudContainerClientBundleIdentifiers;
@property(readonly, copy) NSString *fp_domainIdentifier;
@property(readonly, copy) NSString *fp_parentDomainIdentifier;
@property(readonly, getter=fp_isUbiquitous) BOOL fp_ubiquitous;
@property(readonly, nonatomic) BOOL isTrashed;
@property(readonly, nonatomic) NSString *preformattedMostRecentEditorName;
@property(readonly, nonatomic) NSString *preformattedOwnerName;
@property(readonly, copy) NSString *providerIdentifier;
@property(readonly) Class superclass;

@end

