//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudPhotoLibrary/CPLEngineStorage.h>

#import <CloudPhotoLibrary/CPLAbstractObject-Protocol.h>

@class CPLPlatformObject, NSArray, NSString;

@interface CPLEngineClientCache : CPLEngineStorage <CPLAbstractObject>
{
    NSArray *__lastModifiedProperties;
}

- (void).cxx_destruct;
@property(copy, setter=_setLastModifiedProperties:) NSArray *_lastModifiedProperties; // @synthesize _lastModifiedProperties=__lastModifiedProperties;
- (void)fillRelatedIdentifiersInChange:(id)arg1;
- (id)statusDictionary;
- (id)status;
- (id)resourceOfType:(unsigned long long)arg1 forRecordWithScopedIdentifier:(id)arg2 recordClass:(Class *)arg3 error:(id *)arg4;
- (id)resourceOfType:(unsigned long long)arg1 forRecordWithScopedIdentifier:(id)arg2 error:(id *)arg3;
- (BOOL)applyBatch:(id)arg1 direction:(unsigned long long)arg2 withError:(id *)arg3;
- (id)localChangeBatchFromCloudBatch:(id)arg1 usingMapping:(id)arg2 withError:(id *)arg3;
- (id)compactedBatchFromExpandedBatch:(id)arg1;
- (unsigned long long)countOfRecordsWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;
- (BOOL)hasRecordWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;
- (id)recordsWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;
- (id)recordsWithRelatedScopedIdentifier:(id)arg1;
- (BOOL)hasRecordWithScopedIdentifier:(id)arg1;
- (id)relatedScopedIdentifierForRecordWithScopedIdentifier:(id)arg1;
- (id)_relatedScopedIdentifierForRecordWithScopedIdentifier:(id)arg1;
- (id)recordWithScopedIdentifier:(id)arg1;
- (BOOL)deleteRecordWithScopedIdentifier:(id)arg1 error:(id *)arg2;
- (BOOL)updateRecord:(id)arg1 error:(id *)arg2;
- (BOOL)addRecord:(id)arg1 error:(id *)arg2;
- (BOOL)deleteRecordsForScopeIndex:(long long)arg1 maxCount:(long long)arg2 deletedCount:(long long *)arg3 error:(id *)arg4;
- (unsigned long long)scopeType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) CPLPlatformObject *platformObject;
@property(readonly) Class superclass;

@end

