//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Vision/NSCopying-Protocol.h>
#import <Vision/NSSecureCoding-Protocol.h>
#import <Vision/VNRequestRevisionProviding-Protocol.h>

@class VNFaceAttributeCategory;

@interface VNFaceAttributes : NSObject <NSSecureCoding, NSCopying, VNRequestRevisionProviding>
{
    VNFaceAttributeCategory *_ageCategory;
    VNFaceAttributeCategory *_genderCategory;
    VNFaceAttributeCategory *_eyesCategory;
    VNFaceAttributeCategory *_smilingCategory;
    VNFaceAttributeCategory *_faceHairCategory;
    VNFaceAttributeCategory *_hairColorCategory;
    VNFaceAttributeCategory *_baldCategory;
    VNFaceAttributeCategory *_glassesCategory;
    VNFaceAttributeCategory *_makeupCategory;
    VNFaceAttributeCategory *_makeupEyesCategory;
    VNFaceAttributeCategory *_makeupLipsCategory;
    unsigned long long _requestRevision;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) unsigned long long requestRevision; // @synthesize requestRevision=_requestRevision;
@property(retain) VNFaceAttributeCategory *makeupLipsCategory; // @synthesize makeupLipsCategory=_makeupLipsCategory;
@property(retain) VNFaceAttributeCategory *makeupEyesCategory; // @synthesize makeupEyesCategory=_makeupEyesCategory;
@property(retain) VNFaceAttributeCategory *makeupCategory; // @synthesize makeupCategory=_makeupCategory;
@property(retain) VNFaceAttributeCategory *glassesCategory; // @synthesize glassesCategory=_glassesCategory;
@property(retain) VNFaceAttributeCategory *baldCategory; // @synthesize baldCategory=_baldCategory;
@property(retain) VNFaceAttributeCategory *hairColorCategory; // @synthesize hairColorCategory=_hairColorCategory;
@property(retain) VNFaceAttributeCategory *faceHairCategory; // @synthesize faceHairCategory=_faceHairCategory;
@property(retain) VNFaceAttributeCategory *smilingCategory; // @synthesize smilingCategory=_smilingCategory;
@property(retain) VNFaceAttributeCategory *eyesCategory; // @synthesize eyesCategory=_eyesCategory;
@property(retain) VNFaceAttributeCategory *genderCategory; // @synthesize genderCategory=_genderCategory;
@property(retain) VNFaceAttributeCategory *ageCategory; // @synthesize ageCategory=_ageCategory;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRequestRevision:(unsigned long long)arg1;

@end

