//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PXAssetReference;

@interface _PXAssetsSceneAnchor : NSObject
{
    PXAssetReference *_assetReference;
    double _distance;
    struct CGPoint _anchorOrigin;
}

@property(readonly, nonatomic) double distance; // @synthesize distance=_distance;
@property(readonly, nonatomic) struct CGPoint anchorOrigin; // @synthesize anchorOrigin=_anchorOrigin;
@property(readonly, nonatomic) PXAssetReference *assetReference; // @synthesize assetReference=_assetReference;
- (void).cxx_destruct;
- (id)initWithAssetReference:(id)arg1 anchorOrigin:(struct CGPoint)arg2 distance:(double)arg3;

@end

