//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class CWInterface, NSButton, NSPopUpButton, NSProgressIndicator, SFAuthorization, WDFrameCapture, WDXPCClient;

@interface WDCaptureWindowController : NSWindowController
{
    NSProgressIndicator *_captureIndicator;
    NSButton *_captureButton;
    NSPopUpButton *_channelPopupButton;
    NSPopUpButton *_channelWidthPopupButton;
    BOOL _isCapturingWiFiTraffic;
    BOOL _isSetup;
    WDFrameCapture *_wdCapture;
    WDXPCClient *_xpcClient;
    SFAuthorization *_authorization;
    CWInterface *_interface;
}

@property(retain) CWInterface *interface; // @synthesize interface=_interface;
@property(retain) SFAuthorization *authorization; // @synthesize authorization=_authorization;
@property(retain) WDXPCClient *xpcClient; // @synthesize xpcClient=_xpcClient;
- (void).cxx_destruct;
- (void)populateChannels;
- (void)onCaptureButton:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)setup;

@end

