//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UGCPOIEnrichmentEditorCell.h"

#import "UGCRatingCategoryLikeDislikeViewDelegate-Protocol.h"

@class NSString, UGCRatingCategoryLikeDislikeView, UIFont, UILabel;
@protocol UGCRatingCategoryTableViewCellDelegate;

__attribute__((visibility("hidden")))
@interface UGCRatingCategoryCell : UGCPOIEnrichmentEditorCell <UGCRatingCategoryLikeDislikeViewDelegate>
{
    UILabel *_categoryLabel;
    UGCRatingCategoryLikeDislikeView *_likeDislikeView;
    NSString *_key;
    long long _currentState;
    id <UGCRatingCategoryTableViewCellDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <UGCRatingCategoryTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void)setHasHeaderEmphasis:(BOOL)arg1;
@property(readonly, nonatomic) UIFont *ratingLabelFont;
@property(retain, nonatomic) NSString *titleString;
- (void)_updateState:(long long)arg1;
- (void)likeDislikeViewDidSelectDislike:(id)arg1;
- (void)likeDislikeViewDidSelectLike:(id)arg1;
- (void)_setupConstraints;
- (void)_contentSizeChanged;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

