//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsThemeViewController.h"

#import "AirQualityConditionsViewControllerDelegate-Protocol.h"
#import "WeatherConditionsViewControllerDelegate-Protocol.h"
#import "WeatherLocationDataProviderObserver-Protocol.h"

@class AirQualityConditionsViewController, NSNumber, NSObject, NSString, UIStackView, UIView, UIVisualEffectView, WFLocation, WeatherConditionsViewController;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface WeatherStackViewController : MapsThemeViewController <WeatherLocationDataProviderObserver, WeatherConditionsViewControllerDelegate, AirQualityConditionsViewControllerDelegate>
{
    BOOL _updatingVisibility;
    NSString *_blurGroupName;
    UIView *_contentView;
    UIVisualEffectView *_blurView;
    UIStackView *_stackView;
    WFLocation *_location;
    AirQualityConditionsViewController *_airQualityConditionsViewController;
    WeatherConditionsViewController *_weatherConditionsViewController;
    NSNumber *_requestedAirQualityShown;
    NSNumber *_requestedWeatherShown;
    NSObject<OS_dispatch_source> *_updateVisibilityTimer;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL updatingVisibility; // @synthesize updatingVisibility=_updatingVisibility;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *updateVisibilityTimer; // @synthesize updateVisibilityTimer=_updateVisibilityTimer;
@property(retain, nonatomic) NSNumber *requestedWeatherShown; // @synthesize requestedWeatherShown=_requestedWeatherShown;
@property(retain, nonatomic) NSNumber *requestedAirQualityShown; // @synthesize requestedAirQualityShown=_requestedAirQualityShown;
@property(retain, nonatomic) WeatherConditionsViewController *weatherConditionsViewController; // @synthesize weatherConditionsViewController=_weatherConditionsViewController;
@property(retain, nonatomic) AirQualityConditionsViewController *airQualityConditionsViewController; // @synthesize airQualityConditionsViewController=_airQualityConditionsViewController;
@property(retain, nonatomic) WFLocation *location; // @synthesize location=_location;
@property(nonatomic) __weak UIStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) __weak UIVisualEffectView *blurView; // @synthesize blurView=_blurView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSString *blurGroupName; // @synthesize blurGroupName=_blurGroupName;
- (id)_weatherPunchOutURL;
- (void)_openWeatherPunchOutURL;
- (void)_configureWeatherOrbSupport;
- (void)_configureSubviews;
- (void)_updateVisibilityAnimated:(BOOL)arg1;
- (void)_requestVisibilityUpdateAnimated:(BOOL)arg1;
- (void)_setCornerRadiusWithMaskedCorners:(unsigned long long)arg1 withValue:(double)arg2;
- (void)airQualityConditionsViewController:(id)arg1 makeVisible:(BOOL)arg2 animated:(BOOL)arg3;
- (void)weatherConditionsViewController:(id)arg1 makeVisible:(BOOL)arg2 animated:(BOOL)arg3;
- (void)weatherLocationDataProvider:(id)arg1 didChangeLocation:(id)arg2;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithWeatherLocationDataProvider:(id)arg1;
- (BOOL)_canShowWhileLocked;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

