//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AudioVideoBridging/AVB17221AEMObject.h>

#import <AudioVideoBridging/NSCopying-Protocol.h>

@interface AVB17221AEMStreamFormat : AVB17221AEMObject <NSCopying>
{
    unsigned long long streamFormat;
}

+ (id)keyPathsForValuesAffectingFormatEUI;
+ (id)keyPathsForValuesAffectingFormatID;
+ (id)keyPathsForValuesAffectingProtocolType;
+ (id)keyPathsForValuesAffectingVideoFormat;
+ (id)keyPathsForValuesAffectingSamplesPerFrame;
+ (id)keyPathsForValuesAffectingChannelsPerFrame;
+ (id)keyPathsForValuesAffectingLinearSampleMSB;
+ (id)keyPathsForValuesAffectingAudioFormat;
+ (id)keyPathsForValuesAffectingNominalSampleRate;
+ (id)keyPathsForValuesAffectingColorSpace;
+ (id)keyPathsForValuesAffectingCompressionMode;
+ (id)keyPathsForValuesAffectingVideoMode;
+ (id)keyPathsForValuesAffectingSmpteCnt;
+ (id)keyPathsForValuesAffectingMidiCnt;
+ (id)keyPathsForValuesAffectingMblaCnt;
+ (id)keyPathsForValuesAffectingIec60958Cnt;
+ (id)keyPathsForValuesAffectingNonblockingMode;
+ (id)keyPathsForValuesAffectingBlockingMode;
+ (id)keyPathsForValuesAffectingDbs;
+ (id)keyPathsForValuesAffectingFdfSfc;
+ (id)keyPathsForValuesAffectingFdfEvt;
+ (id)keyPathsForValuesAffectingFmt;
+ (id)keyPathsForValuesAffectingIidcRate;
+ (id)keyPathsForValuesAffectingIidcFormat;
+ (id)keyPathsForValuesAffectingSf;
+ (id)keyPathsForValuesAffectingSubtype;
+ (id)keyPathsForValuesAffectingVendorFormat;
@property unsigned long long streamFormat; // @synthesize streamFormat;
- (unsigned short)maximumIntervalFrames;
- (unsigned int)maximumPayloadSize;
- (void)setSamplingRate:(id)arg1;
- (BOOL)isVideoFormat;
- (BOOL)isAudioFormat;
- (BOOL)isSupportedVideoFormat;
- (BOOL)isSupportedAudioFormat;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)debugLogStringWithIndentation:(id)arg1;
- (BOOL)updateWithXML:(id)arg1;
- (id)xmlRepresentation;
- (id)plistRepresentation;
- (BOOL)updateWithPlistEntry:(id)arg1;
@property unsigned long long formatEUI; // @dynamic formatEUI;
@property unsigned long long formatID; // @dynamic formatID;
@property unsigned char protocolType; // @dynamic protocolType;
@property unsigned char videoFormat; // @dynamic videoFormat;
@property unsigned short samplesPerFrame; // @dynamic samplesPerFrame;
@property unsigned short channelsPerFrame; // @dynamic channelsPerFrame;
@property unsigned char linearSampleMSB; // @dynamic linearSampleMSB;
@property unsigned char audioFormat; // @dynamic audioFormat;
@property unsigned char nominalSampleRate; // @dynamic nominalSampleRate;
@property unsigned char colorSpace; // @dynamic colorSpace;
@property unsigned char compressionMode; // @dynamic compressionMode;
@property unsigned char videoMode; // @dynamic videoMode;
@property unsigned char smpteCnt; // @dynamic smpteCnt;
@property unsigned char midiCnt; // @dynamic midiCnt;
@property unsigned char mblaCnt; // @dynamic mblaCnt;
@property unsigned char iec60958Cnt; // @dynamic iec60958Cnt;
@property(getter=isNonblockingMode) BOOL nonblockingMode; // @dynamic nonblockingMode;
@property(getter=isBlockingMode) BOOL blockingMode; // @dynamic blockingMode;
@property unsigned char dbs; // @dynamic dbs;
@property unsigned char fdfSfc; // @dynamic fdfSfc;
@property unsigned char fdfEvt; // @dynamic fdfEvt;
@property unsigned char fmt; // @dynamic fmt;
@property unsigned char iidcRate; // @dynamic iidcRate;
@property unsigned short iidcFormat; // @dynamic iidcFormat;
@property unsigned char sf; // @dynamic sf;
@property unsigned char subtype; // @dynamic subtype;
@property BOOL vendorFormat; // @dynamic vendorFormat;

@end

