//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class NSString;

@protocol SCNJSImageJSExport <JSExport>
+ (id)imageWithPath:(NSString *)arg1;
+ (id)imageWithURL:(NSString *)arg1;
@property struct CGSize size;
@end

