//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

#import "AggregateViewOrientation-Protocol.h"

@class NSMutableDictionary;
@protocol AMSInOutLayerDataSource, AMSInOutLayerEditor;

@interface AMSChannelSubLayer : CALayer <AggregateViewOrientation>
{
    BOOL isInput;
    BOOL isEditing;
    int highlightedChannel;
    double minWidth;
    double maxWidth;
    double editWidth;
    NSMutableDictionary *channelNames;
    id <AMSInOutLayerDataSource> dataSource;
    id <AMSInOutLayerEditor> editor;
    unsigned long long numChannelsCache;
    double widestChannelLabelString;
    unsigned long long _orientation;
}

+ (void)initialize;
@property(readonly) double maxWidth; // @synthesize maxWidth;
@property(readonly) double minWidth; // @synthesize minWidth;
@property BOOL isInput; // @synthesize isInput;
- (void).cxx_destruct;
- (unsigned int)numChannels;
- (double)widestChannel;
- (double)widestChannelNumberLabel;
- (void)setEditor:(id)arg1;
- (void)setDataSource:(id)arg1;
- (void)reloadData;
- (void)computeLayerSize;
- (void)drawInContext:(struct CGContext *)arg1;
- (struct CGPoint)locationForHighlightedChannel;
- (struct CGPoint)locationForChannel:(unsigned int)arg1;
- (void)highlightChannelAtLocation:(struct CGPoint)arg1;
@property int highlightedChannel;
- (double)calculateMinWidth;
- (void)updateLabel;
@property BOOL isEditing;
- (int)indexOfTextLayer:(id)arg1;
- (struct CGRect)editingRectForEditedChannel;
- (struct CGRect)rectForChannel:(unsigned int)arg1;
- (void)setDisplaySize:(double)arg1;
- (BOOL)hasChannelNameForIndex:(unsigned int)arg1;
- (double)widthOfChannelAtIndex:(unsigned int)arg1;
@property unsigned long long orientation; // @synthesize orientation=_orientation;
- (id)init;

@end

