//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSButton, NSImageView, NSProgressIndicator, iDamDevice;

@interface AMSIDamDeviceTableCellView : NSTableCellView
{
    BOOL hasObservers;
    iDamDevice *_device;
    NSButton *_enableButton;
    NSImageView *_errorImageView;
    NSProgressIndicator *_workingIndicator;
}

@property __weak NSProgressIndicator *workingIndicator; // @synthesize workingIndicator=_workingIndicator;
@property __weak NSImageView *errorImageView; // @synthesize errorImageView=_errorImageView;
@property __weak NSButton *enableButton; // @synthesize enableButton=_enableButton;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain) iDamDevice *device; // @synthesize device=_device;
- (void)removeObservers;
- (void)addObservers;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)dealloc;
- (void)prepareForReuse;
- (void)enableButtonToggled:(id)arg1;

@end

