//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ScriptingBridge/SBObject.h>

@class NSDate, NSString;

@interface _AMiDVDPrintSettings : SBObject
{
}

- (long long)unlockBurningDevice:(id)arg1;
- (long long)startVideo_tsFolderBurnPath:(id)arg1;
- (long long)startMagicIDVDTheme:(id)arg1 title:(id)arg2;
- (long long)startDiscImageBurnPath:(id)arg1;
- (long long)startBurnWithBurner:(id)arg1 eraseRewritable:(BOOL)arg2;
- (long long)showObjectWithName:(id)arg1;
- (long long)saveProjectPath:(id)arg1;
- (void)quit;
- (long long)openTrayOfBurner:(id)arg1;
- (long long)openProjectPath:(id)arg1;
- (long long)newProjectName:(id)arg1 path:(id)arg2 saveCurrent:(BOOL)arg3;
- (long long)createMagicIDVD;
- (long long)closeTrayOfBurner:(id)arg1 lockDevice:(BOOL)arg2;
- (long long)automaticallyFillDropZonesInCurrentMenu;
- (long long)archiveProjectPath:(id)arg1 encodedAssets:(BOOL)arg2 themes:(BOOL)arg3;
- (long long)addSlideshowForMagicIDVDAndImagePaths:(id)arg1 withName:(id)arg2 andAudioPaths:(id)arg3;
- (long long)addMovieForMagicIDVDWithPath:(id)arg1;
- (void)saveAs:(id)arg1 in:(id)arg2;
- (void)moveTo:(id)arg1;
- (BOOL)exists;
- (void)duplicateTo:(id)arg1 withProperties:(id)arg2;
- (void)delete;
- (void)closeSaving:(int)arg1 savingIn:(id)arg2;
@property(copy) NSString *targetPrinter;
@property(copy) NSString *faxNumber;
@property int errorHandling;
@property(copy) NSDate *requestedPrintTime;
@property long long pagesDown;
@property long long pagesAcross;
@property long long endingPage;
@property long long startingPage;
@property BOOL collating;
@property long long copies;

@end

