//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DBSerializable.h"
#import "NSCopying.h"

@class DBFILESDimensions, DBFILESGpsCoordinates, NSDate, NSString;

@interface DBFILESMediaMetadata : NSObject <DBSerializable, NSCopying>
{
    DBFILESDimensions *_dimensions;
    DBFILESGpsCoordinates *_location;
    NSDate *_timeTaken;
}

+ (id)deserialize:(id)arg1;
+ (id)serialize:(id)arg1;
@property(readonly, nonatomic) NSDate *timeTaken; // @synthesize timeTaken=_timeTaken;
@property(readonly, nonatomic) DBFILESGpsCoordinates *location; // @synthesize location=_location;
@property(readonly, nonatomic) DBFILESDimensions *dimensions; // @synthesize dimensions=_dimensions;
- (void).cxx_destruct;
- (BOOL)isEqualToMediaMetadata:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)initDefault;
- (id)initWithDimensions:(id)arg1 location:(id)arg2 timeTaken:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

