//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RDModel.h>

@interface RDSearchableProperty : RDModel
{
}

+ (id)numberPropertyForValue:(id)arg1 withValueType:(unsigned char)arg2;
+ (id)fixedPrecisionNumberForNumber:(id)arg1 precision:(unsigned long long)arg2;
+ (id)decimalRounderForPrecision:(unsigned long long)arg1;
+ (id)stringPropertyForValue:(id)arg1 withValueType:(unsigned char)arg2;
+ (unsigned char)propertyValueTypeFromKey:(id)arg1 propertyType:(unsigned short)arg2;
+ (id)convertKeyPath:(id)arg1 toKeyAndType:(unsigned short *)arg2;
+ (id)prefixForKeyPath:(id)arg1;
+ (unsigned char)propertyValueTypeForKeyPath:(id)arg1;
+ (id)keyPathForKey:(id)arg1 propertyType:(unsigned short)arg2;
+ (id)stringFromPropertyType:(unsigned short)arg1;
+ (unsigned short)propertyTypeForKeyPath:(id)arg1;
+ (unsigned short)propertyTypeFromString:(id)arg1;
+ (id)reusablePropertyKey:(id)arg1;
+ (void)initialize;
- (id)initWithUuid:(id)arg1 inDatabase:(id)arg2;
- (id)initWithUuid:(id)arg1 forTable:(id)arg2;
- (id)init;

@end

