//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError;

@interface _PHValidation : NSObject
{
    unsigned long long _requestedOptions;
    unsigned long long _validatedOptions;
    NSError *_error;
}

- (void).cxx_destruct;
- (BOOL)isValid:(id *)arg1;
- (void)assert:(BOOL)arg1 error:(id)arg2;
- (void)assert:(BOOL)arg1 format:(id)arg2;
- (void)validateOption:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)initWithOptions:(unsigned long long)arg1;

@end

