//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle, NSString, ODUMCXRecord;

@interface XAAuthController : NSObject
{
    NSString *_mUserDisplayName;
    NSString *_mHomeVolumeName;
    ODUMCXRecord *_mDefaultAdminMCXRecord;
    BOOL _mAuthOnDeny;
    NSBundle *mBundle;
    BOOL _mAllowed;
    BOOL _mDenied;
    BOOL _mSaved;
    BOOL mAuthOnDeny;
    BOOL mAllowed;
    BOOL mDenied;
    BOOL mSaved;
    NSString *mUserDisplayName;
    NSString *mHomeVolumeName;
    ODUMCXRecord *mDefaultAdminMCXRecord;
}

+ (id)createWithInfo:(id)arg1 homeVolumeName:(id)arg2 defaultAdminMCXRecord:(id)arg3 saveCheckboxChecked:(BOOL)arg4 authOnDeny:(BOOL)arg5;
@property BOOL mSaved; // @synthesize mSaved;
@property BOOL mDenied; // @synthesize mDenied;
@property BOOL mAllowed; // @synthesize mAllowed;
@property(readonly) BOOL mAuthOnDeny; // @synthesize mAuthOnDeny;
@property(readonly, retain) ODUMCXRecord *mDefaultAdminMCXRecord; // @synthesize mDefaultAdminMCXRecord;
@property(readonly, retain) NSString *mHomeVolumeName; // @synthesize mHomeVolumeName;
@property(readonly, retain) NSString *mUserDisplayName; // @synthesize mUserDisplayName;
- (void)dealloc;
- (id)initWithInfo:(id)arg1 homeVolumeName:(id)arg2 defaultAdminMCXRecord:(id)arg3 saveCheckboxChecked:(BOOL)arg4 authOnDeny:(BOOL)arg5;

@end

