//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Plugin.h"

@class NSMenu, NSString, NSTimer, WebView;

__attribute__((visibility("hidden")))
@interface HTMLPlugin : Plugin
{
    NSTimer *_autoReloadTimer;
    WebView *_webView;
    NSMenu *_menu;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)arg1;
+ (id)webScriptNameForSelector:(SEL)arg1;
+ (BOOL)isSelectorExcludedFromWebScript:(SEL)arg1;
@property(retain, nonatomic) NSMenu *menu; // @synthesize menu=_menu;
@property(retain, nonatomic) WebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSTimer *autoReloadTimer; // @synthesize autoReloadTimer=_autoReloadTimer;
- (void).cxx_destruct;
- (void)showWebInspector;
- (void)showMenu;
- (void)addMenuSeperatorItem;
- (void)addMenuItems:(id)arg1;
- (void)addMenuItem:(id)arg1;
- (void)resetMenu;
- (void)resizeToFit;
- (void)setReloadInterval:(id)arg1;
@property(readonly, nonatomic) NSString *reloadInterval;
- (void)log:(id)arg1;
- (id)arrayFromWebScriptObject:(id)arg1;
- (BOOL)isWebScriptObjectInstanceOfArray:(id)arg1;
- (id)dictionaryFromWebScriptObject:(id)arg1;
- (id)arrayOfKeysFromWebScriptObject:(id)arg1;
- (BOOL)webView:(id)arg1 shouldChangeSelectedDOMRange:(id)arg2 toDOMRange:(id)arg3 affinity:(unsigned long long)arg4 stillSelecting:(BOOL)arg5;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (void)webView:(id)arg1 addMessageToConsole:(id)arg2;
- (void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)resizeWebViewToFitContents;
- (void)rebuildMenuForStatusItem:(id)arg1;
- (void)reloadWebView;
- (void)reinitAutoReloadTimer;
- (BOOL)refresh;

@end

