//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface PFCloudKitMetadataCache : NSObject
{
    NSMutableDictionary *_recordZoneIDToZoneMetadata;
    NSMutableDictionary *_objectIDToRecordMetadata;
    NSMutableDictionary *_recordIDToMirroredRelationshipOrRecordMetadata;
    NSMutableDictionary *_mtmKeyToMirroredRelationship;
    NSMutableDictionary *_objectIDToRelationshipNameToExistingMTMKeys;
    NSMutableSet *_invalidatedMTMKeys;
}

- (void)cacheZoneMetadata:(id)arg1;
- (id)zoneMetadataForZoneID:(id)arg1;
- (void)_addMirroredRelationshipMTMKey:(id)arg1 forObjectWithID:(id)arg2 andRelationshipName:(id)arg3;
- (void)registerRecordMetadata:(id)arg1 forObject:(id)arg2;
- (void)registerMirroredRelationship:(id)arg1 forKey:(id)arg2;
- (id)mtmKeysRelatedToObjectWithID:(id)arg1 byRelationshipWithName:(id)arg2;
- (id)mirroredRelationshipForKey:(id)arg1;
- (id)recordMetadataForRecordID:(id)arg1;
- (id)mirroredRelationshipForRecordID:(id)arg1;
- (id)recordMetadataForObjectID:(id)arg1;
- (id)recordMetadataForObject:(id)arg1;
- (id)_metadataForRecordID:(id)arg1;
- (BOOL)cacheMetadataForObjectsWithIDs:(id)arg1 andRecordsWithIDs:(id)arg2 inStore:(id)arg3 withManagedObjectContext:(id)arg4 error:(id *)arg5;
- (void)dealloc;
- (id)init;

@end

