//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebView.h"

@interface WebView (FSM)
- (BOOL)isTransparent;
- (void)setTransparent:(BOOL)arg1;
- (void)handleURLRequest:(id)arg1 fromWebView:(id)arg2 withListener:(id)arg3 ignoringAbout:(BOOL)arg4;
- (double)documentHeight;
- (struct CGRect)clipRect;
@end

