//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMMediaRemoteController.h"

#import "MTPlaybackQueueControllerSessionDelegate-Protocol.h"

@class MPRemoteCommandCenter, MTDefaultsChangeNotifier, MTSiriAnalyticsController, NSArray, NSString;

@interface MTMediaRemoteController : IMMediaRemoteController <MTPlaybackQueueControllerSessionDelegate>
{
    MPRemoteCommandCenter *_metadataCommandCenter;
    long long _remoteSkipPreference;
    MTSiriAnalyticsController *_siriAnalyticsController;
    MTDefaultsChangeNotifier *_defaultsObserver;
    NSArray *_internalRequestLabels;
}

@property(retain, nonatomic) NSArray *internalRequestLabels; // @synthesize internalRequestLabels=_internalRequestLabels;
@property(retain, nonatomic) MTDefaultsChangeNotifier *defaultsObserver; // @synthesize defaultsObserver=_defaultsObserver;
@property(retain, nonatomic) MTSiriAnalyticsController *siriAnalyticsController; // @synthesize siriAnalyticsController=_siriAnalyticsController;
@property(nonatomic) long long remoteSkipPreference; // @synthesize remoteSkipPreference=_remoteSkipPreference;
@property(retain, nonatomic) MPRemoteCommandCenter *metadataCommandCenter; // @synthesize metadataCommandCenter=_metadataCommandCenter;
- (void).cxx_destruct;
- (id)_skipBackwardCommandEvent;
- (id)_skipForwardCommandEvent;
- (BOOL)_commandEventIsInternal:(id)arg1;
- (BOOL)_commandEventIsFromSiri:(id)arg1;
- (void)updateRemoteSkipPreferenceFromDefaults:(id)arg1;
- (void)updatePreferredSkipDurationsFromUserDefaults:(id)arg1 forCommandCenter:(id)arg2;
- (void)sessionIdentifierDidChange;
- (long long)remoteChangePlaybackRate:(id)arg1;
- (long long)remotePreviousTrack:(id)arg1;
- (long long)remoteNextTrack:(id)arg1;
- (void)remoteTogglePlayPauseCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (long long)remotePause:(id)arg1;
- (void)remotePlayCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remoteSetPlaybackSessionCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remoteSetPlaybackQueueCommand:(id)arg1 isMagicMoment:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)remoteSetPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remoteSetMetadataPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remoteRemoveFromPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remoteReorderPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remotePlayItemInPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)remoteInsertIntoPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (long long)findIndexOfCommand:(unsigned int)arg1 inArray:(struct __CFArray *)arg2;
- (struct __CFArray *)copySupportedCommands;
- (void)dealloc;
- (id)initWithPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

