//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/_NSQuickActionProviderObserver-Protocol.h>
#import <AppKit/_NSQuickActionTouchBarPickerDelegate-Protocol.h>

@class NSDictionary, NSOperationQueue, NSSet, NSString, NSWorkflowsBar, _NSQuickActionProvider, _NSQuickActionTouchBarPicker;
@protocol _NSQuickActionTouchBarControllerDelegate;

__attribute__((visibility("hidden")))
@interface _NSQuickActionTouchBarController : NSObject <_NSQuickActionTouchBarPickerDelegate, _NSQuickActionProviderObserver>
{
    id <_NSQuickActionTouchBarControllerDelegate> _delegate;
    NSWorkflowsBar *_workflowsBar;
    _NSQuickActionTouchBarPicker *_mainPicker;
    _NSQuickActionTouchBarPicker *_popoverPicker;
    _NSQuickActionProvider *_provider;
    NSDictionary *_dataSourcesByQuickActionIdentifier;
    NSSet *_enabledQuickActionIdentifiers;
    NSOperationQueue *_backgroundLoadingQueue;
    BOOL _isObservingWorkflowsBar;
}

+ (id)keyPathsForValuesAffectingTouchBarIsShowing;
+ (BOOL)automaticallyNotifiesObserversOf_workflowsBar;
+ (BOOL)automaticallyNotifiesObserversOf_popoverPicker;
+ (BOOL)automaticallyNotifiesObserversOfTouchBarIsShowing;
+ (BOOL)accessInstanceVariablesDirectly;
- (void).cxx_destruct;
- (void)dismissPopover;
- (void)cancelQuickActionTouchBarPicker:(id)arg1;
- (void)quickActionTouchBarPicker:(id)arg1 invokeQuickActionForItemDataSource:(id)arg2;
- (void)showPopover;
@property(readonly) BOOL touchBarIsShowing;
- (void)enableQuickActionsWithIdentifiers:(id)arg1;
- (void)quickActionsDidChange;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)_workflowsBar;
- (id)_popoverPicker;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

