//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ICRDThumbnailGenerator.h"

@class NSObject;
@protocol OS_dispatch_queue;

@interface ICRDThumbnailGeneratorNote : ICRDThumbnailGenerator
{
    NSObject<OS_dispatch_queue> *_completionQueue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
- (id)generateThumbnailImageWithNote:(id)arg1 configuration:(id)arg2;
- (void)generateThumbnailWithConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithManagedObjectContext:(id)arg1;

@end

