//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <SearchFoundation/NSSecureCoding-Protocol.h>
#import <SearchFoundation/_SFPBImage-Protocol.h>

@class NSData, NSString, _SFPBAppIconImage, _SFPBContactImage, _SFPBGraphicalFloat, _SFPBLocalImage, _SFPBMonogramImage, _SFPBPointSize, _SFPBURLImage;

@interface _SFPBImage : PBCodable <_SFPBImage, NSSecureCoding>
{
    struct {
        unsigned int isTemplate:1;
        unsigned int shouldCropToCircle:1;
        unsigned int source:1;
        unsigned int type:1;
    } _has;
    BOOL _isTemplate;
    BOOL _shouldCropToCircle;
    int _source;
    int _type;
    NSData *_imageData;
    _SFPBGraphicalFloat *_cornerRadius;
    _SFPBGraphicalFloat *_scale;
    _SFPBPointSize *_size;
    NSString *_contentType;
    NSString *_keyColor;
    NSString *_identifier;
    _SFPBURLImage *_urlImage;
    _SFPBContactImage *_contactImage;
    _SFPBMonogramImage *_monogramImage;
    _SFPBLocalImage *_localImage;
    _SFPBAppIconImage *_appIconImage;
}

@property(retain, nonatomic) _SFPBAppIconImage *appIconImage; // @synthesize appIconImage=_appIconImage;
@property(retain, nonatomic) _SFPBLocalImage *localImage; // @synthesize localImage=_localImage;
@property(retain, nonatomic) _SFPBMonogramImage *monogramImage; // @synthesize monogramImage=_monogramImage;
@property(retain, nonatomic) _SFPBContactImage *contactImage; // @synthesize contactImage=_contactImage;
@property(retain, nonatomic) _SFPBURLImage *urlImage; // @synthesize urlImage=_urlImage;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) int source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *keyColor; // @synthesize keyColor=_keyColor;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(retain, nonatomic) _SFPBPointSize *size; // @synthesize size=_size;
@property(retain, nonatomic) _SFPBGraphicalFloat *scale; // @synthesize scale=_scale;
@property(retain, nonatomic) _SFPBGraphicalFloat *cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) BOOL shouldCropToCircle; // @synthesize shouldCropToCircle=_shouldCropToCircle;
@property(nonatomic) BOOL isTemplate; // @synthesize isTemplate=_isTemplate;
@property(copy) NSData *imageData; // @synthesize imageData=_imageData;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
@property(readonly, nonatomic) NSData *jsonData;
- (id)dictionaryRepresentation;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
@property(readonly, nonatomic) BOOL hasAppIconImage;
@property(readonly, nonatomic) BOOL hasLocalImage;
@property(readonly, nonatomic) BOOL hasMonogramImage;
@property(readonly, nonatomic) BOOL hasContactImage;
@property(readonly, nonatomic) BOOL hasUrlImage;
@property(readonly, nonatomic) BOOL hasType;
@property(readonly, nonatomic) BOOL hasSource;
@property(readonly, nonatomic) BOOL hasIdentifier;
@property(readonly, nonatomic) BOOL hasKeyColor;
@property(readonly, nonatomic) BOOL hasContentType;
@property(readonly, nonatomic) BOOL hasSize;
@property(readonly, nonatomic) BOOL hasScale;
@property(readonly, nonatomic) BOOL hasCornerRadius;
@property(readonly, nonatomic) BOOL hasShouldCropToCircle;
@property(readonly, nonatomic) BOOL hasIsTemplate;
@property(readonly, nonatomic) BOOL hasImageData;
- (id)initWithFacade:(id)arg1;
- (id)initWithSFImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

