//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSDictionary;

@interface AppTabButton : NSButton
{
    NSDictionary *attOff;
    NSDictionary *attOn;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGPath *)newTopPathForRoundedRect:(struct CGRect)arg1 radius:(double)arg2;
- (void)initUIValues;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

