//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICSLoggingDelegate.h"

@interface DAiCalendarLogger : NSObject <ICSLoggingDelegate>
{
}

+ (id)sharedLogger;
- (void)logICSMessage:(id)arg1 atLevel:(long long)arg2;
- (void)registerWithiCalendar;

@end

