//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSDocument.h>

#import "DragDropDelegate-Protocol.h"
#import "NSSplitViewDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class DataInspectorRepresenter, HFBinaryTemplateRepresenter, HFController, HFDocumentOperationView, HFHexTextRepresenter, HFLayoutRepresenter, HFLineCountingRepresenter, HFRepresenter, HFStatusBarRepresenter, NSDate, NSFont, NSResponder, NSSplitView, NSString, NSTimer, NSView;

__attribute__((visibility("hidden")))
@interface BaseDataDocument : NSDocument <NSWindowDelegate, DragDropDelegate, NSSplitViewDelegate>
{
    NSSplitView *containerView;
    HFController *controller;
    HFLineCountingRepresenter *lineCountingRepresenter;
    HFHexTextRepresenter *hexRepresenter;
    HFRepresenter *asciiRepresenter;
    HFRepresenter *scrollRepresenter;
    HFRepresenter *textDividerRepresenter;
    HFLayoutRepresenter *layoutRepresenter;
    DataInspectorRepresenter *dataInspectorRepresenter;
    HFStatusBarRepresenter *statusBarRepresenter;
    HFBinaryTemplateRepresenter *binaryTemplateRepresenter;
    NSResponder *savedFirstResponder;
    HFDocumentOperationView *operationView;
    HFDocumentOperationView *findReplaceView;
    HFDocumentOperationView *moveSelectionByView;
    HFDocumentOperationView *jumpToOffsetView;
    HFDocumentOperationView *saveView;
    NSTimer *showSaveViewAfterDelayTimer;
    BOOL bannerIsShown;
    BOOL bannerGrowing;
    BOOL willRemoveBannerIfSufficientlyShortAfterDrag;
    NSView *bannerView;
    NSTimer *bannerResizeTimer;
    double bannerTargetHeight;
    double bannerStartTime;
    id targetFirstResponderInBanner;
    CDUnknownBlockType commandToRunAfterBannerIsDoneHiding;
    CDUnknownBlockType commandToRunAfterBannerPrepared;
    BOOL saveInProgress;
    BOOL currentlySettingFont;
    BOOL isTransient;
    BOOL shouldLiveReload;
    NSDate *liveReloadDate;
    NSTimer *liveReloadTimer;
    unsigned long long cleanGenerationCount;
    BOOL loadingWindow;
}

+ (void)prepareForChangeInFileByBreakingFileDependencies:(id)arg1;
+ (void)didEndBreakFileDependencySheet:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
+ (id)byteArrayfromURL:(id)arg1 error:(id *)arg2;
+ (void)initialize;
+ (void)registerDefaultDefaults;
+ (id)layoutUserDefaultIdentifier;
+ (id)userDefKeyForRepresenterWithName:(const char *)arg1;
- (void).cxx_destruct;
- (void)setLiveReloadFromMenuItem:(id)arg1;
@property(nonatomic) BOOL shouldLiveReload;
- (BOOL)requiresOverwriteMode;
- (BOOL)isTransientAndCanBeReplaced;
- (void)updateChangeCount:(unsigned long long)arg1;
@property(nonatomic, getter=isTransient) BOOL transient;
- (void)deleteBookmark:(id)arg1;
- (void)setBookmark:(id)arg1;
- (BOOL)canSetBookmark;
- (void)selectBookmark:(id)arg1;
- (void)scrollToBookmark:(id)arg1;
- (void)jumpToBookmarkIndex:(long long)arg1 selecting:(BOOL)arg2;
- (void)saveLineNumberFormat;
- (void)setLineNumberFormat:(id)arg1;
- (void)setReadOnlyMode:(id)arg1;
- (void)setInsertMode:(id)arg1;
- (void)setOverwriteMode:(id)arg1;
- (void)modifyByteGrouping:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)showFontPanel:(id)arg1;
- (id)copyBookmarksMenuItems;
- (void)moveSelectionByAction:(id)arg1;
- (void)moveSelectionToAction:(id)arg1;
- (BOOL)movingRanges:(id)arg1 byAmount:(unsigned long long)arg2 isNegative:(BOOL)arg3 isValidForLength:(unsigned long long)arg4;
- (void)jumpToOffset:(id)arg1;
- (void)extendSelectionForwards:(id)arg1;
- (void)moveSelectionForwards:(id)arg1;
- (void)showNavigationBannerSettingExtendSelectionCheckboxTo:(BOOL)arg1;
- (void)performFindReplaceActionFromSelectedSegment:(id)arg1;
- (void)performHFFindPanelAction:(id)arg1;
- (void)replaceAll:(id)arg1;
- (void)replaceAndFind:(id)arg1;
- (void)replace:(id)arg1;
- (void)findPrevious:(id)arg1;
- (void)findNext:(id)arg1;
- (id)threadedReplaceBytes:(id)arg1 inBytes:(id)arg2 withBytes:(id)arg3 trackingProgress:(id)arg4;
- (void)findNextBySearchingForwards:(BOOL)arg1;
- (void)findEnded:(id)arg1;
- (id)threadedFindBytes:(id)arg1 inBytes:(id)arg2 inRange1:(CDStruct_91ee6ea3)arg3 range2:(CDStruct_91ee6ea3)arg4 forwards:(BOOL)arg5 trackingProgress:(id)arg6;
- (id)threadedSaveToURL:(id)arg1 trackingProgress:(id)arg2 error:(id *)arg3;
- (void)cancelOperation:(id)arg1;
- (void)splitViewDidResizeSubviews:(id)arg1;
- (void)removeBannerIfSufficientlyShort:(id)arg1;
- (struct CGRect)splitView:(id)arg1 effectiveRect:(struct CGRect)arg2 forDrawnRect:(struct CGRect)arg3 ofDividerAtIndex:(long long)arg4;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (void)showFindPanel:(id)arg1;
- (void)saveDocumentTo:(id)arg1;
- (void)saveDocumentAs:(id)arg1;
- (void)saveDocument:(id)arg1;
- (BOOL)displayCurrentSaveOperation;
- (BOOL)writeSafelyToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 error:(id *)arg4;
- (void)showSaveBannerHavingDelayed:(id)arg1;
- (void)hideBannerImmediately;
- (void)hideBannerFirstThenDo:(CDUnknownBlockType)arg1;
- (BOOL)canSwitchToNewBanner;
- (void)animateBanner:(id)arg1;
- (void)saveFirstResponderIfNotInBannerAndThenSetItTo:(id)arg1;
- (void)restoreFirstResponderToSavedResponder;
- (void)finishedAnimation;
- (BOOL)validateMenuItem:(id)arg1;
- (long long)selectedBookmark;
- (void)setColorBytesFromMenuItem:(id)arg1;
- (void)setShowNullBytesFromMenuItem:(id)arg1;
- (void)setShowCalloutsFromMenuItem:(id)arg1;
- (void)setAntialiasFromMenuItem:(id)arg1;
- (void)setStringEncodingFromMenuItem:(id)arg1;
@property(nonatomic) unsigned long long stringEncoding;
- (void)decreaseFontSize:(id)arg1;
- (void)increaseFontSize:(id)arg1;
- (void)setFontSizeFromMenuItem:(id)arg1;
@property(copy, nonatomic) NSFont *font;
- (void)setFont:(id)arg1 registeringUndo:(BOOL)arg2;
- (void)toggleVisibleControllerView:(id)arg1;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)performDragOperation:(id)arg1;
- (void)prepareBannerWithView:(id)arg1 withTargetFirstResponder:(id)arg2;
- (id)newOperationViewForNibName:(id)arg1 displayName:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)init;
- (void)dataInspectorChangedRowCount:(id)arg1;
- (void)dataInspectorDeletedAllRows:(id)arg1;
- (void)lineCountingRepCycledLineNumberFormat:(id)arg1;
- (void)lineCountingViewChangedWidth:(id)arg1;
- (void)adoptWindowController:(id)arg1 fromTransientDocument:(id)arg2;
- (void)windowControllerDidLoadNib:(id)arg1;
- (void)setupWindowEnforcingBytesPerLine:(unsigned long long)arg1;
- (void)setContainerView:(id)arg1;
- (void)relayoutAndResizeWindowForBytesPerLine:(unsigned long long)arg1;
- (void)relayoutAndResizeWindowPreservingFrame;
- (void)saveWindowState;
- (void)windowDidMove:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (struct CGSize)minimumWindowFrameSizeForProposedSize:(struct CGSize)arg1;
- (double)minimumWindowFrameWidthForBytesPerLine:(unsigned long long)arg1;
- (void)makeWindowControllers;
- (void)updateDocumentWindowTitle;
- (id)documentWindowTitleFormatString;
- (id)runningOperationViews;
- (void)applyDefaultRepresentersToDisplay;
- (void)saveDefaultRepresentersToDisplay;
- (void)saveOrApplyDefaultRepresentersToDisplay:(BOOL)arg1;
- (void)showOrHideDividerRepresenter;
- (BOOL)dividerRepresenterShouldBeShown;
- (void)hideViewForRepresenter:(id)arg1;
- (void)showViewForRepresenter:(id)arg1;
- (BOOL)representerIsShown:(id)arg1;
- (id)byteArray;
- (id)representers;
- (id)window;
- (id)windowNibName;
- (BOOL)prepareSavePanel:(id)arg1;
- (BOOL)tryLiveReload;
- (void)pollLiveReload;
- (void)presentedItemDidChange;
- (void)_tweakByteArray:(id)arg1;
- (void)_randomByteArray:(id)arg1;
- (void)_showByteArray:(id)arg1;
- (void)installDebuggingMenuItems:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

