//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <HomeKit/HMRoom.h>

#import <Home/HFWallaperHost-Protocol.h>

@class UIImage;

@interface HMRoom (HFWallpaperHostAdoption) <HFWallaperHost>
- (id)hf_updateWallpaperImage:(id)arg1;
@property(readonly, nonatomic) UIImage *hf_wallpaperImage;
@end

