//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HMAccessoryBrowserDelegate.h"

@class HMAccessory, HMAccessoryBrowser;

@protocol HMAccessoryBrowserPrivateDelegate <HMAccessoryBrowserDelegate>

@optional
- (void)accessoryBrowser:(HMAccessoryBrowser *)arg1 didUpdateNewAccessory:(HMAccessory *)arg2;
@end

