//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class TSDLayout;
@protocol TSDInfo;

@protocol TPAttachmentLayoutParent
- (void)addAttachmentLayout:(TSDLayout *)arg1;
- (TSDLayout *)existingAttachmentLayoutForInfo:(id <TSDInfo>)arg1;
@end

