//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s12NowPlayingUI0aB13TabControllerCN.h"

@interface _TtC8Podcasts28PodcastsFlowTabBarController : _$s12NowPlayingUI0aB13TabControllerCN
{
    // Error parsing type: , name: flowController
    // Error parsing type: , name: actionRunner
    // Error parsing type: , name: presenter
    // Error parsing type: , name: overlayView
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;

@end

