//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOAddress, GEOPDIndexQueryNode, GEOPDRecentRouteInfo, GEOPDViewportInfo, NSMutableArray, NSString, PBDataReader, PBUnknownFields;

__attribute__((visibility("hidden")))
@interface GEOPDSiriSearchParameters : PBCodable <NSCopying>
{
    PBDataReader *_reader;
    CDStruct_158f0f88 _readerMark;
    PBUnknownFields *_unknownFields;
    GEOAddress *_address;
    NSMutableArray *_businessCategoryFilters;
    GEOPDIndexQueryNode *_indexFilter;
    GEOPDRecentRouteInfo *_recentRouteInfo;
    NSString *_searchString;
    NSMutableArray *_searchSubstringDescriptors;
    GEOPDViewportInfo *_viewportInfo;
    unsigned int _maxResultCount;
    int _sortOrder;
    BOOL _isStrictMapRegion;
    BOOL _structuredSearch;
    struct {
        unsigned int has_maxResultCount:1;
        unsigned int has_sortOrder:1;
        unsigned int has_isStrictMapRegion:1;
        unsigned int has_structuredSearch:1;
        unsigned int read_unknownFields:1;
        unsigned int read_address:1;
        unsigned int read_businessCategoryFilters:1;
        unsigned int read_indexFilter:1;
        unsigned int read_recentRouteInfo:1;
        unsigned int read_searchString:1;
        unsigned int read_searchSubstringDescriptors:1;
        unsigned int read_viewportInfo:1;
        unsigned int wrote_unknownFields:1;
        unsigned int wrote_address:1;
        unsigned int wrote_businessCategoryFilters:1;
        unsigned int wrote_indexFilter:1;
        unsigned int wrote_recentRouteInfo:1;
        unsigned int wrote_searchString:1;
        unsigned int wrote_searchSubstringDescriptors:1;
        unsigned int wrote_viewportInfo:1;
        unsigned int wrote_maxResultCount:1;
        unsigned int wrote_sortOrder:1;
        unsigned int wrote_isStrictMapRegion:1;
        unsigned int wrote_structuredSearch:1;
    } _flags;
}

+ (BOOL)isValid:(id)arg1;
+ (Class)searchSubstringDescriptorType;
+ (Class)businessCategoryFilterType;
- (void).cxx_destruct;
- (void)clearUnknownFields:(BOOL)arg1;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)readAll:(BOOL)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(retain, nonatomic) GEOPDRecentRouteInfo *recentRouteInfo;
@property(readonly, nonatomic) BOOL hasRecentRouteInfo;
- (void)_readRecentRouteInfo;
@property(retain, nonatomic) GEOPDIndexQueryNode *indexFilter;
@property(readonly, nonatomic) BOOL hasIndexFilter;
- (void)_readIndexFilter;
- (id)searchSubstringDescriptorAtIndex:(unsigned long long)arg1;
- (unsigned long long)searchSubstringDescriptorsCount;
- (void)_addNoFlagsSearchSubstringDescriptor:(id)arg1;
- (void)addSearchSubstringDescriptor:(id)arg1;
- (void)clearSearchSubstringDescriptors;
@property(retain, nonatomic) NSMutableArray *searchSubstringDescriptors;
- (void)_readSearchSubstringDescriptors;
@property(nonatomic) BOOL hasStructuredSearch;
@property(nonatomic) BOOL structuredSearch;
@property(nonatomic) BOOL hasIsStrictMapRegion;
@property(nonatomic) BOOL isStrictMapRegion;
- (id)businessCategoryFilterAtIndex:(unsigned long long)arg1;
- (unsigned long long)businessCategoryFiltersCount;
- (void)_addNoFlagsBusinessCategoryFilter:(id)arg1;
- (void)addBusinessCategoryFilter:(id)arg1;
- (void)clearBusinessCategoryFilters;
@property(retain, nonatomic) NSMutableArray *businessCategoryFilters;
- (void)_readBusinessCategoryFilters;
@property(retain, nonatomic) GEOAddress *address;
@property(readonly, nonatomic) BOOL hasAddress;
- (void)_readAddress;
@property(retain, nonatomic) GEOPDViewportInfo *viewportInfo;
@property(readonly, nonatomic) BOOL hasViewportInfo;
- (void)_readViewportInfo;
@property(retain, nonatomic) NSString *searchString;
@property(readonly, nonatomic) BOOL hasSearchString;
- (void)_readSearchString;
@property(nonatomic) BOOL hasMaxResultCount;
@property(nonatomic) unsigned int maxResultCount;
- (int)StringAsSortOrder:(id)arg1;
- (id)sortOrderAsString:(int)arg1;
@property(nonatomic) BOOL hasSortOrder;
@property(nonatomic) int sortOrder;

@end

