//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CXCallObserver, NSObject<OS_dispatch_queue>;

@interface CXCallController : NSObject
{
    CXCallObserver *_callObserver;
    NSObject<OS_dispatch_queue> *_completionQueue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
@property(retain, nonatomic) CXCallObserver *callObserver; // @synthesize callObserver=_callObserver;
- (void)_requestTransaction:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestTransactionWithAction:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestTransactionWithActions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestTransaction:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithQueue:(id)arg1;
- (id)init;

@end

