//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLgGenwSplitPartView.h"

@class CLgUnilibInspectorView;

@interface CLgGenwSplitPartView_inspector : CLgGenwSplitPartView
{
    CLgUnilibInspectorView *unilibInspectorView;
}

- (id)unilibInspectorView;
- (void)dealloc;
- (id)initPartWithFrame_inspector:(struct CGRect)arg1 genwLayoutCreator:(id)arg2 splitPartIndex:(int)arg3 unilibDocManager:(id)arg4;

@end

