//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <HomeKitDaemon/NSObject-Protocol.h>

@class HMBLocalZone, HMBProcessingModelCreation, HMBProcessingModelDeletion, HMBProcessingModelUpdate, NAFuture;

@protocol HMBLocalZoneModelObserver <NSObject>
- (NAFuture *)localZone:(HMBLocalZone *)arg1 didProcessModelDeletion:(HMBProcessingModelDeletion *)arg2;
- (NAFuture *)localZone:(HMBLocalZone *)arg1 didProcessModelUpdate:(HMBProcessingModelUpdate *)arg2;
- (NAFuture *)localZone:(HMBLocalZone *)arg1 didProcessModelCreation:(HMBProcessingModelCreation *)arg2;
@end

