//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

__attribute__((visibility("hidden")))
@interface _PFResultObjectKeyEnumerator : NSEnumerator
{
    id _target;
    const id *_keys;
    unsigned long long *_referenceItems;
    struct _NSRange _range;
    unsigned long long _index;
}

- (id)nextObject;
- (void)dealloc;
- (void)_invalidate;
- (id)initWithArray:(const id *)arg1 forTarget:(id)arg2 withReferenceValues:(unsigned long long *)arg3 andRange:(struct _NSRange)arg4;

@end

