//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSObject;
@protocol KNAnimationSceneNodeMetalRenderer, KNAnimationSceneTransitionMetalRenderer, _TtP7Keynote40KNAnimationSceneMetalRendererAssetLoader_;

@protocol _TtP7Keynote39KNAnimationSceneMetalSubrendererFactory_ <NSObject>
- (id <_TtP7Keynote40KNAnimationSceneMetalRendererAssetLoader_>)newAssetLoaderFor:(NSArray *)arg1;
- (id <KNAnimationSceneTransitionMetalRenderer>)newTransitionSubrendererForSceneContentDescription:(NSObject *)arg1 effectContentDescription:(NSObject *)arg2;
- (id <KNAnimationSceneNodeMetalRenderer>)newNodeSubrendererForSceneContentDescription:(NSObject *)arg1 nodeContentDescription:(NSObject *)arg2 effectContentDescription:(NSObject *)arg3;
@end

