//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CHITHostState.h"

@class ECColumnWidthConvertor, ECFormulaProcessor, EDResources, EDStyle, EDWorkbook, EITSheetHyperlinks, NSMutableDictionary;
@protocol TCCancelDelegate;

@interface EITBaseState : CHITHostState
{
    EDWorkbook *mEDWorkbook;
    EDResources *mEDResources;
    ECColumnWidthConvertor *mColumnWidthConvertor;
    int mLassoDefaultColumnCount;
    int mLassoDefaultRowCount;
    id <TCCancelDelegate> mCancelDelegate;
    NSMutableDictionary *mSheetNameToSheetMap;
    EITSheetHyperlinks *_sheetHyperlinks;
}

- (void).cxx_destruct;
@property(retain, nonatomic) EITSheetHyperlinks *sheetHyperlinks; // @synthesize sheetHyperlinks=_sheetHyperlinks;
@property(readonly, nonatomic) id <TCCancelDelegate> cancelDelegate; // @synthesize cancelDelegate=mCancelDelegate;
@property(nonatomic) int lassoDefaultRowCount; // @synthesize lassoDefaultRowCount=mLassoDefaultRowCount;
@property(nonatomic) int lassoDefaultColumnCount; // @synthesize lassoDefaultColumnCount=mLassoDefaultColumnCount;
@property(readonly, nonatomic) NSMutableDictionary *sheetNameToSheetMap; // @synthesize sheetNameToSheetMap=mSheetNameToSheetMap;
@property(readonly, nonatomic) EDResources *edResources; // @synthesize edResources=mEDResources;
@property(readonly, nonatomic) EDWorkbook *edWorkbook; // @synthesize edWorkbook=mEDWorkbook;
@property(readonly, nonatomic) BOOL isCancelled;
- (_Bool)displayGridlinesForSheet:(id)arg1;
@property(readonly, nonatomic) ECColumnWidthConvertor *columnWidthConvertor;
@property(readonly, nonatomic) ECFormulaProcessor *formulaProcessor;
@property(readonly, nonatomic) EDStyle *edDefaultStyle;
- (id)initWithWorkbook:(id)arg1 cancel:(id)arg2;

@end

