//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSView (BlockAnimation)
+ (void)ic_animateWithDuration:(double)arg1 animations:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)ic_animateWithDuration:(double)arg1 animations:(CDUnknownBlockType)arg2;
+ (void)ic_performWithoutAnimation:(CDUnknownBlockType)arg1;
- (id)ic_animator;
- (void)ic_insertSubview:(struct NSView *)arg1 belowSubview:(struct NSView *)arg2;
- (void)ic_setAlpha:(double)arg1;
- (void)ic_setNeedsLayout;
- (void)ic_setNeedsDisplay;
- (double)ic_backingScaleFactor;
@end

