//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GSSPMessageBase.h"

#import "GSSPAutoDecodable-Protocol.h"

@class NSString;

@interface GSSPLargeArray : GSSPMessageBase <GSSPAutoDecodable>
{
    NSString *mMaxSegmentElementCount;
    NSString *mMaxSegmentSize;
    BOOL mShouldDelayArchiving;
    int mDelayedArchivingPriority;
    BOOL mStoreOutsideObjectArchive;
    BOOL mDefinedMaxSegmentElementCount;
    BOOL mDefinedMaxSegmentSize;
    BOOL mDefinedShouldDelayArchiving;
    BOOL mDefinedDelayedArchivingPriority;
    BOOL mDefinedStoreOutsideObjectArchive;
}

+ (Class)realClass;
+ (void)registerRealGsspClass:(Class)arg1;
+ (CDUnknownFunctionPointerType)defaultDecodeConversionFunc;
+ (CDUnknownFunctionPointerType)autoDecodeConversionFunc;
+ (void)setAutoDecodeConversionFuncForDocServer:(CDUnknownFunctionPointerType)arg1;
+ (Class)autoDecodedClass;
@property(readonly, nonatomic) BOOL definedStoreOutsideObjectArchive; // @synthesize definedStoreOutsideObjectArchive=mDefinedStoreOutsideObjectArchive;
@property(readonly, nonatomic) BOOL definedDelayedArchivingPriority; // @synthesize definedDelayedArchivingPriority=mDefinedDelayedArchivingPriority;
@property(readonly, nonatomic) BOOL definedShouldDelayArchiving; // @synthesize definedShouldDelayArchiving=mDefinedShouldDelayArchiving;
@property(readonly, nonatomic) BOOL definedMaxSegmentSize; // @synthesize definedMaxSegmentSize=mDefinedMaxSegmentSize;
@property(readonly, nonatomic) BOOL definedMaxSegmentElementCount; // @synthesize definedMaxSegmentElementCount=mDefinedMaxSegmentElementCount;
- (void).cxx_destruct;
- (id)description;
- (id)dspClassName;
- (id)jsonNSDictionaryValue;
- (void)populateJsonNSDictionaryValueToDictionary:(id)arg1;
- (int)p_getDiffEncodingScoreWith:(id)arg1;
- (void)p_populateStructHashKey:(struct GSSPHashKeyBuilder *)arg1;
- (unsigned long long)p_getStructHashKeyLength;
- (int)getStructHashId;
- (void)serializeRequiredFieldsWithSerializationContext:(struct GSSPSerializationContext *)arg1 withNextFieldNeedSerialize:(BOOL)arg2 diffBy:(id)arg3;
- (void)serializeOptionalFieldsWithSerializationContext:(struct GSSPSerializationContext *)arg1 withNextFieldNeedSerialize:(BOOL)arg2 diffBy:(id)arg3;
- (id)dspTypeIdString;
- (void)populateRequiredField:(int)arg1 fromContext:(struct GSSPDeserializationContext *)arg2;
- (void)populateOptionalField:(int)arg1 fromContext:(struct GSSPDeserializationContext *)arg2;
- (void)shallowCopyAllFieldsFrom:(id)arg1;
- (BOOL)clearStoreOutsideObjectArchive;
- (BOOL)clearDelayedArchivingPriority;
- (BOOL)clearShouldDelayArchiving;
- (BOOL)clearMaxSegmentSize;
- (BOOL)clearMaxSegmentElementCount;
- (void)setStoreOutsideObjectArchive:(BOOL)arg1;
- (BOOL)storeOutsideObjectArchive;
- (void)setDelayedArchivingPriority:(int)arg1;
- (int)delayedArchivingPriority;
- (void)setShouldDelayArchiving:(BOOL)arg1;
- (BOOL)shouldDelayArchiving;
- (void)setMaxSegmentSize:(id)arg1;
- (id)maxSegmentSize;
- (void)setMaxSegmentElementCount:(id)arg1;
- (id)maxSegmentElementCount;

@end

