//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Mail/MFEWSLocalMessageAction.h>

@class NSDictionary;

@interface MFEWSCopyMessageAction : MFEWSLocalMessageAction
{
    NSDictionary *_destinationMessagesBySourceItemIDs;
    NSDictionary *_destinationMessagesBySourceMessages;
    NSDictionary *_destinationItemIDsByMessage;
}

@property(copy, nonatomic) NSDictionary *destinationItemIDsByMessage; // @synthesize destinationItemIDsByMessage=_destinationItemIDsByMessage;
@property(copy, nonatomic) NSDictionary *destinationMessagesBySourceMessages; // @synthesize destinationMessagesBySourceMessages=_destinationMessagesBySourceMessages;
@property(copy, nonatomic) NSDictionary *destinationMessagesBySourceItemIDs; // @synthesize destinationMessagesBySourceItemIDs=_destinationMessagesBySourceItemIDs;
- (void).cxx_destruct;
- (id)newSyncOperation;
- (id)initWithMessageActionID:(long long)arg1 activityType:(id)arg2 mailbox:(id)arg3 userInitiated:(BOOL)arg4;
- (id)initWithMessageActionID:(long long)arg1 activityType:(id)arg2 mailbox:(id)arg3 userInitiated:(BOOL)arg4 destinationMessagesBySourceItemIDs:(id)arg5 destinationMessagesBySourceMessages:(id)arg6;

@end

