//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FAFamilyCircleRequestConnectionProvider.h"

@class NSLock, NSString, NSXPCConnection;

@interface _FAFamilyCircleRequestConnectionProvider : NSObject <FAFamilyCircleRequestConnectionProvider>
{
    id <FAFamilyCircleRequestConnectionFactory> _factory;
    NSXPCConnection *_connection;
    NSLock *_lock;
}

+ (id)createResumedConnectionWithFactory:(id)arg1 provider:(id)arg2;
+ (id)sharedInstance;
@property(readonly, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) id <FAFamilyCircleRequestConnectionFactory> factory; // @synthesize factory=_factory;
- (void).cxx_destruct;
- (id)serviceConnection;
- (void)connectionWasInvalidated:(id)arg1;
- (void)connectionWasInterrupted:(id)arg1;
- (void)dealloc;
- (id)initWithConnectionFactory:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

