//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSTextField;

__attribute__((visibility("hidden")))
@interface FMFTitleViewMac : NSView
{
    NSTextField *_titleLabel;
    NSTextField *_subtitleLabel;
}

@property(retain, nonatomic) NSTextField *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)_updateLabels:(id)arg1;
- (void)updateLocation:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

