//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "KNBaseCanvasEditorHelper.h"

@interface KNCanvasEditorHelper : KNBaseCanvasEditorHelper
{
}

- (int)canvasEditorCanPerformLockAction:(SEL)arg1 withSender:(id)arg2;
- (id)infosForAdjustingConnectionLinesAfterRemove:(id)arg1;
- (void)replaceDrawable:(id)arg1 withDrawable:(id)arg2;
- (BOOL)insertInfosFromDragAndDrop:(id)arg1 atPoint:(struct CGPoint)arg2 preferredCenterRequired:(BOOL)arg3 onRep:(id)arg4;
- (void)addContextualMenuItemsToMenu:(id)arg1 clickAtPoint:(struct CGPoint)arg2 withEvent:(id)arg3;
- (id)shapeInfoToBeginEditing;
- (id)emptyCanvasSelectionForSlideNode:(id)arg1;
- (id)p_actionBuildChunksToSelectForDrawable:(id)arg1;
- (id)buildChunksToSelectForInfos:(id)arg1 limitingToAnimationType:(long long)arg2;
- (id)p_buildChunksToSelectForInfos:(id)arg1 limitToFirstChunk:(BOOL)arg2 limitToAnimationType:(long long)arg3;
- (id)p_infosForSelectingForBuildChunks:(id)arg1;
- (id)p_drawableWithExpandedSequenceInInfos:(id)arg1;
- (id)p_infosWithGhostsForCollapsedSequencesReplacedByOriginalDrawables:(id)arg1;
- (BOOL)p_originalDrawableIsSharedByGhostInfos:(id)arg1;
- (id)canvasSelectionForBuildChunks:(id)arg1;
- (id)selectionPathForBuildChunks:(id)arg1;
- (id)canvasSelectionWithInfos:(id)arg1 buildChunks:(id)arg2;
- (id)selectionPathWithInfos:(id)arg1 buildChunks:(id)arg2;
- (id)canvasSelectionWithInfos:(id)arg1;

@end

