//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface CFPDSourceLookUpKey : NSObject
{
    struct __CFString *domain;
    struct __CFString *userName;
    struct __CFString *containerPath;
    struct __CFString *cloudPath;
    BOOL byHost;
    BOOL managed;
    BOOL managedUsesContainer;
    BOOL cloud;
}

- (void)dealloc;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@end

