//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKTableViewCell.h>

@class NSLayoutConstraint, NSLayoutGuide, NSView, TransitDirectionsListItem;

__attribute__((visibility("hidden")))
@interface TransitDirectionsCell : MKTableViewCell
{
    TransitDirectionsListItem *_transitListItem;
    NSLayoutConstraint *_leadingAccessoryLayoutGuideWidthConstraint;
    NSLayoutConstraint *_bottomSpacingLayoutGuideHeightConstraint;
    NSLayoutGuide *_trailingContentLayoutGuide;
    NSLayoutConstraint *_trailingContentLayoutGuideWidthConstraint;
    NSLayoutConstraint *_trailingGuideToContentViewConstraint;
    NSView *_contentView;
    BOOL _lastChild;
    double _leadingInstructionMargin;
    long long _navigationState;
    NSLayoutGuide *_leadingAccessoryLayoutGuide;
    NSLayoutGuide *_contentLayoutGuide;
    NSLayoutGuide *_bottomSpacingLayoutGuide;
    NSView *_trailingView;
}

+ (id)keyPathsForValuesAffectingIsHighlighted;
+ (double)estimatedHeightForListItem:(id)arg1;
+ (id)cellIdentifier;
+ (id)cellForListItem:(id)arg1 withFrame:(struct CGRect)arg2;
+ (id)cellIdentifierForListItem:(id)arg1;
+ (Class)cellClassForListItem:(id)arg1;
+ (id)cellMapping;
@property(retain, nonatomic) NSView *trailingView; // @synthesize trailingView=_trailingView;
@property(readonly, nonatomic) NSLayoutGuide *bottomSpacingLayoutGuide; // @synthesize bottomSpacingLayoutGuide=_bottomSpacingLayoutGuide;
@property(readonly, nonatomic) NSLayoutGuide *contentLayoutGuide; // @synthesize contentLayoutGuide=_contentLayoutGuide;
@property(readonly, nonatomic) NSLayoutGuide *leadingAccessoryLayoutGuide; // @synthesize leadingAccessoryLayoutGuide=_leadingAccessoryLayoutGuide;
@property(nonatomic, getter=isLastChild) BOOL lastChild; // @synthesize lastChild=_lastChild;
@property(nonatomic) long long navigationState; // @synthesize navigationState=_navigationState;
@property(nonatomic) double leadingInstructionMargin; // @synthesize leadingInstructionMargin=_leadingInstructionMargin;
@property(readonly, nonatomic) TransitDirectionsListItem *transitListItem; // @synthesize transitListItem=_transitListItem;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) BOOL isHighlighted;
- (BOOL)isSelected;
@property(readonly, nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
- (double)_leadingSeparatorInset;
@property(readonly, nonatomic) double bottomSpacerHeight;
- (double)_trailingGuideToContentViewDistance;
- (void)updateConstraints;
- (id)_initialConstraints;
- (void)_updateForParentExpansionOrCollapse;
- (void)_createSubviews;
- (BOOL)isFlipped;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

