//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Automator/AMGroup.h>

@class NSString;

@interface AMWorkflowGroup : AMGroup
{
    NSString *_path;
}

+ (id)workflowGroupWithName:(id)arg1 smallIcon:(id)arg2 largeIcon:(id)arg3;
- (void)setPath:(id)arg1;
- (id)path;
- (void)dealloc;

@end

