//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <MAToolKit/MAKitView.h>

@class CLgListAreaTabView, MASegmentedControl;

@interface CLgListAreaTabButtons : MAKitView
{
    MASegmentedControl *segmentedControl;
    CLgListAreaTabView *listAreaTabView;
    BOOL mainViewIsFirstResponder;
}

- (void)dealloc;
- (BOOL)isOpaque;
- (void)unilibViewFirstResponderStateChanged3:(BOOL)arg1;
- (void)setImageIndex:(long long)arg1;
- (void)setListAreaTabView:(id)arg1;
- (void)segmentedControlAction:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1 forDictArray:(id)arg2;

@end

