//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ClassroomKit/NSCopying-Protocol.h>
#import <ClassroomKit/NSObject-Protocol.h>
#import <ClassroomKit/NSSecureCoding-Protocol.h>

@class CRKCloudRecord, NSDictionary, NSSet, NSString;
@protocol CRKCloudStoring;

@protocol CRKCloudStoring <NSObject, NSSecureCoding, NSCopying>
+ (id)skeletonInstance;
+ (NSString *)recordType;
+ (id)instanceWithRecord:(CRKCloudRecord *)arg1;
- (id)valueForKey:(NSString *)arg1;
- (NSString *)recordName;
- (BOOL)isChangedFrom:(id <CRKCloudStoring>)arg1;
- (void)applyFieldsToRecord:(CRKCloudRecord *)arg1;

@optional
- (NSSet *)requiredKeys;
- (NSDictionary *)subItemClassesByItemKey;
- (NSDictionary *)subItemClassesByItemSetKey;
@end

