//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPasteboard.h"

@class NSString;

@interface NSPasteboard (UXKit)
@property(copy, nonatomic, setter=ux_setSourceIdentifier:) NSString *ux_sourceIdentifier;
@end

