//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"
#import "NSSecureCoding.h"

@class AVCaptionInternal, NSString;

@interface AVCaption : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>
{
    AVCaptionInternal *_internal;
}

+ (void)_appendFigStyleKey:(const struct __CFString *)arg1 value:(const void *)arg2 range:(CDStruct_43f4b5b8)arg3 toArray:(id)arg4;
+ (BOOL)supportsSecureCoding;
+ (id)captionFromFigCaption:(const struct OpaqueFigCaption *)arg1;
- (id)_stylePropertiesForArchive;
- (void)_setStylePropertiesForArchive:(id)arg1;
- (void)_setRuby:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)_setTextCombine:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)_setDecoration:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)_setFontStyle:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)_setFontWeight:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)_setBackgroundColor:(struct CGColor *)arg1 inRange:(struct _NSRange)arg2;
- (void)_setTextColor:(struct CGColor *)arg1 inRange:(struct _NSRange)arg2;
- (void)_setTextAlignment:(long long)arg1;
- (void)_setAnimation:(long long)arg1;
- (void)_setRegion:(id)arg1;
- (void)_setTimeRange:(CDStruct_e83c9415)arg1;
- (void)_setText:(id)arg1;
- (id)description;
@property(readonly, nonatomic) const struct OpaqueFigCaptionData *_figCaptionData;
@property(readonly, nonatomic) CDStruct_e83c9415 timeRange;
- (id)region;
@property(readonly, nonatomic) NSString *text;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithText:(id)arg1 timeRange:(CDStruct_e83c9415)arg2;
- (id)initWithFigCaptionData:(const struct OpaqueFigCaptionData *)arg1 timeRange:(CDStruct_e83c9415)arg2;
- (id)initWithFigMutableCaptionData:(struct OpaqueFigCaptionData *)arg1 timeRange:(CDStruct_e83c9415)arg2;
- (id)init;
- (id)rubyTextAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (long long)textCombineAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (long long)decorationAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (long long)fontStyleAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (long long)fontWeightAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (struct CGColor *)copyBackgroundColorAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (struct CGColor *)copyTextColorAtIndex:(long long)arg1 range:(struct _NSRange *)arg2;
- (long long)textAlignment;
- (long long)animation;

@end

