//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CalendarUI/EKUISingleViewGadget.h>

@class CalUILabel, NSLayoutConstraint;

@interface EKUISubtitleGadget : EKUISingleViewGadget
{
    CalUILabel *_subtitleLabel;
    NSLayoutConstraint *_zeroHeightConstraint;
}

@property(retain) NSLayoutConstraint *zeroHeightConstraint; // @synthesize zeroHeightConstraint=_zeroHeightConstraint;
@property(retain) CalUILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (void).cxx_destruct;
- (BOOL)shouldDisplay;

@end

