//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CloudDocsDaemon/BRCItem-Protocol.h>

@class BRCAccountSession, BRCClientZone, BRCItemID, BRCServerZone, BRCStatInfo, BRCVersion, NSNumber, NSString;

@interface BRCServerItem : NSObject <BRCItem>
{
    BRCAccountSession *_session;
    BRCServerZone *_zone;
    unsigned long long _sharingOptions;
    BOOL _needsInsert;
    NSString *_symlinkTarget;
    NSNumber *_ownerKey;
    BRCItemID *_itemID;
    NSString *_originalName;
    long long _rank;
    BRCStatInfo *_st;
    BRCVersion *_latestVersion;
    BRCServerZone *_serverZone;
    BRCClientZone *_clientZone;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) NSString *symlinkTarget; // @synthesize symlinkTarget=_symlinkTarget;
@property(nonatomic) unsigned long long sharingOptions; // @synthesize sharingOptions=_sharingOptions;
@property(readonly, nonatomic) BRCAccountSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) BRCClientZone *clientZone; // @synthesize clientZone=_clientZone;
@property(readonly, nonatomic) BRCServerZone *serverZone; // @synthesize serverZone=_serverZone;
@property(readonly, nonatomic) BRCVersion *latestVersion; // @synthesize latestVersion=_latestVersion;
@property(readonly, nonatomic) BRCStatInfo *st; // @synthesize st=_st;
@property(readonly, nonatomic) long long rank; // @synthesize rank=_rank;
@property(readonly, nonatomic) NSString *originalName; // @synthesize originalName=_originalName;
@property(readonly, nonatomic) BRCItemID *itemID; // @synthesize itemID=_itemID;
@property(readonly, nonatomic) NSNumber *ownerKey; // @synthesize ownerKey=_ownerKey;
- (void).cxx_destruct;
- (unsigned int)_t_pcsChainState;
- (id)newLocalItemWithServerZone:(id)arg1 dbRowID:(unsigned long long)arg2;
- (id)appLibraryForRootItem;
- (id)description;
- (id)descriptionWithContext:(id)arg1;
- (unsigned long long)diffAgainstServerItem:(id)arg1;
- (BOOL)validateLoggingToFile:(struct __sFILE *)arg1;
- (id)initFromPQLResultSet:(id)arg1 serverZone:(id)arg2 error:(id *)arg3;
- (id)initFromPQLResultSet:(id)arg1 session:(id)arg2 error:(id *)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithServerItem:(id)arg1;
@property(readonly, nonatomic) BOOL isPackage;
@property(readonly, nonatomic) BOOL isFinderBookmark;
@property(readonly, nonatomic) BOOL isSymLink;
@property(readonly, nonatomic) BOOL isZoneRoot;
@property(readonly, nonatomic) BOOL isFSRoot;
@property(readonly, nonatomic) BOOL isDocument;
@property(readonly, nonatomic) BOOL isDirectory;
@property(readonly, nonatomic) BOOL isBRAlias;
@property(readonly, nonatomic) BOOL isDead;
@property(readonly, nonatomic) BOOL isLive;

@end

