//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CALayerDelegate.h"
#import "DDSTItemStatePartProtocol.h"
#import "IXClickableAreaDelegate.h"

@class CALayer, IXClickableArea, NSString, RunningStringPresenter;

@interface DDSTErrorMessagePart : NSObject <IXClickableAreaDelegate, CALayerDelegate, DDSTItemStatePartProtocol>
{
    id <DDSTItemStatePartContext> _context;
    CALayer *_layer;
    CALayer *_iconLayer;
    RunningStringPresenter *_runningTitle;
    RunningStringPresenter *_runningMessage;
    IXClickableArea *_titleHoverableArea;
    IXClickableArea *_messageHoverableArea;
    BOOL _hidden;
    NSString *_title;
    NSString *_message;
    struct CGRect _frame;
}

@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
- (void).cxx_destruct;
- (void)clickableAreaDidClick:(id)arg1;
- (void)clickableAreaDidHover:(id)arg1;
- (void)drawErrorIcon;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)disconnectFromIxHost:(id)arg1;
- (void)connectToIxHost:(id)arg1;
- (void)removeFromSuperlayer;
- (void)addToSuperlayer:(id)arg1;
- (void)dealloc;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

