//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface ITItemLayerPool : NSObject
{
    NSMutableArray *m_layerPool;
}

- (void)disposeLayerOfItemView:(id)arg1;
- (void)allocateLayerForItemView:(id)arg1;
- (void)recycleItemLayer:(id)arg1;
- (id)provideItemLayer;
- (void)dealloc;
- (id)init;

@end

