//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "TSDChangeSourceCommandPushingProxy.h"

#import "TSCHChartStyleOwnerProxy-Protocol.h"
#import "TSCHChartStyleOwnerProxyPropertyForwarding-Protocol.h"

@class NSMutableDictionary, NSString, TSCHChartAxis, TSCHChartDrawableInfo, TSCHChartEditor;

@interface TSCHChartAxisProxy : TSDChangeSourceCommandPushingProxy <TSCHChartStyleOwnerProxy, TSCHChartStyleOwnerProxyPropertyForwarding>
{
    TSCHChartEditor *mChartEditor;
    NSMutableDictionary *mPriorValues;
}

+ (id)p_dynamicChangeKeys;
+ (id)keyPathsForValuesAffectingP_chartDrawable;
+ (id)keyPathsForValuesAffectingP_chartAxis;
- (void).cxx_destruct;
- (id)keyPathsToInvalidateForChangeRecords:(id)arg1;
- (void)willSetValue:(id)arg1 forKeyPath:(id)arg2;
- (void)notifyChartRepsForChanges:(id)arg1;
- (id)newDynamicChangeStandInForKeyPath:(id)arg1;
- (void)p_cachePriorValue:(id)arg1 forKey:(id)arg2;
- (id)styleOwner;
- (id)chartDrawableInfo;
- (BOOL)enqueueCommandToChangeOldValue:(id)arg1 toNewValue:(id)arg2 forKeyPath:(id)arg3;
- (id)commandToChangeOldValue:(id)arg1 toNewValue:(id)arg2 forKeyPath:(id)arg3;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)targetDidChangeValuesForKeyPaths:(id)arg1;
- (void)p_getSampleValuesWithValue:(id *)arg1 string:(id *)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (id)p_adjustedNumberFormatType;
- (BOOL)validateValue:(id *)arg1 forKey:(id)arg2 error:(id *)arg3;
- (id)chartEditor;
@property(readonly, nonatomic) TSCHChartDrawableInfo *p_chartDrawable;
@property(readonly, nonatomic) TSCHChartAxis *p_chartAxis;
- (id)p_logValueForNumber:(id)arg1;
- (BOOL)p_hasLogScale;
- (id)forwardingPropertyForProperty:(id)arg1;
- (id)propertyForForwardingProperty:(id)arg1;
- (void)dealloc;
- (id)initWithChartEditor:(id)arg1 forAxis:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

