//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "ModernButtonCell.h"

@class NSColor;

@interface GlyphButtonCell : ModernButtonCell
{
    double _contentDiameter;
    double _strokeWidth;
    NSColor *_strokeColor;
}

@property(copy, nonatomic) NSColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(nonatomic) double strokeWidth; // @synthesize strokeWidth=_strokeWidth;
@property(nonatomic) double contentDiameter; // @synthesize contentDiameter=_contentDiameter;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)teardownObservations;
- (void)setupObservations;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawAlignmentGuidesWithFrame:(struct CGRect)arg1;
- (BOOL)showAlignmentRects;
- (struct CGSize)cellSize;
- (struct CGSize)intrinsicContentSize;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)updateContentDiameter;
- (void)setControlSize:(unsigned long long)arg1;
- (id)attributedTitle;
- (void)updateFontForBounds:(struct CGRect)arg1;
- (void)commonInit;

@end

