//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "TagPopoverDelegate-Protocol.h"

@class ClickableURLTextField, NSLayoutConstraint, NSString, NSTextField;

@interface TagsSectionViewController : NSViewController <TagPopoverDelegate>
{
    ClickableURLTextField *tagsDescriptionTextField;
    NSTextField *label;
    NSLayoutConstraint *widthConstraint;
    NSLayoutConstraint *heightConstraint;
    BOOL isObservingRepresentedObject;
}

- (void).cxx_destruct;
- (void)updateLayout;
- (void)handleTagsChange;
- (void)tagPopoverDidClose:(id)arg1;
- (void)handleAddTagURI:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

