//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WebsiteController : NSObject
{
    BOOL _allowRequests;
}

+ (id)webSSOHost;
+ (BOOL)runningCobrandedBuild;
+ (id)intSrcStringWithTopic:(id)arg1;
+ (id)sharedInstance;
@property BOOL allowRequests; // @synthesize allowRequests=_allowRequests;
- (unsigned long long)cobrandVersion;
- (void)skypeKitWillStop:(id)arg1;
- (void)showHelpGoLink:(id)arg1 intSrcTopic:(id)arg2;
- (void)openURL:(id)arg1;
- (id)websiteURLWithAction:(id)arg1;
- (id)getLongVersionString;
- (void)registerUpgraded;
- (void)registerInstalled;
- (BOOL)validateMenuItem:(id)arg1;
- (void)showTryBeforeYouBuyLink:(id)arg1;
- (void)showTermsOfServiceLink:(id)arg1;
- (void)showEulaLink:(id)arg1;
- (void)showHelpCallForwardingLink:(id)arg1;
- (void)showPartnerPageLink:(id)arg1;
- (void)showBuyCreditLink:(id)arg1;
- (void)showProblemsSigningInLink:(id)arg1;
- (void)showMyAccountLink:(id)arg1;
- (void)showVoicemailLink:(id)arg1;
- (void)showHeartbeatLink:(id)arg1;
- (void)showPrivacyStatementLink:(id)arg1;
- (void)showAskTheSkypeCommunityLink:(id)arg1;
- (void)showGoToSupportLink:(id)arg1;
- (void)showLearnAboutSkypeLink:(id)arg1;
- (void)showHelp:(id)arg1;
- (void)handleTrackingGoURIWithLinkTarget:(id)arg1 queryDictionary:(id)arg2;
- (void)handleGoURIWithSSOToken:(id)arg1 userInfo:(id)arg2;
- (void)handleGoURI:(id)arg1;
- (void)handleBuyCreditURI:(id)arg1;
- (void)dealloc;
- (id)init;

@end

