//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class Application;

@protocol AppStatusClient
- (void)applicationChangedName:(Application *)arg1;
- (void)applicationBecameFront:(Application *)arg1;
- (void)applicationQuit:(Application *)arg1;
- (void)applicationLaunchFinished:(Application *)arg1;
- (void)applicationReady:(Application *)arg1;
- (void)applicationLaunched:(Application *)arg1;
@end

