//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (PLVideoOverlayButton)
+ (struct CGSize)pl_videoOverlayButtonSize;
+ (id)pl_videoOverlayButtonWithStyle:(long long)arg1;
+ (double)pl_setHiddenAnimationDuration;
- (void)pl_setHidden:(BOOL)arg1 delay:(double)arg2 animated:(BOOL)arg3;
- (void)pl_setHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)pl_drawBorderWithColor:(id)arg1 width:(double)arg2;
- (BOOL)pl_isOnScreen:(id)arg1;
@end

