//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSSet, NSString;
@protocol UINSTouchBar;

@interface _UITouchBar : NSObject
{
    id <UINSTouchBar> _touchBar;
    NSSet *_touchBarItems;
}

- (void).cxx_destruct;
- (id)backingBar;
@property(nonatomic) BOOL allowsCustomization;
@property(retain, nonatomic) NSSet *templateItems;
@property(retain, nonatomic) NSString *principalItemIdentifier;
@property(copy, nonatomic) NSArray *itemIdentifiers;
@property(readonly, nonatomic) NSString *identifier;
- (void)setIdentifier:(id)arg1;
- (id)initWithIdentifier:(id)arg1;

@end

