//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class NSString, PBDataReader;

@interface GEOLogMsgEventThrottle : PBCodable <NSCopying>
{
    PBDataReader *_reader;
    CDStruct_158f0f88 _readerMark;
    NSString *_manifestEnv;
    NSString *_requestAppIdentifier;
    double _throttleDuration;
    NSString *_throttleReqType;
    int _networkService;
    unsigned int _throttleCount;
    int _throttleMode;
    unsigned int _throttleTriggerCount;
    unsigned int _throttleTriggerDuration;
    int _throttleType;
    unsigned int _tilesetId;
    struct {
        unsigned int has_throttleDuration:1;
        unsigned int has_networkService:1;
        unsigned int has_throttleCount:1;
        unsigned int has_throttleMode:1;
        unsigned int has_throttleTriggerCount:1;
        unsigned int has_throttleTriggerDuration:1;
        unsigned int has_throttleType:1;
        unsigned int has_tilesetId:1;
        unsigned int read_manifestEnv:1;
        unsigned int read_requestAppIdentifier:1;
        unsigned int read_throttleReqType:1;
        unsigned int wrote_manifestEnv:1;
        unsigned int wrote_requestAppIdentifier:1;
        unsigned int wrote_throttleDuration:1;
        unsigned int wrote_throttleReqType:1;
        unsigned int wrote_networkService:1;
        unsigned int wrote_throttleCount:1;
        unsigned int wrote_throttleMode:1;
        unsigned int wrote_throttleTriggerCount:1;
        unsigned int wrote_throttleTriggerDuration:1;
        unsigned int wrote_throttleType:1;
        unsigned int wrote_tilesetId:1;
    } _flags;
}

+ (BOOL)isValid:(id)arg1;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)readAll:(BOOL)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) BOOL hasThrottleDuration;
@property(nonatomic) double throttleDuration;
@property(nonatomic) BOOL hasThrottleCount;
@property(nonatomic) unsigned int throttleCount;
@property(nonatomic) BOOL hasThrottleTriggerDuration;
@property(nonatomic) unsigned int throttleTriggerDuration;
@property(nonatomic) BOOL hasThrottleTriggerCount;
@property(nonatomic) unsigned int throttleTriggerCount;
@property(retain, nonatomic) NSString *throttleReqType;
@property(readonly, nonatomic) BOOL hasThrottleReqType;
- (void)_readThrottleReqType;
- (int)StringAsThrottleMode:(id)arg1;
- (id)throttleModeAsString:(int)arg1;
@property(nonatomic) BOOL hasThrottleMode;
@property(nonatomic) int throttleMode;
- (int)StringAsThrottleType:(id)arg1;
- (id)throttleTypeAsString:(int)arg1;
@property(nonatomic) BOOL hasThrottleType;
@property(nonatomic) int throttleType;
@property(nonatomic) BOOL hasTilesetId;
@property(nonatomic) unsigned int tilesetId;
@property(retain, nonatomic) NSString *manifestEnv;
@property(readonly, nonatomic) BOOL hasManifestEnv;
- (void)_readManifestEnv;
@property(retain, nonatomic) NSString *requestAppIdentifier;
@property(readonly, nonatomic) BOOL hasRequestAppIdentifier;
- (void)_readRequestAppIdentifier;
- (int)StringAsNetworkService:(id)arg1;
- (id)networkServiceAsString:(int)arg1;
@property(nonatomic) BOOL hasNetworkService;
@property(nonatomic) int networkService;

@end

