//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Safari/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSExtension, NSString;

@protocol SFContentBlockerManagerDelegate <NSObject>
- (BOOL)shouldDisableAllContentBlockers;
- (BOOL)allowUnsignedContentBlockers;
- (NSString *)developerIdentifierForContentBlocker:(NSExtension *)arg1;
- (NSArray *)contentBlockersFromContentBlockersState:(NSDictionary *)arg1;
- (void)replaceLegacyExtensionsWithContentBlocker:(NSExtension *)arg1 userHasChangedEnabledState:(BOOL)arg2;
- (NSArray *)contentBlockersNotBlockedForAnyReason:(NSArray *)arg1;
- (void)contentBlockerEnabledStateDidChange:(NSExtension *)arg1;
- (void)contentBlockersWereRemoved:(NSArray *)arg1;
- (void)contentBlockersWereAdded:(NSArray *)arg1;
- (void)applyEnabledContentBlockers:(NSArray *)arg1;
@end

