//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (DeallocHook)
- (void)removeDeallocHook:(void *)arg1;
- (void *)addDeallocHook:(CDUnknownBlockType)arg1;
- (const char *)cDesc;
- (BOOL)performBoolSelectorIfSupported:(SEL)arg1;
- (void)performSelectorIfSupported:(SEL)arg1;
- (void)setDynamicProperty:(id)arg1 forKey:(id)arg2;
- (id)dynamicPropertyForKey:(id)arg1;
- (id)dynamicProperties;
@end

