//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PDBarButtonItem.h"

@interface PDCameraBarButtonItem : PDBarButtonItem
{
    struct QPointer<CSignalSelectorBinding> _vmConfigChangeBinding;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct QMenu *)popupMenu:(char *)arg1;
- (void)updateConnectedState;
- (id)initWithVm:(struct CVmWrap *)arg1;

@end

