//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "__TMACellNumberInspectorPaneControllerAccessibility_super.h"

@interface TMACellNumberInspectorPaneControllerAccessibility : __TMACellNumberInspectorPaneControllerAccessibility_super
{
}

+ (Class)tsaxBaseSafeCategoryClass;
+ (id)tsaxTargetClassName;
- (id)_tsaxCurrencyPopUpButton;
- (id)_tsaxNegStylePopUpButton;
- (id)_tsaxDecimalPlaceStepper;
- (id)_tsaxDecimalTextField;
- (id)_tsaxDecimalLabel;
- (id)_tsaxNegativeStyleLabelForTag:(unsigned long long)arg1;
- (void)_tsaxApplyNegativeStyleItemLabels;
- (void)tsaxLoadAccessibilityInformation;

@end

