//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "OCDDelayedMedia.h"

@class NSData, NSString;

@interface OADSound : OCDDelayedMedia
{
    NSData *mSoundData;
    NSString *mName;
    int mSizeInBytes;
}

- (void).cxx_destruct;
- (id)description;
- (_Bool)isLoaded;
- (void)setSizeInBytes:(int)arg1;
- (int)sizeInBytes;
- (void)setName:(id)arg1;
- (id)name;
- (void)setSoundData:(id)arg1;
- (id)soundData;

@end

