//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TSWPRangeMap : NSObject
{
    struct _NSRange _subRange;
    vector_7c702c4c _unmappedIndexes;
    vector_7c702c4c _mappedIndexes;
}

@property(nonatomic) vector_7c702c4c mappedIndexes; // @synthesize mappedIndexes=_mappedIndexes;
@property(nonatomic) vector_7c702c4c unmappedIndexes; // @synthesize unmappedIndexes=_unmappedIndexes;
@property(nonatomic) struct _NSRange subRange; // @synthesize subRange=_subRange;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)adjustByDelta:(long long)arg1 startingAt:(unsigned long long)arg2;
- (struct _NSRange)unmappedCharRange:(struct _NSRange)arg1;
- (struct _NSRange)mappedCharRange:(struct _NSRange)arg1;
- (unsigned long long)p_extendRightMappedIndex:(unsigned long long)arg1;
- (unsigned long long)p_extendLeftMappedIndex:(unsigned long long)arg1;
- (unsigned long long)unmappedCharIndex:(unsigned long long)arg1;
- (unsigned long long)mappedCharIndex:(unsigned long long)arg1;
- (id)initWithSubRange:(struct _NSRange)arg1 unmappedIndexes:(const vector_06e666a8 *)arg2 affinity:(int)arg3;
- (id)initWithSubRange:(struct _NSRange)arg1 unmappedIndexes:(const vector_06e666a8 *)arg2 isBackwardAffinities:(const vector_553f084a *)arg3;
- (id)initWithSubRange:(struct _NSRange)arg1 unmappedPairIndexes:(const vector_06e666a8 *)arg2;

@end

