//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIScreen;

__attribute__((visibility("hidden")))
@interface _UIScreenBoundingPathUtilities : NSObject
{
    UIScreen *_screen;
}

+ (id)boundingPathUtilitiesForScreen:(id)arg1;
@property(nonatomic, getter=_screen) __weak UIScreen *screen; // @synthesize screen=_screen;
- (void).cxx_destruct;
- (id)boundingPathForWindow:(id)arg1;
- (id)initWithScreen:(id)arg1;

@end

