//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ContentKit/WFAlert.h>

@class NSArray, UIView, WFAlertPresentationSource;

@interface WFAlert (UIKitAdditions)
- (void)addKeyCommand:(id)arg1;
@property(readonly, nonatomic) NSArray *keyCommands;
@property(nonatomic) struct UIEdgeInsets contentViewPadding;
@property(retain, nonatomic) UIView *contentView;
@property(retain, nonatomic) WFAlertPresentationSource *presentationSource;
@end

