//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudKitDaemon/CKDDatabaseOperation.h>

@class CKDAssetTokenRequest;

__attribute__((visibility("hidden")))
@interface CKDAssetTokenRequestOperation : CKDDatabaseOperation
{
    CKDAssetTokenRequest *_assetTokenRequest;
}

@property(retain, nonatomic) CKDAssetTokenRequest *assetTokenRequest; // @synthesize assetTokenRequest=_assetTokenRequest;
- (void).cxx_destruct;
- (void)main;
- (id)initWithOperationInfo:(id)arg1 clientContext:(id)arg2;

@end

