//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@interface _ThreadDisclosureTextFieldCell : NSTextFieldCell
{
    BOOL _threadIsOpen;
}

@property(nonatomic) BOOL threadIsOpen; // @synthesize threadIsOpen=_threadIsOpen;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (id)accessibilityRole;
- (id)accessibilityValue;
- (BOOL)isAccessibilitySelectorAllowed:(SEL)arg1;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (struct CGRect)drawingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)_textRect;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;

@end

