//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FRURLAnalyticsReferralFactory-Protocol.h"

@class FRAppActivityMonitor;

@interface FRURLAnalyticsReferralFactory : NSObject <FRURLAnalyticsReferralFactory>
{
    FRAppActivityMonitor *_appActivityMonitor;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) FRAppActivityMonitor *appActivityMonitor; // @synthesize appActivityMonitor=_appActivityMonitor;
- (id)_removeAMSTokensFromUrl:(id)arg1;
- (id)_extractWidgetEngagementFromReferralURL:(id)arg1;
- (id)analyticsReferralForURL:(id)arg1 options:(id)arg2;
- (id)initWithAppActivityMonitor:(id)arg1;
- (id)init;

@end

