//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GHViewController.h"

@class NSButton, NSImageView, NSTextField;

@interface GitHub.GHCopyBranchFromForkViewController : GHViewController
{
    // Error parsing type: , name: nameField
    // Error parsing type: , name: copyButton
    // Error parsing type: , name: errorLabel
    // Error parsing type: , name: iconView
}

+ (id)nibName;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithViewModel:(id)arg1;
- (id)init;
- (void)viewDidLoad;
@property(nonatomic) __weak NSImageView *iconView; // @synthesize iconView;
@property(nonatomic) __weak NSTextField *errorLabel; // @synthesize errorLabel;
@property(nonatomic) __weak NSButton *copyButton; // @synthesize copyButton;
@property(nonatomic) __weak NSTextField *nameField; // @synthesize nameField;

@end

