//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ConsoleKit/CSKTableViewController.h>

#import <ConsoleKit/CSKMessagesTableViewEventDelegate-Protocol.h>
#import <ConsoleKit/NSTableViewDataSource-Protocol.h>

@class NSMapTable, NSMutableDictionary, NSObject, NSOperationQueue, NSString;
@protocol CSKMessagesViewControllerDataSource, OS_dispatch_queue;

@interface CSKMessagesViewController : CSKTableViewController <NSTableViewDataSource, CSKMessagesTableViewEventDelegate>
{
    NSObject<OS_dispatch_queue> *_cellUpdateQueue;
    NSMutableDictionary *_rowToBlockOp;
    NSOperationQueue *_cellUpdateOpQueue;
    unsigned long long _currentRow;
    BOOL _allowsMessagesInsertion;
    id <CSKMessagesViewControllerDataSource> _dataSource;
    double _defaultRowHeight;
    NSMapTable *_expandedRowsCache;
}

@property(readonly, nonatomic) NSMapTable *expandedRowsCache; // @synthesize expandedRowsCache=_expandedRowsCache;
@property(nonatomic) double defaultRowHeight; // @synthesize defaultRowHeight=_defaultRowHeight;
@property(nonatomic) BOOL allowsMessagesInsertion; // @synthesize allowsMessagesInsertion=_allowsMessagesInsertion;
@property(nonatomic) __weak id <CSKMessagesViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)scrollRangeToVisible:(struct _NSRange)arg1;
- (struct _NSRange)firstSelectedRange;
- (unsigned long long)stringLength;
- (id)stringAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2 endsWithSearchBoundary:(char *)arg3;
- (id)_padString:(id)arg1;
- (unsigned long long)_rangeToRowIndex:(struct _NSRange)arg1;
- (struct _NSRange)_rangeForCharacterIndex:(unsigned long long)arg1;
- (void)textFinder:(id)arg1 findBarVisibilityDidChange:(BOOL)arg2;
- (id)_expandedRowsInRows:(id)arg1;
- (id)_collapsedRowsInRows:(id)arg1;
- (BOOL)_isRowExpanded:(long long)arg1;
- (double)_cachedHeightForRow:(long long)arg1;
- (void)_removeCachedHeightsForRows:(id)arg1;
- (void)_updateCachedHeightForRow:(unsigned long long)arg1 string:(id)arg2 width:(double)arg3;
- (void)_cacheHeightsForMessagesStringAtIndexes:(id)arg1;
- (void)_reloadMessageStringColumnRows:(id)arg1;
- (BOOL)_isMessageStringColumnVisible;
- (void)scrollViewDidEndResizeNotification:(id)arg1;
- (void)tableView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)messagesTableViewRightArrowDidPress:(id)arg1;
- (void)messagesTableViewLeftArrowDidPress:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)tableView:(id)arg1 didRemoveRowView:(id)arg2 forRow:(long long)arg3;
- (void)tableView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (id)defaultColumnLayout;
- (void)collapseEntitiesAtIndexes:(id)arg1;
- (void)expandEntitiesAtIndexes:(id)arg1;
- (id)entitiesAtIndexes:(id)arg1;
- (id)entityAtIndex:(unsigned long long)arg1;
- (void)reload;
- (void)removeMessagesAtIndexes:(id)arg1;
- (void)insertMessagesAtIndexes:(id)arg1 ignoreFocus:(BOOL)arg2;
- (void)insertMessagesAtIndexes:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

