//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class ContentHuggingTextView, NSClipView, NSPopover, NSString, WBSSavedPassword;
@protocol PasswordsAuditingHandler;

__attribute__((visibility("hidden")))
@interface PasswordsAuditingPopoverViewController : NSViewController
{
    NSString *_duplicatedPasswordDomain;
    NSPopover *_popover;
    id <PasswordsAuditingHandler> _passwordAuditingHandler;
    WBSSavedPassword *_auditingSavedPassword;
    NSClipView *_passwordsAuditingWarningLabelEnclosingClipView;
    ContentHuggingTextView *_passwordsAuditingWarningLabel;
}

@property ContentHuggingTextView *passwordsAuditingWarningLabel; // @synthesize passwordsAuditingWarningLabel=_passwordsAuditingWarningLabel;
@property __weak NSClipView *passwordsAuditingWarningLabelEnclosingClipView; // @synthesize passwordsAuditingWarningLabelEnclosingClipView=_passwordsAuditingWarningLabelEnclosingClipView;
@property(readonly, nonatomic) WBSSavedPassword *auditingSavedPassword; // @synthesize auditingSavedPassword=_auditingSavedPassword;
@property(nonatomic) __weak id <PasswordsAuditingHandler> passwordAuditingHandler; // @synthesize passwordAuditingHandler=_passwordAuditingHandler;
- (void).cxx_destruct;
- (void)closePopover;
- (void)showPopoverWithPositioningView:(id)arg1;
- (void)_updateWarningLabelStringValue;
- (void)viewDidLoad;
- (id)initWithAuditingSavedPassword:(id)arg1;

@end

