//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, PLPhotoLibrary;

@interface PLCacheDeleteSupport : NSObject
{
    PLPhotoLibrary *_photoLibrary;
    struct fsid _fsid;
    NSDate *_exitDeleteTime;
}

+ (BOOL)verifyAndFixLocalAvailabilityForMissingResourcesUsingFileIDInManagedObjectContext:(id)arg1 countPresent:(long long *)arg2 countMissing:(long long *)arg3 countUnableToVerify:(long long *)arg4 error:(id *)arg5;
+ (struct fsid)fsidForURL:(id)arg1;
+ (id)_purgeableResourceDirectoriesForPathManager:(id)arg1;
+ (id)purgeableStateDescriptionForFile:(id)arg1;
+ (BOOL)isPurgeableFile:(id)arg1 outIsPhotoType:(char *)arg2 outUrgencyLevel:(long long *)arg3;
+ (BOOL)clearPurgeableFlagsForAllResourcesInPhotoLibraryURL:(id)arg1;
+ (void)registerNullHandler;
@property(copy, nonatomic) NSDate *exitDeleteTime; // @synthesize exitDeleteTime=_exitDeleteTime;
- (void).cxx_destruct;
- (void)_markAsNotLocallyAvailableForResourcesWithFileIDsToPath:(id)arg1;
- (void)_rescanResourcesFromFileSystem;
- (BOOL)_isFilePurgedForFileID:(id)arg1 purgedPath:(id)arg2;
- (void)_processRemovedFiles:(id)arg1 inMountPoint:(id)arg2;
- (void)_installPurgeObserverAndProcessAlreadyRemovedFiles;
- (BOOL)clearPurgeableFlagsForAllResources;
- (BOOL)clearPurgeableFlagForResource:(id)arg1;
- (BOOL)markResourceAsPurgeable:(id)arg1 withUrgency:(long long)arg2;
- (id)initWithPhotoLibrary:(id)arg1 cplStatus:(id)arg2;

@end

