//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EDCollection;

@interface EDLink : NSObject
{
    int mType;
    EDCollection *mExternalNames;
}

+ (id)linkWithType:(int)arg1;
- (void).cxx_destruct;
- (id)description;
- (id)externalNames;
- (void)setType:(int)arg1;
- (int)type;
- (id)initWithType:(int)arg1;

@end

