//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDecimalNumber, NSLocale, SKProductSubscriptionPeriod;

@interface SKProductDiscount : NSObject
{
    id _internal;
}

- (void).cxx_destruct;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)_setSubscriptionPeriod:(id)arg1;
- (void)_setPriceLocale:(id)arg1;
- (void)_setPrice:(id)arg1;
- (void)_setPaymentMode:(unsigned long long)arg1;
- (void)_setNumberOfPeriods:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long paymentMode;
@property(readonly, nonatomic) unsigned long long numberOfPeriods;
@property(readonly, nonatomic) SKProductSubscriptionPeriod *subscriptionPeriod;
@property(readonly, nonatomic) NSLocale *priceLocale;
@property(readonly, nonatomic) NSDecimalNumber *price;
- (id)init;

@end

