//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Home/HFItemManager.h>

#import <HomeUI/HFAccessorySettingSiriLanguageAdapterObserver-Protocol.h>

@class HFAccessorySettingGroupItem, HFAccessorySettingSiriLanguageAdapter, HUSiriLanguageOptionItemProvider, NSString;

@interface HUAccessorySettingsSiriOutputVoiceItemManager : HFItemManager <HFAccessorySettingSiriLanguageAdapterObserver>
{
    HFAccessorySettingSiriLanguageAdapter *_adapter;
    HUSiriLanguageOptionItemProvider *_accentOptionItemProvider;
    HUSiriLanguageOptionItemProvider *_genderOptionItemProvider;
}

- (void).cxx_destruct;
@property(retain, nonatomic) HUSiriLanguageOptionItemProvider *genderOptionItemProvider; // @synthesize genderOptionItemProvider=_genderOptionItemProvider;
@property(retain, nonatomic) HUSiriLanguageOptionItemProvider *accentOptionItemProvider; // @synthesize accentOptionItemProvider=_accentOptionItemProvider;
@property(readonly, nonatomic) HFAccessorySettingSiriLanguageAdapter *adapter; // @synthesize adapter=_adapter;
- (void)siriLanguageAdapter:(id)arg1 availableLanguageOptionsDidChange:(id)arg2;
- (void)siriLanguageAdapter:(id)arg1 selectedLanguageOptionDidChange:(id)arg2;
- (void)_unregisterForExternalUpdates;
- (void)_registerForExternalUpdates;
- (id)_buildSectionsWithDisplayedItems:(id)arg1;
- (id)_buildItemProvidersForHome:(id)arg1;
- (id)updateSelectionWithOptionItem:(id)arg1;
@property(readonly, copy, nonatomic) HFAccessorySettingGroupItem *groupItem;
- (id)initWithDelegate:(id)arg1 groupItem:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (id)initWithDelegate:(id)arg1 sourceItem:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

