//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SASerializable.h"

@class NSString;

@interface SATurnstileInfo : NSObject <SASerializable>
{
    unsigned char _priority;
    unsigned char _numHops;
    unsigned long long _context;
    unsigned long long _flags;
}

+ (id)turnstileInfoWithKCDataTurnstileInfo:(const struct stackshot_thread_turnstileinfo *)arg1;
+ (id)newInstanceWithoutReferencesFromSerializedBuffer:(const CDStruct_f186406e *)arg1 bufferLength:(unsigned long long)arg2;
+ (id)classDictionaryKey;
@property(readonly) unsigned long long flags; // @synthesize flags=_flags;
@property(readonly) unsigned char numHops; // @synthesize numHops=_numHops;
@property(readonly) unsigned char priority; // @synthesize priority=_priority;
@property(readonly) unsigned long long context; // @synthesize context=_context;
- (id)descriptionForTid:(unsigned long long)arg1 threadPriority:(int)arg2 options:(unsigned long long)arg3 nameCallback:(CDUnknownBlockType)arg4;
- (BOOL)displaysSameContentAs:(id)arg1 withDisplayOptions:(unsigned long long)arg2;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)matchesKCDataTurnstileInfo:(const struct stackshot_thread_turnstileinfo *)arg1;
- (long long)compare:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)initWithKCDataTurnstileInfo:(const struct stackshot_thread_turnstileinfo *)arg1;
- (void)populateReferencesUsingBuffer:(const CDStruct_f186406e *)arg1 bufferLength:(unsigned long long)arg2 andDeserializationDictionary:(struct NSMutableDictionary *)arg3 andDataBufferDictionary:(struct NSMutableDictionary *)arg4;
- (void)addSelfToSerializationDictionary:(struct NSMutableDictionary *)arg1;
- (BOOL)addSelfToBuffer:(CDStruct_f186406e *)arg1 bufferLength:(unsigned long long)arg2 withCompletedSerializationDictionary:(struct NSMutableDictionary *)arg3;
- (unsigned long long)sizeInBytesForSerializedVersion;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

