//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HFController, HFTemplateNode;

__attribute__((visibility("hidden")))
@interface HFTemplateController : NSObject
{
    BOOL _requireFailed;
    unsigned long long _anchor;
    HFController *_controller;
    unsigned long long _position;
    unsigned long long _endian;
    HFTemplateNode *_root;
    HFTemplateNode *_currentNode;
}

@property BOOL requireFailed; // @synthesize requireFailed=_requireFailed;
@property __weak HFTemplateNode *currentNode; // @synthesize currentNode=_currentNode;
@property(retain) HFTemplateNode *root; // @synthesize root=_root;
@property unsigned long long endian; // @synthesize endian=_endian;
@property unsigned long long position; // @synthesize position=_position;
@property(retain) HFController *controller; // @synthesize controller=_controller;
@property unsigned long long anchor; // @synthesize anchor=_anchor;
- (void).cxx_destruct;
- (void)addEntryWithLabel:(id)arg1 value:(id)arg2 length:(unsigned long long *)arg3 offset:(unsigned long long *)arg4;
- (id)currentSection;
- (void)endSection;
- (void)beginSectionWithLabel:(id)arg1;
- (unsigned long long)length;
- (void)goTo:(unsigned long long)arg1;
- (void)moveTo:(long long)arg1;
- (BOOL)requireDataAtOffset:(unsigned long long)arg1 toMatchHexValues:(id)arg2;
- (BOOL)isEOF;
- (void)addNodeWithLabel:(id)arg1 value:(id)arg2 size:(unsigned long long)arg3;
- (BOOL)readUUID:(id *)arg1 forLabel:(id)arg2;
- (BOOL)readMacDate:(id *)arg1 forLabel:(id)arg2;
- (BOOL)readDouble:(double *)arg1 forLabel:(id)arg2;
- (BOOL)readFloat:(float *)arg1 forLabel:(id)arg2;
- (BOOL)readInt8:(char *)arg1 forLabel:(id)arg2;
- (BOOL)readUInt8:(char *)arg1 forLabel:(id)arg2 asHex:(BOOL)arg3;
- (BOOL)readInt16:(short *)arg1 forLabel:(id)arg2;
- (BOOL)readUInt16:(unsigned short *)arg1 forLabel:(id)arg2 asHex:(BOOL)arg3;
- (BOOL)readUInt24:(unsigned int *)arg1 forLabel:(id)arg2;
- (BOOL)readInt32:(int *)arg1 forLabel:(id)arg2;
- (BOOL)readUInt32:(unsigned int *)arg1 forLabel:(id)arg2 asHex:(BOOL)arg3;
- (BOOL)readInt64:(long long *)arg1 forLabel:(id)arg2;
- (BOOL)readUInt64:(unsigned long long *)arg1 forLabel:(id)arg2 asHex:(BOOL)arg3;
- (id)readStringDataForSize:(unsigned long long)arg1 encoding:(id)arg2 forLabel:(id)arg3;
- (id)readHexDataForSize:(unsigned long long)arg1 forLabel:(id)arg2;
- (id)readBytesForSize:(unsigned long long)arg1 forLabel:(id)arg2;
- (id)readDataForSize:(unsigned long long)arg1;
- (BOOL)readBytes:(void *)arg1 size:(unsigned long long)arg2;
- (id)evaluateScript:(id)arg1;
- (id)evaluateScript:(id)arg1 forController:(id)arg2 error:(id *)arg3;

@end

