//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "__KNSlideNavigatorSlideDataAccessibility_super.h"

@class NSString;

@interface KNSlideNavigatorSlideDataAccessibility : __KNSlideNavigatorSlideDataAccessibility_super
{
}

+ (Class)tsaxBaseSafeCategoryClass;
+ (id)tsaxTargetClassName;
- (long long)_tsaxDisclosureState;
- (id)tsaxIndicatorDescriptionWithBuilds:(BOOL)arg1 withTransition:(BOOL)arg2 withNotes:(BOOL)arg3;
@property(readonly, nonatomic) BOOL tsaxIsSkipped;
@property(readonly, nonatomic) unsigned long long tsaxNumberOfChildren;
@property(readonly, nonatomic) BOOL tsaxHasParent;
@property(readonly, nonatomic) BOOL tsaxHasChildren;
@property(readonly, nonatomic) unsigned long long tsaxIndentIndex;
@property(readonly, nonatomic) unsigned long long tsaxIndentNumber;
@property(readonly, nonatomic) BOOL tsaxIsDisclosed;
@property(readonly, nonatomic) unsigned long long tsaxSlideNumber;
@property(readonly, nonatomic) unsigned long long tsaxSlideIndex;
@property(readonly, nonatomic) NSString *tsaxMasterName;
@property(readonly, nonatomic) NSString *tsaxInferredTitle;
- (id)tsaxTarget;

@end

