//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import "TSDModalMouseEventHandler-Protocol.h"

@class NSString, TMACanvasHUDPositionHelper;
@protocol TMACanvasHUDViewDelegate;

@interface TMACanvasHUDView : NSView <TSDModalMouseEventHandler>
{
    struct CGPoint _mouseDownLocationInSuperview;
    struct CGPoint _oldOrigin;
    TMACanvasHUDPositionHelper *_postitionHelper;
    id <TMACanvasHUDViewDelegate> _delegate;
}

@property(nonatomic) __weak id <TMACanvasHUDViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)wantsMouseDownAtPoint:(struct CGPoint)arg1 withEvent:(id)arg2;
- (BOOL)mouseMovedAtPoint:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)updateCursorAtPoint:(struct CGPoint)arg1 withEvent:(id)arg2;
- (BOOL)wantsUpdateCursorAtPoint:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)updateLocationForFrame:(struct CGRect)arg1;
- (void)setOrigin:(struct CGPoint)arg1 constrainToRect:(struct CGRect)arg2;
- (void)setHidden:(BOOL)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

