//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface PKPaymentRemoteInstrumentThumbnailView : UIView
{
    UIImageView *_placeholderImageView;
    UIImageView *_cardImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *cardImageView; // @synthesize cardImageView=_cardImageView;
@property(retain, nonatomic) UIImageView *placeholderImageView; // @synthesize placeholderImageView=_placeholderImageView;
- (void)_updateCardImage:(struct CGImage *)arg1;
- (void)_prepareConstraints;
- (id)initWithRemotePaymentInstrument:(id)arg1;

@end

