//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BefContainer : NSObject
{
    const struct BEFGRUPPE *gr;
    int grI;
    const struct BEFEHL *b;
    int bI;
}

+ (id)befContainer:(const struct BEFGRUPPE *)arg1 grIndex:(int)arg2 befehl:(const struct BEFEHL *)arg3 index:(int)arg4;
- (int)befehlI;
- (const struct BEFEHL *)befehlP;
- (int)befGruppeI;
- (const struct BEFGRUPPE *)befGruppeP;

@end

