//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppleMediaServices/AMSMetricsEvent.h>

@class NSArray, NSString;

@interface AMSMetricsLoadURLEvent : AMSMetricsEvent
{
}

+ (double)_timingDataMetricToServerTimeInterval:(id)arg1;
+ (id)_resolvedIPAddressFromTask:(id)arg1;
+ (double)_randomDouble;
+ (id)_metricsDictionaryFromConfig:(id)arg1;
+ (id)_fetchNetworkQualityReports;
+ (id)_DNSServerIPAddresses;
+ (BOOL)shouldCollectMetricsForContext:(id)arg1;
@property(retain) NSString *xxdc;
@property double xpSamplingPercentageCachedResponses;
@property double xpSamplingPercentageUsers;
@property BOOL xpSamplingForced;
@property double xpSessionDuration;
@property(retain) NSString *wt;
@property BOOL TLSSessionTickets;
@property(retain) NSString *TIDState;
@property BOOL TFOEnabled;
@property long long statusCode;
@property double secureConnectionStartTime;
@property double responseStartTime;
@property unsigned long long responseMessageSize;
@property double responseEndTime;
@property(retain) NSString *responseDate;
@property(retain) NSString *resolvedIPAddress;
@property(retain) NSString *requestURL;
@property unsigned long long requestMessageSize;
@property double requestStartTime;
@property double redirectStartTime;
@property double redirectEndTime;
@property unsigned long long redirectCount;
@property(retain) NSString *radioType;
@property(retain) NSString *radioTechnology;
@property(retain) NSString *originalApp;
@property(retain) NSArray *networkQualityReports;
@property double fetchStartTime;
@property(retain) NSString *environmentDataCenter;
@property(retain) NSString *edgeNodeCacheStatus;
@property double domainLookupStartTime;
@property double domainLookupEndTime;
@property(retain) NSString *DNSServers;
@property(retain) NSString *connectionType;
@property double connectionStartTime;
@property unsigned long long connectionStopNStatTXBytes;
@property unsigned long long connectionStopNStatRXBytes;
@property unsigned long long connectionStartNStatTXBytes;
@property unsigned long long connectionStartNStatRXBytes;
@property BOOL connectionReused;
@property(retain) NSString *connectionInterface;
@property double connectionEndTime;
@property(retain) NSString *clientError;
@property(retain) NSString *clientCorrelationKey;
@property BOOL cachedResponse;
@property BOOL apsRelaySucceeded;
@property BOOL apsRelayDidFallback;
@property BOOL apsRelayAttempted;
@property(retain) NSString *appleTimingApp;
- (void)_prepareEventWithContext:(id)arg1;
- (id)initWithContext:(id)arg1;

@end

