//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSFileHandle, NSString, NSTimer;

@interface STPrivilegedTask : NSObject
{
    NSTimer *_checkStatusTimer;
    BOOL _isRunning;
    int _processIdentifier;
    int _terminationStatus;
    NSArray *_arguments;
    NSString *_currentDirectoryPath;
    NSString *_launchPath;
    NSFileHandle *_outputFileHandle;
    CDUnknownBlockType _terminationHandler;
}

+ (BOOL)authorizationFunctionAvailable;
+ (id)launchedPrivilegedTaskWithLaunchPath:(id)arg1 arguments:(id)arg2 currentDirectory:(id)arg3 authorization:(struct AuthorizationOpaqueRef *)arg4;
+ (id)launchedPrivilegedTaskWithLaunchPath:(id)arg1 arguments:(id)arg2 currentDirectory:(id)arg3;
+ (id)launchedPrivilegedTaskWithLaunchPath:(id)arg1 arguments:(id)arg2;
+ (id)launchedPrivilegedTaskWithLaunchPath:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
@property(copy) CDUnknownBlockType terminationHandler; // @synthesize terminationHandler=_terminationHandler;
@property(readonly) int terminationStatus; // @synthesize terminationStatus=_terminationStatus;
@property(readonly) int processIdentifier; // @synthesize processIdentifier=_processIdentifier;
@property(readonly) BOOL isRunning; // @synthesize isRunning=_isRunning;
@property(readonly) NSFileHandle *outputFileHandle; // @synthesize outputFileHandle=_outputFileHandle;
@property(copy) NSString *launchPath; // @synthesize launchPath=_launchPath;
@property(copy) NSString *currentDirectoryPath; // @synthesize currentDirectoryPath=_currentDirectoryPath;
@property(copy) NSArray *arguments; // @synthesize arguments=_arguments;
- (id)description;
- (void)checkTaskStatus;
- (void)waitUntilExit;
- (void)terminate;
- (int)launchWithAuthorization:(struct AuthorizationOpaqueRef *)arg1;
- (int)launch;
- (id)initWithLaunchPath:(id)arg1 arguments:(id)arg2 currentDirectory:(id)arg3;
- (id)initWithLaunchPath:(id)arg1 arguments:(id)arg2;
- (id)initWithLaunchPath:(id)arg1;
- (id)init;

@end

