//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "TMADocumentWindowToolbarController.h"

@class NSToolbarItem;

@interface TNMacDocumentWindowToolbarController : TMADocumentWindowToolbarController
{
    NSToolbarItem *_addCategoryItem;
}

+ (id)makeAddCategoryItem;
@property(retain, nonatomic) NSToolbarItem *addCategoryItem; // @synthesize addCategoryItem=_addCategoryItem;
- (void).cxx_destruct;
- (id)p_toolTips;
- (void)closePopovers;
- (BOOL)toolbarItemIsValidInVersionBrowser:(id)arg1;
- (BOOL)toolbarItemIsValidInReadOnlyMode:(id)arg1;
- (BOOL)toolbarItemIsValidInViewingMode:(id)arg1;
- (void)toolbarDidRemoveToolbarItem:(id)arg1;
- (void)toolbarWillAddToolbarItem:(id)arg1;
- (id)makeItemForIdentifier:(id)arg1;
- (id)allowedItemIdentifiers;
- (id)defaultItemIdentifiers;

@end

