//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <OfficeImport/OITSUFormatObject.h>

__attribute__((visibility("hidden")))
@interface OITSUMutableFormatObject : OITSUFormatObject
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) CDStruct_730f14de formatStruct; // @dynamic formatStruct;

@end

