//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "StylesBase.h"

@class NSArray, NSImage;

@interface ABAnimatedIconStyles : StylesBase
{
    NSImage *_backgroundImage;
    NSImage *_backgroundMapImage;
    NSArray *_backgroundRingMaskImages;
    NSArray *_backgroundRingAnimationDurations;
    NSImage *_foregroundMapImage;
    NSArray *_foregroundRingMaskImages;
    NSArray *_foregroundRingAnimationDurations;
    struct CGPoint _anchorPoint;
}

@property(retain, nonatomic) NSArray *foregroundRingAnimationDurations; // @synthesize foregroundRingAnimationDurations=_foregroundRingAnimationDurations;
@property(retain, nonatomic) NSArray *foregroundRingMaskImages; // @synthesize foregroundRingMaskImages=_foregroundRingMaskImages;
@property(retain, nonatomic) NSImage *foregroundMapImage; // @synthesize foregroundMapImage=_foregroundMapImage;
@property(retain, nonatomic) NSArray *backgroundRingAnimationDurations; // @synthesize backgroundRingAnimationDurations=_backgroundRingAnimationDurations;
@property(retain, nonatomic) NSArray *backgroundRingMaskImages; // @synthesize backgroundRingMaskImages=_backgroundRingMaskImages;
@property(retain, nonatomic) NSImage *backgroundMapImage; // @synthesize backgroundMapImage=_backgroundMapImage;
@property(retain, nonatomic) NSImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(nonatomic) struct CGPoint anchorPoint; // @synthesize anchorPoint=_anchorPoint;
- (void).cxx_destruct;

@end

