//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData, NSDate, NSNumber, NSString;

@interface ISDDataWrapper : NSObject <NSCoding>
{
    NSString *_guid;
    NSString *_extension;
    NSDate *_moddate;
    NSData *_signature;
    NSNumber *_length;
    unsigned int _hash;
    NSString *_subdir;
    NSData *_dataCache;
    NSString *_recordId;
    NSString *_propertyName;
    BOOL _faultFailure;
    NSString *_previousExtension;
}

+ (id)dataReferencePathNamesWithExtension:(id)arg1 prependSubdirs:(BOOL)arg2;
+ (void)setDataReferenceDirectory:(id)arg1;
+ (id)dataReferenceDirectory;
+ (id)dataWrapperWithData:(id)arg1;
+ (void)initialize;
+ (void)deleteAllReferencesForClientWithId:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (int)isd_quickDirtyCoderType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)deleteDataReference:(id *)arg1;
- (BOOL)saveDataReference:(id *)arg1 withExtension:(id)arg2;
- (BOOL)swapPreviousBackingStore:(id)arg1;
- (BOOL)isd_isEqual:(id)arg1;
- (BOOL)_backingStoreExists;
- (id)loadData;
- (id)isd_data;
- (id)data;
- (id)dataReference;
- (BOOL)isd_isAttributeSelfConsistent;
- (BOOL)_dataReferenceWasSaved;
- (unsigned long long)_dataReferenceCount:(id)arg1;
- (id)_pathToDataUsingPreviousExtension;
- (BOOL)backingStoreEqual:(id)arg1;
- (id)_pathToData;
- (id)_composePathToData:(id)arg1;
- (id)_pathToDataDirectory;
- (BOOL)dataFaultFailure;
- (id)dataCache;
- (unsigned long long)length;
- (void)setSignature:(id)arg1;
- (id)signature;
- (void)setModdate:(id)arg1;
- (id)moddate;
- (id)previousExtension;
- (void)setExtension:(id)arg1 savePrevious:(BOOL)arg2;
- (void)setPreviousExtension:(id)arg1;
- (void)setExtension:(id)arg1;
- (id)extension;
- (void)setGuid:(id)arg1;
- (id)guid;
- (id)initWithQuickDirtyCoder:(id)arg1;
- (void)encodeWithQuickDirtyCoder:(id)arg1;
- (id)description;
- (id)_loadData;
- (void)dealloc;
- (id)initDataWrapperWithData:(id)arg1;
- (void)_updateWrapperWithData;
- (BOOL)_isUpToDateWithData;
- (void)setPropertyName:(id)arg1;
- (id)propertyName;
- (void)setRecordId:(id)arg1;
- (id)recordId;
- (id)dataWrapper;

@end

