//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOLocation, NSMutableArray, NSString, PBDataReader, PBUnknownFields;

__attribute__((visibility("hidden")))
@interface GEOPDExternalTransitLookupParameters : PBCodable <NSCopying>
{
    PBDataReader *_reader;
    CDStruct_158f0f88 _readerMark;
    PBUnknownFields *_unknownFields;
    NSMutableArray *_externalTransitStationCodes;
    NSString *_sourceId;
    GEOLocation *_transactionLocation;
    double _transactionTimestamp;
    struct {
        unsigned int has_transactionTimestamp:1;
        unsigned int read_unknownFields:1;
        unsigned int read_externalTransitStationCodes:1;
        unsigned int read_sourceId:1;
        unsigned int read_transactionLocation:1;
        unsigned int wrote_unknownFields:1;
        unsigned int wrote_externalTransitStationCodes:1;
        unsigned int wrote_sourceId:1;
        unsigned int wrote_transactionLocation:1;
        unsigned int wrote_transactionTimestamp:1;
    } _flags;
}

+ (BOOL)isValid:(id)arg1;
+ (Class)externalTransitStationCodeType;
- (void).cxx_destruct;
- (void)clearUnknownFields:(BOOL)arg1;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)readAll:(BOOL)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)externalTransitStationCodeAtIndex:(unsigned long long)arg1;
- (unsigned long long)externalTransitStationCodesCount;
- (void)_addNoFlagsExternalTransitStationCode:(id)arg1;
- (void)addExternalTransitStationCode:(id)arg1;
- (void)clearExternalTransitStationCodes;
@property(retain, nonatomic) NSMutableArray *externalTransitStationCodes;
- (void)_readExternalTransitStationCodes;
@property(retain, nonatomic) NSString *sourceId;
@property(readonly, nonatomic) BOOL hasSourceId;
- (void)_readSourceId;
@property(retain, nonatomic) GEOLocation *transactionLocation;
@property(readonly, nonatomic) BOOL hasTransactionLocation;
- (void)_readTransactionLocation;
@property(nonatomic) BOOL hasTransactionTimestamp;
@property(nonatomic) double transactionTimestamp;

@end

