//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ContactsAutocomplete/CNAutocompleteResult.h>

@interface CNAutocompleteResult (SocialUIAdditions)
+ (id)_imHandleForID:(id)arg1 account:(id)arg2 forceCreate:(BOOL)arg3;
+ (id)resultWithChat:(id)arg1;
+ (id)resultWithName:(id)arg1 imHandleID:(id)arg2 person:(id)arg3 account:(id)arg4 result:(id)arg5 addressType:(long long)arg6;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)displayID;
- (id)handleIDForAccount:(id)arg1;
- (id)person;
- (id)account;
- (id)chat;
- (id)imHandleForAccount:(id)arg1 forceCreate:(BOOL)arg2;
@end

