//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABRemoteLabeledValue.h"

@class ABRemoteCustomProperty, NSDate, NSString;

@interface ABRemoteLabeledValue (SearchHelpers)
- (id)valueForKeyPath:(id)arg1;
- (id)dictionaryValue;
- (id)customPropertyValue;
@property(readonly) NSString *uniqueId;
@property(readonly) NSString *zipCode;
@property(readonly) NSString *stringValue;
@property(readonly) NSString *street;
@property(readonly) NSString *state;
@property(readonly) NSString *sama;
@property(readonly) NSString *region;
@property(readonly) NSString *name;
@property(readonly) NSString *fullNumber;
@property(readonly) NSDate *dateValue;
@property(readonly) double dateYearless;
@property(readonly) NSDate *date;
@property(readonly) ABRemoteCustomProperty *customProperty;
@property(readonly) NSString *countryName;
@property(readonly) NSString *countryCode;
@property(readonly) NSString *city;
@property(readonly) NSString *addressNormalized;
@property(readonly) NSString *address;
@end

