//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DTSDisplayPortDevice.h"

@class DTSDPDeviceDescription, DTSDisplayPortDeviceAnalyticsData, NSString;

@interface DTSDPDeviceProxy : NSObject <DTSDisplayPortDevice>
{
    DTSDPDeviceDescription *_remoteDeviceDescription;
    NSString *_portLookupKey;
    long long _portState;
    id <DTSIOPMAssertion> _sleepAssertion;
    DTSDisplayPortDeviceAnalyticsData *_analyticsData;
}

+ (void)initialize;
+ (long long)portStateForKey:(id)arg1;
+ (void)setPortState:(long long)arg1 forKey:(id)arg2;
+ (long long)i2cTransactionLengthLimit;
+ (long long)nativeAUXTransactionLengthLimit;
- (void).cxx_destruct;
@property(retain, nonatomic) DTSDisplayPortDeviceAnalyticsData *analyticsData; // @synthesize analyticsData=_analyticsData;
@property(retain, nonatomic) id <DTSIOPMAssertion> sleepAssertion; // @synthesize sleepAssertion=_sleepAssertion;
@property(nonatomic) long long portState; // @synthesize portState=_portState;
@property(readonly, nonatomic) NSString *portLookupKey; // @synthesize portLookupKey=_portLookupKey;
@property(retain, nonatomic) DTSDPDeviceDescription *remoteDeviceDescription; // @synthesize remoteDeviceDescription=_remoteDeviceDescription;
@property(readonly, nonatomic) id <DTSDisplayPortDeviceInfo> info;
- (BOOL)unlock:(id *)arg1;
- (BOOL)lock:(id *)arg1;
- (BOOL)_isDeviceLocked;
- (void)_deassertPortState;
- (BOOL)_assertPortState:(id *)arg1;
- (id)i2cWriteReadAtAddress:(long long)arg1 data:(id)arg2 length:(long long)arg3 error:(id *)arg4;
- (BOOL)i2cWriteAtAddress:(long long)arg1 data:(id)arg2 error:(id *)arg3;
- (id)i2cReadAtAddress:(long long)arg1 length:(long long)arg2 error:(id *)arg3;
- (BOOL)nativeWriteAtAddress:(long long)arg1 data:(id)arg2 error:(id *)arg3;
- (id)nativeReadAtAddress:(long long)arg1 length:(long long)arg2 error:(id *)arg3;
- (id)initWithDescription:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

