//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MCMessage, MessageListObjectProxy, NSColor, NSLayoutConstraint, ToCCIndicator;

@interface MessageListTableCellView : NSTableCellView
{
    NSColor *_textColor;
    BOOL _showToCc;
    ToCCIndicator *_toCCIndicator;
    NSLayoutConstraint *_subjectLeadingToIndicatorConstraint;
}

+ (id)keyPathsForValuesAffectingTextColor;
+ (id)keyPathsForValuesAffectingMessage;
- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *subjectLeadingToIndicatorConstraint; // @synthesize subjectLeadingToIndicatorConstraint=_subjectLeadingToIndicatorConstraint;
@property(retain, nonatomic) ToCCIndicator *toCCIndicator; // @synthesize toCCIndicator=_toCCIndicator;
- (void)_updateToCCIndicatorWithString:(id)arg1;
@property(nonatomic) BOOL showToCc; // @synthesize showToCc=_showToCc;
- (void)_preserveContentTintForImageViews:(id)arg1;
@property(retain, nonatomic) NSColor *textColor;
@property(readonly, nonatomic) MCMessage *message;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain) MessageListObjectProxy *objectValue;
- (void)_setSymbolFonts;
- (void)updateFontsUsingBold:(BOOL)arg1;
- (void)setBackgroundStyle:(long long)arg1;
- (void)awakeFromNib;

@end

