//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AddressBook/NSObject-Protocol.h>

@class ABCollectionViewItem, NSString;
@protocol ABCardCollectionViewDelegate, ABCardViewMultiValue;

@protocol ABCollectionMultiPropertyAction <NSObject>
@property(readonly) NSString *targetPropertyKey;
- (NSString *)titleForTarget:(id <ABCardViewMultiValue>)arg1;
- (void)executeWithTarget:(id <ABCardViewMultiValue>)arg1 delegate:(id <ABCardCollectionViewDelegate>)arg2;
- (BOOL)validateWithTarget:(id <ABCardViewMultiValue>)arg1;
- (id)initWithCollectionViewItem:(ABCollectionViewItem *)arg1 targetPropertyKey:(NSString *)arg2;
@end

