//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LiConcurrentQueueEntry : NSObject
{
    BOOL _barrier;
    CDUnknownBlockType _block;
}

@property(nonatomic) BOOL barrier; // @synthesize barrier=_barrier;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (id)initWithBlock:(CDUnknownBlockType)arg1 barrier:(BOOL)arg2;

@end

