//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <VoiceMemos/RCWaveformDataSource.h>

@interface RCPlaceholderWaveformDataSource : RCWaveformDataSource
{
    double _placeholderDuration;
}

- (void)beginLoading;
- (double)duration;
- (id)initWithDuration:(double)arg1;
- (id)initWithWaveformGenerator:(id)arg1 generatedWaveformOutputURL:(id)arg2;

@end

