//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RBProcess, RBProcessStateChangeSet, RBSystemState;

@protocol RBThrottleBestEffortNetworkingManaging <NSObject>
- (BOOL)isThrottleBestEffortNetworkingEnabled;
- (void)removeProcess:(RBProcess *)arg1;
- (void)addProcess:(RBProcess *)arg1;
- (void)applySystemState:(RBSystemState *)arg1;
- (void)didUpdateProcessStates:(RBProcessStateChangeSet *)arg1;
@end

