//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthKit/HKFeatureAvailabilityDataSource-Protocol.h>

@class NSString;

@interface HKActiveWatchFeatureAvailabilityDataSource : NSObject <HKFeatureAvailabilityDataSource>
{
    NSString *_electrocardiogramOnboardingCountryCode;
    NSString *_atrialFibrillationDetectionOnboardingCountryCode;
}

@property(copy, nonatomic) NSString *atrialFibrillationDetectionOnboardingCountryCode; // @synthesize atrialFibrillationDetectionOnboardingCountryCode=_atrialFibrillationDetectionOnboardingCountryCode;
@property(copy, nonatomic) NSString *electrocardiogramOnboardingCountryCode; // @synthesize electrocardiogramOnboardingCountryCode=_electrocardiogramOnboardingCountryCode;
- (void).cxx_destruct;
- (CDStruct_f6aba300)watchElectrocardiogramVersion;
- (CDStruct_f6aba300)watchAtrialFibrillationDetectionVersion;
- (id)watchCompanionDevicePlatform;
- (id)watchOSBuildVersion;
- (id)watchProductType;
- (id)watchBuildType;
- (id)watchModelNumber;
- (id)watchRegion;
- (CDStruct_f6aba300)watchOSVersion;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

