//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "TSDEditor-Protocol.h"

@class NSArray, NSNumber, TSKChangeRecord, TSUColor, TSWPFont, TSWPFontInspectorController, TSWPFontSizeInspectorController;

@protocol TSWPFontInspecting <NSObject, TSDEditor>

@optional
- (BOOL)fontPicker:(TSWPFontInspectorController *)arg1 shouldReloadForChangeRecord:(TSKChangeRecord *)arg2;
- (NSArray *)displayedObjectsForFontInspector;
- (void)setFontSize:(double)arg1;
- (void)setFontSizeDelta:(NSNumber *)arg1;
- (void)setFontColor:(TSUColor *)arg1;
- (TSUColor *)currentFontColor;
- (void)fontSizeController:(TSWPFontSizeInspectorController *)arg1 choseNamedFontSize:(int)arg2;
- (int)currentNamedFontSizeForFontSizeController:(TSWPFontSizeInspectorController *)arg1;
- (void)fontSizeController:(TSWPFontSizeInspectorController *)arg1 choseFontSize:(double)arg2;
- (double)currentFontSizeForFontSizeController:(TSWPFontSizeInspectorController *)arg1;
- (void)fontPicker:(TSWPFontInspectorController *)arg1 choseFont:(TSWPFont *)arg2 preserveFace:(BOOL)arg3;
- (TSWPFont *)currentFontForFontPicker:(TSWPFontInspectorController *)arg1;
@end

