//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _CDPaths : NSObject
{
}

+ (id)interactionCopyDirectory;
+ (id)interactionTestDirectory;
+ (id)DKKnowledgeTestDirectoryString;
+ (id)knowledgeTestDirectory;
+ (id)monitorBundlePath;
+ (id)policiesConfigPath;
+ (id)userKnowledgeDirectory;
+ (id)knowledgeDirectory;
+ (id)peopleDirectory;
+ (id)defaultSleepPath;
+ (id)otaSleepPath;
+ (id)eventPlistPath;
+ (id)contentProviderBundlePaths;
+ (id)contentProvidersPath;
+ (id)simulatorSharedPathFor:(id)arg1;
+ (id)simulatorHomePathFor:(id)arg1;
+ (id)simulatorSystemPathFor:(id)arg1 withEnvVar:(id)arg2;
+ (id)bundleBuiltInPlugInsPath;
+ (id)bundlePathForResource:(id)arg1 ofType:(id)arg2;

@end

