//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Safari/CompletionControllerObjCAdapter.h>

@class _MKResultView;

__attribute__((visibility("hidden")))
@interface UnifiedFieldCompletionControllerObjCAdapter : CompletionControllerObjCAdapter
{
    _MKResultView *_reusableMKResultView;
    double _lastKnownUnifiedFieldWidth;
    double _lastKnownWindowBackingScaleFactor;
}

- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (void)prepareForReloadOfCompletionList;
- (void)_configureParsecReportProblemTableCellView:(id)arg1;
- (void)_configureParsecMapsExtraCompletionListItemTableCellView:(id)arg1 forCompletionListItem:(struct ParsecMapsExtraCompletionListItem *)arg2;
- (void)_configureParsecSingleLineTableCellView:(id)arg1 forCompletionListItem:(struct ParsecSearchResultCompletionListItem *)arg2;
- (void)_configureParsecSimpleTableCellView:(id)arg1 forCompletionListItem:(struct ParsecSearchResultCompletionListItem *)arg2;
- (void)_configureParsecMovieListTableCellView:(id)arg1 forCompletionListItem:(struct ParsecSearchResultCompletionListItem *)arg2;
- (void)_configureParsecITunesTableCellView:(id)arg1 forCompletionListItem:(struct ParsecSearchResultCompletionListItem *)arg2;
- (void)_appendSpaceToAttributedStringIfNecessary:(id)arg1 withAttributes:(id)arg2;
- (id)_ratingStringForSearchResult:(id)arg1;
- (id)_rottenTomatoesInformationForSearchResult:(id)arg1 withSession:(id)arg2;
- (id)_stringFromGlyphs:(id)arg1;
- (id)_attributedStringWithGlyph:(id)arg1 shouldSkipHighlighting:(BOOL)arg2;
- (id)_textAttachmentWithGlyph:(id)arg1 highlighted:(BOOL)arg2;
- (id)_descriptionTextAttributesWithWrapping:(BOOL)arg1;
- (id)_descriptionTextAttributes;
- (id)_footnoteForSearchResult:(id)arg1;
- (void)_configureTitleTextField:(id)arg1 inTableCellView:(id)arg2 withAttributedString:(id)arg3;
- (void)_configureDescriptionTextField:(id)arg1 inTableCellView:(id)arg2 withAttributedString:(id)arg3;
- (void)_configureTextField:(id)arg1 inTableCellView:(id)arg2 withAttributedString:(id)arg3 highlightedAttributedString:(id)arg4;
- (id)_titleTextAttributesWithWrapping:(BOOL)arg1;
- (id)_titleTextAttributes;
- (id)_parsecCellViewForCompletionListItem:(struct CompletionListItem *)arg1;
- (int)_parsecCellViewTypeForCompletionListItem:(struct CompletionListItem *)arg1;
- (int)_parsecCellViewTypeForResult:(id)arg1;
- (BOOL)shouldAbortCompletionFromNotification:(id)arg1;
- (void)completionListDidShow;
- (struct UnifiedFieldCompletionController *)unifiedFieldCompletionController;

@end

