//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Safari/WBSFormAutoFillItem.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WBSUserTypedFormString : WBSFormAutoFillItem
{
    NSString *_userTypedString;
}

@property(readonly, nonatomic) NSString *userTypedString; // @synthesize userTypedString=_userTypedString;
- (void).cxx_destruct;
- (id)completion;
- (id)initWithUserTypedString:(id)arg1;

@end

