//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MSCMSAttributeCoder.h"

@class MSOID;

__attribute__((visibility("hidden")))
@interface MSCMSContentTypeAttribute : NSObject <MSCMSAttributeCoder>
{
    MSOID *_contentType;
}

+ (id)contentTypeAttributeWithOID:(id)arg1;
@property(retain) MSOID *contentType; // @synthesize contentType=_contentType;
- (void).cxx_destruct;
- (id)initWithOID:(id)arg1;
- (id)encodeAttributeWithError:(id *)arg1;
- (id)initWithAttribute:(id)arg1 error:(id *)arg2;

@end

