//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <VectorKit/NSObject-Protocol.h>

@class VKAnimation, VKWorld;

@protocol VKWorldDelegate <NSObject>
- (void)runAnimation:(VKAnimation *)arg1;
- (void)worldDisplayDidChange:(VKWorld *)arg1;
- (void)worldLayoutDidChange:(VKWorld *)arg1;
@end

