//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class IPXVersionArrayController, NSArray, NSSet;

@protocol IPXVersionArrayControllerChange

@optional
- (void)versionArrayController:(IPXVersionArrayController *)arg1 didUpdateVersions:(NSArray *)arg2 forKeyPaths:(NSSet *)arg3;
- (void)versionArrayControllerDidChange:(IPXVersionArrayController *)arg1;
@end

