//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PVSearchResultSectionItem.h"

@class NSArray, PDFDestination, PDFSelection;

@interface PVSearchResultPDFSectionItem : PVSearchResultSectionItem
{
    PDFDestination *_sectionStart;
    PDFDestination *_sectionEnd;
    NSArray *_sectionPath;
    BOOL _isPsuedoSection;
    PDFSelection *_cachedSelectionOfExtent;
}

- (void).cxx_destruct;
@property(copy) NSArray *sectionPath; // @synthesize sectionPath=_sectionPath;
@property(retain) PDFDestination *sectionEnd; // @synthesize sectionEnd=_sectionEnd;
@property(retain) PDFDestination *sectionStart; // @synthesize sectionStart=_sectionStart;
- (void)purgeTemporaryData;
- (id)stringOfExtent;
- (id)selectionOfExtent;
- (id)mediaElement;
- (id)ordinalValue;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithPage:(id)arg1 relevanceScore:(double)arg2;
- (id)initWithStart:(id)arg1 andEnd:(id)arg2 relevanceScore:(double)arg3;

@end

