//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Contacts/NSSecureCoding-Protocol.h>

@class NSString;

@interface CNChangeHistoryFetchRequest : NSObject <NSSecureCoding>
{
    BOOL _contactChanges;
    BOOL _groupChanges;
    NSString *_clientIdentifier;
}

+ (BOOL)supportsSecureCoding;
@property BOOL groupChanges; // @synthesize groupChanges=_groupChanges;
@property BOOL contactChanges; // @synthesize contactChanges=_contactChanges;
@property(retain) NSString *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
- (id)description;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

