//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IMDaemonCore/IMServicePlugInAll-Protocol.h>

@class NSDictionary, NSString;

@protocol IMServicePlugInDispatcher <IMServicePlugInAll>
- (oneway void)_handleFileTransferStopped:(NSString *)arg1;
- (oneway void)_handleFileTransferAccepted:(NSString *)arg1 path:(NSString *)arg2;
- (oneway void)_addOutgoingFileTransferWithGUID:(NSString *)arg1 handle:(NSString *)arg2 path:(NSString *)arg3 type:(NSString *)arg4 totalBytes:(unsigned long long)arg5;
- (oneway void)_terminate;
- (oneway void)_readyWithAccountSettings:(NSDictionary *)arg1;
@end

