//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "TSDMacSidebarCapableRowView.h"

#import "TSDMacAnnotationViewSizing-Protocol.h"

@class NSLayoutConstraint, NSString, TSDMacCommonHeaderView, TSDMacHighlightContentView, TSDMacHighlightFooterView;
@protocol TSDAnnotationEditor, TSDComment, TSDMacHighlightViewDelegate;

@interface TSDMacHighlightView : TSDMacSidebarCapableRowView <TSDMacAnnotationViewSizing>
{
    id <TSDMacHighlightViewDelegate> _delegate;
    id <TSDComment> _comment;
    id <TSDAnnotationEditor> _annotationEditor;
    TSDMacCommonHeaderView *_headerView;
    TSDMacHighlightContentView *_highlightContentView;
    TSDMacHighlightFooterView *_footerView;
    NSLayoutConstraint *_highlightHeightConstraint;
    NSLayoutConstraint *_footerHeightConstraint;
    double _cachedViewHeight;
    double _cachedViewWidth;
}

@property(nonatomic) double cachedViewWidth; // @synthesize cachedViewWidth=_cachedViewWidth;
@property(nonatomic) double cachedViewHeight; // @synthesize cachedViewHeight=_cachedViewHeight;
@property(retain, nonatomic) NSLayoutConstraint *footerHeightConstraint; // @synthesize footerHeightConstraint=_footerHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *highlightHeightConstraint; // @synthesize highlightHeightConstraint=_highlightHeightConstraint;
@property(retain, nonatomic) TSDMacHighlightFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) TSDMacHighlightContentView *highlightContentView; // @synthesize highlightContentView=_highlightContentView;
@property(retain, nonatomic) TSDMacCommonHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <TSDAnnotationEditor> annotationEditor; // @synthesize annotationEditor=_annotationEditor;
@property(retain, nonatomic) id <TSDComment> comment; // @synthesize comment=_comment;
@property(nonatomic) __weak id <TSDMacHighlightViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)p_contentViewFrameDidChange:(id)arg1;
- (void)p_addContentViewConstraints;
- (void)p_addFooterViewConstraints;
- (void)p_addHeaderViewConstraints;
- (void)p_convertToComment:(id)arg1;
- (void)p_nextAnnotation:(id)arg1;
- (void)p_previousAnnotation:(id)arg1;
- (void)p_deleteHighlight:(id)arg1;
- (void)p_updateControlVisibility;
- (void)p_setupConstraints;
- (void)p_setupButtonActions;
- (void)p_setupViews;
- (void)p_setup;
- (void)p_setSubviewsWidth:(double)arg1;
- (void)updateDateFieldsRelativeToNow;
- (void)setSidebarMode:(BOOL)arg1;
- (double)prototypeHeight;
- (void)setWidth:(double)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)layout;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1 annotationEditor:(id)arg2 comment:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

