//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@class NSMutableArray;
@protocol TSKModel;

@interface TSKDocumentModelEnumerator : NSEnumerator
{
    BOOL _stop;
    id <TSKModel> _root;
    NSMutableArray *_enumeratorStack;
    CDUnknownBlockType _filter;
}

@property(copy, nonatomic) CDUnknownBlockType filter; // @synthesize filter=_filter;
@property(retain, nonatomic) NSMutableArray *enumeratorStack; // @synthesize enumeratorStack=_enumeratorStack;
@property(retain, nonatomic) id <TSKModel> root; // @synthesize root=_root;
- (void)enumerateUsingBlock:(CDUnknownBlockType)arg1;
- (id)nextObject;
- (void)dealloc;
- (id)initWithEnumerator:(id)arg1 filter:(CDUnknownBlockType)arg2;
- (id)initWithRootModelObject:(id)arg1 filter:(CDUnknownBlockType)arg2;
- (void)enumerateReferencedStylesUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateModelAndReferencedStylesUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateStyleClientsUsingBlock:(CDUnknownBlockType)arg1;

@end

