//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <ScreenSharing/SSGestureEvent.h>

@interface SSGestureScrollEvent : SSGestureEvent
{
    double mDeltaX;
    double mDeltaY;
    double mDeltaZ;
    BOOL mIsNaturalScrolling;
    long long mGesturePhase;
    long long mGestureMask;
}

+ (id)gestureScrollEventWithCoordinates:(struct SSPoint)arg1 subType:(long long)arg2 deltaX:(double)arg3 deltaY:(double)arg4 deltaZ:(double)arg5 naturalScrolling:(BOOL)arg6 gesturePhase:(long long)arg7 gestureMask:(long long)arg8;
@property(readonly) long long gestureMask; // @synthesize gestureMask=mGestureMask;
@property(readonly) long long gesturePhase; // @synthesize gesturePhase=mGesturePhase;
@property(readonly) BOOL isNaturalScrolling; // @synthesize isNaturalScrolling=mIsNaturalScrolling;
@property(readonly) double deltaZ; // @synthesize deltaZ=mDeltaZ;
@property(readonly) double deltaY; // @synthesize deltaY=mDeltaY;
@property(readonly) double deltaX; // @synthesize deltaX=mDeltaX;
- (id)initWithCoordinates:(struct SSPoint)arg1 subType:(long long)arg2 deltaX:(double)arg3 deltaY:(double)arg4 deltaZ:(double)arg5 naturalScrolling:(BOOL)arg6 gesturePhase:(long long)arg7 gestureMask:(long long)arg8;

@end

