//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ActionKit/BOXModel.h>

#import <ActionKit/WFNaming-Protocol.h>
#import <ActionKit/WFRemoteFile-Protocol.h>

@class BOXFolderMini, BOXSharedLink, BOXUserMini, NSArray, NSDate, NSNumber, NSString;

@interface BOXItem : BOXModel <WFNaming, WFRemoteFile>
{
    NSString *_sequenceID;
    NSString *_name;
    NSString *_etag;
    NSDate *_createdDate;
    NSDate *_modifiedDate;
    NSString *_itemDescription;
    NSNumber *_size;
    NSArray *_pathFolders;
    NSDate *_trashedDate;
    NSDate *_purgedDate;
    NSDate *_contentCreatedDate;
    NSDate *_contentModifiedDate;
    BOXUserMini *_creator;
    BOXUserMini *_lastModifier;
    BOXUserMini *_owner;
    BOXSharedLink *_sharedLink;
    NSArray *_allowedSharedLinkAccessLevels;
    BOXFolderMini *_parentFolder;
    NSString *_status;
    NSArray *_collections;
    unsigned long long _canShare;
    unsigned long long _canSetShareAccess;
    unsigned long long _canRename;
    unsigned long long _canDelete;
    unsigned long long _canInviteCollaborator;
    unsigned long long _hasCollaborations;
    unsigned long long _isExternallyOwned;
    NSArray *_allowedInviteeRoles;
    NSArray *_metadata;
}

@property(retain, nonatomic) NSArray *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) NSArray *allowedInviteeRoles; // @synthesize allowedInviteeRoles=_allowedInviteeRoles;
@property(nonatomic) unsigned long long isExternallyOwned; // @synthesize isExternallyOwned=_isExternallyOwned;
@property(nonatomic) unsigned long long hasCollaborations; // @synthesize hasCollaborations=_hasCollaborations;
@property(nonatomic) unsigned long long canInviteCollaborator; // @synthesize canInviteCollaborator=_canInviteCollaborator;
@property(nonatomic) unsigned long long canDelete; // @synthesize canDelete=_canDelete;
@property(nonatomic) unsigned long long canRename; // @synthesize canRename=_canRename;
@property(nonatomic) unsigned long long canSetShareAccess; // @synthesize canSetShareAccess=_canSetShareAccess;
@property(nonatomic) unsigned long long canShare; // @synthesize canShare=_canShare;
@property(retain, nonatomic) NSArray *collections; // @synthesize collections=_collections;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) BOXFolderMini *parentFolder; // @synthesize parentFolder=_parentFolder;
@property(retain, nonatomic) NSArray *allowedSharedLinkAccessLevels; // @synthesize allowedSharedLinkAccessLevels=_allowedSharedLinkAccessLevels;
@property(retain, nonatomic) BOXSharedLink *sharedLink; // @synthesize sharedLink=_sharedLink;
@property(retain, nonatomic) BOXUserMini *owner; // @synthesize owner=_owner;
@property(retain, nonatomic) BOXUserMini *lastModifier; // @synthesize lastModifier=_lastModifier;
@property(retain, nonatomic) BOXUserMini *creator; // @synthesize creator=_creator;
@property(retain, nonatomic) NSDate *contentModifiedDate; // @synthesize contentModifiedDate=_contentModifiedDate;
@property(retain, nonatomic) NSDate *contentCreatedDate; // @synthesize contentCreatedDate=_contentCreatedDate;
@property(retain, nonatomic) NSDate *purgedDate; // @synthesize purgedDate=_purgedDate;
@property(retain, nonatomic) NSDate *trashedDate; // @synthesize trashedDate=_trashedDate;
@property(retain, nonatomic) NSArray *pathFolders; // @synthesize pathFolders=_pathFolders;
@property(retain, nonatomic) NSNumber *size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(retain, nonatomic) NSDate *modifiedDate; // @synthesize modifiedDate=_modifiedDate;
@property(retain, nonatomic) NSDate *createdDate; // @synthesize createdDate=_createdDate;
@property(retain, nonatomic) NSString *etag; // @synthesize etag=_etag;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *sequenceID; // @synthesize sequenceID=_sequenceID;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *availableCollectionRank;
@property(readonly, nonatomic) BOOL isBookmark;
@property(readonly, nonatomic) BOOL isFolder;
@property(readonly, nonatomic) BOOL isFile;
- (id)initWithJSON:(id)arg1;
@property(readonly, copy, nonatomic) NSString *wfName;
- (BOOL)wfIsEqualToFile:(id)arg1;
- (id)wfFileType;
- (id)wfLastModifiedDate;
- (id)wfFileSize;
- (id)wfPath;
- (BOOL)wfIsDirectory;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

