//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsBaseLightMonitor.h"

#import "MKLocationManagerObserver-Protocol.h"

@class CLLocation, GCDTimer, GEOAlmanac, NSObject, NSString;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MapsAstronomicalConditionMonitor : MapsBaseLightMonitor <MKLocationManagerObserver>
{
    GEOAlmanac *_daylightAlmanac;
    GEOAlmanac *_twilightAlmanac;
    NSObject<OS_dispatch_queue> *_computeQueue;
    long long _astronomicalCondition;
    CLLocation *_currentLocation;
    GCDTimer *_timeCheckTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GCDTimer *timeCheckTimer; // @synthesize timeCheckTimer=_timeCheckTimer;
@property(retain, nonatomic) CLLocation *currentLocation; // @synthesize currentLocation=_currentLocation;
- (long long)_computeOnQueueAstronomicalConditionForTime:(double)arg1 currentLocation:(id)arg2;
- (void)computeAstronomicalConditionForTime:(double)arg1 currentLocation:(id)arg2;
- (void)timeDidChangeSignificantly;
- (void)scheduleTimeCheck;
- (BOOL)locationManagerShouldPauseLocationUpdates:(id)arg1;
- (void)locationManagerFailedToUpdateLocation:(id)arg1 withError:(id)arg2;
- (void)locationManagerDidResumeLocationUpdates:(id)arg1;
- (void)locationManagerDidReset:(id)arg1;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
- (void)locationManager:(id)arg1 didUpdateVehicleSpeed:(double)arg2 timestamp:(id)arg3;
- (void)locationManager:(id)arg1 didUpdateVehicleHeading:(double)arg2 timestamp:(id)arg3;
- (void)locationManagerUpdatedLocation:(id)arg1;
@property(nonatomic) long long astronomicalCondition; // @synthesize astronomicalCondition=_astronomicalCondition;
- (void)_setMonitoring:(BOOL)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

