//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface _SPResultsArrays : NSObject
{
    unsigned long long _queryId;
    NSArray *_topHits;
    NSArray *_results;
    double _blendingDuration;
}

@property double blendingDuration; // @synthesize blendingDuration=_blendingDuration;
@property(retain) NSArray *results; // @synthesize results=_results;
@property(retain) NSArray *topHits; // @synthesize topHits=_topHits;
@property unsigned long long queryId; // @synthesize queryId=_queryId;
- (void).cxx_destruct;

@end

