//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MPLinkedListNode-Protocol.h"

@class IECachedImageRep, IEFileSystemItem, NSString;

__attribute__((visibility("hidden")))
@interface IEImageCacheItem : NSObject <MPLinkedListNode>
{
    IECachedImageRep *imageRep;
    unsigned long long memoryDataSize;
    IEFileSystemItem *representedFSI;
    IEImageCacheItem *previousNode;
    IEImageCacheItem *nextNode;
    NSString *keyStr;
}

@property(retain, nonatomic) IEFileSystemItem *representedFSI; // @synthesize representedFSI;
@property(nonatomic) unsigned long long memoryDataSize; // @synthesize memoryDataSize;
@property(retain, nonatomic) IECachedImageRep *imageRep; // @synthesize imageRep;
- (void).cxx_destruct;
- (id)quickKey;
- (void)setNextNode:(id)arg1;
- (id)nextNode;
- (void)setPreviousNode:(id)arg1;
- (id)previousNode;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

