//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "IPXBrowserModel.h"

@protocol IPXCollection_deprecated;

@interface IPXEditorBrowserModel : IPXBrowserModel
{
    id <IPXCollection_deprecated> _collection;
    long long _countOfColumns;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) long long countOfColumns; // @synthesize countOfColumns=_countOfColumns;
@property(retain, nonatomic) id <IPXCollection_deprecated> collection; // @synthesize collection=_collection;
- (void).cxx_destruct;
- (void)setPrimarySelection:(id)arg1;
- (void)setSelectedObjects:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_startObservingCollectionContent;
- (void)_stopObservingCollectionContent;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

