//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray;

@interface iTermLineBlockCacheCollection : NSObject <NSCopying>
{
    NSMutableArray *_caches;
    int _capacity;
}

- (void).cxx_destruct;
@property(nonatomic) int capacity; // @synthesize capacity=_capacity;
- (void)appendValue:(long long)arg1;
- (void)setLastValueWithBlock:(CDUnknownBlockType)arg1;
- (void)setFirstValueWithBlock:(CDUnknownBlockType)arg1;
- (void)removeFirstValue;
- (void)removeLastValue;
- (void)evictIfNeeded;
- (void)setNumLinesCache:(id)arg1 forWidth:(int)arg2;
- (id)numLinesCacheForWidth:(int)arg1;
- (id)dumpForCrashlog;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

