//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNHandleStringClassifier, NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface CNContactClassifiedHandleStringInterpreter : NSObject
{
    BOOL _hasBeenInterpreted;
    CNHandleStringClassifier *_classifier;
    NSMutableArray *_emailAddressesImpl;
    NSMutableArray *_phoneNumbersImpl;
    NSMutableArray *_postalAddressesImpl;
    NSMutableArray *_unconvertableHandles;
}

@property(nonatomic) BOOL hasBeenInterpreted; // @synthesize hasBeenInterpreted=_hasBeenInterpreted;
@property(readonly, nonatomic) NSMutableArray *unconvertableHandles; // @synthesize unconvertableHandles=_unconvertableHandles;
@property(readonly, nonatomic) NSMutableArray *postalAddressesImpl; // @synthesize postalAddressesImpl=_postalAddressesImpl;
@property(readonly, nonatomic) NSMutableArray *phoneNumbersImpl; // @synthesize phoneNumbersImpl=_phoneNumbersImpl;
@property(readonly, nonatomic) NSMutableArray *emailAddressesImpl; // @synthesize emailAddressesImpl=_emailAddressesImpl;
@property(readonly, nonatomic) CNHandleStringClassifier *classifier; // @synthesize classifier=_classifier;
- (void).cxx_destruct;
@property(readonly) NSArray *postalAddresses;
@property(readonly) NSArray *phoneNumbers;
@property(readonly) NSArray *emailAddresses;
- (void)interpretUnknowns;
- (void)interpretPostalAddresses;
- (void)interpretPhoneNumbers;
- (void)interpretEmailAddresses;
- (void)interpretValues;
- (id)description;
- (id)initWithHandleStringClassifier:(id)arg1;
- (id)init;

@end

