//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "SDBGAbstractSlide.h"

@interface SDBGMasterSlide : SDBGAbstractSlide
{
}

+ (const char *)idPrefix;
+ (unsigned long long)childDescriptionCount;
+ (const CDStruct_183601bc **)childDescriptionArray;
+ (struct __CFSet **)childDescriptionSetPointer;
+ (struct __CFSet *)childDescriptionSet;
+ (void)initialize;
- (id)drawablesLayer;
- (void)createTreeInTheme:(id)arg1;
- (void)finalizeXml;
- (id)initTreeAt:(struct _xmlNode *)arg1 root:(id)arg2;
- (void)createTree;
- (BOOL)isHasFloatingContentOverridden;
- (void)setHasFloatingContent:(BOOL)arg1;
- (BOOL)hasFloatingContent;
- (void)setName:(id)arg1;
- (id)name;
- (id)styleSheet;

@end

