//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;
@protocol KNTimebase;

@interface KNTimebasePeriodicTimeObserver : NSObject
{
    id <KNTimebase> _timebase;
    id _timeDiscontinuityObserver;
    NSTimer *_timeUpdateTimer;
    double _timeUpdateInterval;
    double _currentTime;
    BOOL _observingRate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(nonatomic) double timeUpdateInterval; // @synthesize timeUpdateInterval=_timeUpdateInterval;
@property(readonly, nonatomic) id <KNTimebase> timebase; // @synthesize timebase=_timebase;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)p_stopTimeUpdateTimer;
- (void)p_startTimeUpdateTimerAtDate:(id)arg1;
- (void)p_updateCurrentTimeFromTimer:(id)arg1;
- (void)p_updateCurrentTime;
- (void)stopUpdating;
- (void)startUpdatingAtDate:(id)arg1;
- (void)startUpdating;
- (void)dealloc;
- (id)init;
- (id)initWithTimebase:(id)arg1;

@end

