//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, TreeNode;

@interface TreeEnumerator : NSObject
{
    TreeNode *root;
    TreeNode *current;
    NSMutableArray *nodes;
}

+ (id)enumeratorWithRoot:(id)arg1;
- (void)reset;
- (void)skipDescendants;
- (id)nextObject;
- (id)initWithRoot:(id)arg1;
- (void)dealloc;

@end

