//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ABDefaultGroupEntriesFactory, ABGroupEntriesList;

@interface ABLastImportGroupController : NSObject
{
    ABGroupEntriesList *_groupEntriesList;
    ABDefaultGroupEntriesFactory *_groupEntriesFactory;
}

- (void)updateShowsLastImportGroup:(BOOL)arg1;
- (void)primitiveSetShowsLastImportGroup:(BOOL)arg1;
- (void)overrideShowsLastImportGroup:(BOOL)arg1;
@property(nonatomic) BOOL showsLastImportGroup;
- (void)dealloc;
- (id)initWithGroupEntriesList:(id)arg1 groupEntriesFactory:(id)arg2;

@end

