//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class ComApplePreferenceSpeechKeyCaptureTextField, NSButton;

@interface ComApplePreferenceSpeechSpeakingHotKeyCaptureSheet : NSWindowController
{
    ComApplePreferenceSpeechKeyCaptureTextField *_speakingKeyComboTextField;
    NSButton *_saveButton;
    id _delegate;
}

+ (id)defaultSpeakingHotKeyCaptureSheet;
- (void)textDidChange;
- (void)cancelSpeakingKeyEditsButtonPressed:(id)arg1;
- (void)saveSpeakingKeyEditsButtonPressed:(id)arg1;
- (void)closeWindow;
- (void)showSheetWithDelegate:(id)arg1 modalForWindow:(id)arg2;

@end

