//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CalDAVPrincipalSearchSupport : NSObject
{
}

+ (id)parserMappingsWithServerSupportSet:(id)arg1 includeEmail:(BOOL)arg2;
+ (id)resultTypeForRecordType:(id)arg1;
+ (id)propertySearchItemForWellKnownType:(int)arg1;
+ (id)namespaceAndNameForWellKnownType:(int)arg1;
+ (id)namespaceForWellKnownType:(int)arg1;
+ (id)nameForWellKnownType:(int)arg1;

@end

