//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KNMovieSampleGeneratorTrack-Protocol.h"

@class CALayer, NSString;
@protocol KNCALayerImageBufferGenerator, OS_dispatch_queue;

@interface KNCALayerMovieSampleGeneratorTrack : NSObject <KNMovieSampleGeneratorTrack>
{
    CALayer *_layer;
    CDStruct_e83c9415 _generatedTimeRange;
    CDStruct_1b6d18a9 _frameDuration;
    NSObject<OS_dispatch_queue> *_queue;
    id <KNCALayerImageBufferGenerator> _imageBufferGenerator;
    CDStruct_1b6d18a9 _nextSampleBufferTime;
    BOOL _hasNextSampleBuffer;
    struct CGSize _mediaSize;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL hasNextSampleBuffer; // @synthesize hasNextSampleBuffer=_hasNextSampleBuffer;
@property(readonly, nonatomic) struct CGSize mediaSize; // @synthesize mediaSize=_mediaSize;
- (void)p_finish;
- (void)p_setUpImageBufferGeneratorIfNeeded;
- (void)cancel;
- (struct opaqueCMSampleBuffer *)copyNextSampleBufferReturningError:(out id *)arg1;
@property(readonly, nonatomic) NSString *mediaType;
- (void)dealloc;
- (id)initWithLayer:(id)arg1 generatedTimeRange:(CDStruct_e83c9415)arg2 frameDuration:(CDStruct_1b6d18a9)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

