//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class ARUICountdownView, CAMediaTimingFunction, NSString;

@protocol ARUICountdownAnimation
+ (NSString *)identifier;
- (void)applyToCountdownView:(ARUICountdownView *)arg1 completion:(void (^)(void))arg2;
- (NSString *)identifier;
- (BOOL)cancelable;
- (CAMediaTimingFunction *)timingFunction;
- (double)duration;
- (double)delay;

@optional
- (unsigned long long)countdownStep;
@end

