//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKitCore/UIView.h>

#import <UIKitCore/CAAnimationDelegate-Protocol.h>

@class NSString, UIButton, UIColor;

__attribute__((visibility("hidden")))
@interface _UIButtonMaskAnimationView : UIView <CAAnimationDelegate>
{
    unsigned long long _hardEdge;
    UIView *_hardEdgeLine;
    UIButton *_delegate;
}

@property(nonatomic) UIButton *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
@property unsigned long long hardEdge;
@property(nonatomic) UIColor *borderColor;
@property double borderWidth;
- (void)layoutSubviews;
- (struct CGRect)_frameForLine;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

