//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface VMAudioParameter : NSObject
{
    float _defaultValue;
    float _min;
    float _max;
    int _address;
    float _value;
    int _internalAddress;
    NSString *_name;
    NSString *_graphName;
}

+ (id)parameterWithName:(id)arg1 defaultValue:(float)arg2 min:(float)arg3 max:(float)arg4 internalAddress:(int)arg5 graphName:(id)arg6;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *graphName; // @synthesize graphName=_graphName;
@property(nonatomic) int internalAddress; // @synthesize internalAddress=_internalAddress;
@property(readonly, nonatomic) float value; // @synthesize value=_value;
@property(nonatomic) int address; // @synthesize address=_address;
@property(readonly, nonatomic) float max; // @synthesize max=_max;
@property(readonly, nonatomic) float min; // @synthesize min=_min;
@property(readonly, nonatomic) float defaultValue; // @synthesize defaultValue=_defaultValue;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (float)currentValue;
- (id)initWithName:(id)arg1 defaultValue:(float)arg2 min:(float)arg3 max:(float)arg4 internalAddress:(int)arg5 graphName:(id)arg6;

@end

