//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <EmailFoundation/EFSQLExpressable-Protocol.h>
#import <EmailFoundation/EFSQLJoinable-Protocol.h>

@class EFSQLSelectStatement, NSString;
@protocol EFSQLExpressable;

@interface _EFSQLJoinExpression : NSObject <EFSQLExpressable, EFSQLJoinable>
{
    BOOL _isLeftOuter;
    EFSQLSelectStatement *_select;
    NSString *_tableName;
    id <EFSQLExpressable> _joinConstraint;
}

@property(readonly, nonatomic) BOOL isLeftOuter; // @synthesize isLeftOuter=_isLeftOuter;
@property(readonly, nonatomic) id <EFSQLExpressable> joinConstraint; // @synthesize joinConstraint=_joinConstraint;
@property(readonly, copy, nonatomic) NSString *tableName; // @synthesize tableName=_tableName;
@property(readonly, nonatomic) __weak EFSQLSelectStatement *select; // @synthesize select=_select;
- (void).cxx_destruct;
- (id)leftOuterJoin:(id)arg1 sourceColumn:(id)arg2 targetColumn:(id)arg3;
- (id)join:(id)arg1 sourceColumn:(id)arg2 targetColumn:(id)arg3;
- (id)leftOuterJoin:(id)arg1 on:(id)arg2;
- (id)join:(id)arg1 on:(id)arg2;
@property(readonly, copy, nonatomic) NSString *ef_SQLExpression;
- (id)initWithSelect:(id)arg1 tableName:(id)arg2 joinConstraint:(id)arg3 isLeftOuter:(BOOL)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

