//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Metal/MTLCommandEncoder-Protocol.h>

@class NSString;
@protocol MTLBuffer, MTLTexture;

@protocol MTLDebugCommandEncoder <MTLCommandEncoder>
- (void)IOLogBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (void)kprintfBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (void)IOLog:(NSString *)arg1;
- (void)kprintf:(NSString *)arg1;

@optional
- (void)postFinishEvent:(const char *)arg1;
- (void)dumpTexture:(id <MTLTexture>)arg1 name:(const char *)arg2;
- (void)dumpBuffer:(id <MTLBuffer>)arg1 name:(const char *)arg2;
@end

