//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSButton, NSTextField, NSTrackingArea;

@interface KNMacPresenterDisplayConfigurationPickerTableCellView : NSTableCellView
{
    NSButton *_menuButton;
    NSTextField *_shortcutNameField;
    NSTrackingArea *_trackingArea;
}

@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) NSTextField *shortcutNameField; // @synthesize shortcutNameField=_shortcutNameField;
@property(retain, nonatomic) NSButton *menuButton; // @synthesize menuButton=_menuButton;
- (void).cxx_destruct;
- (void)dealloc;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (long long)backgroundStyle;
- (void)viewDidMoveToWindow;

@end

