//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8Podcasts19LibraryDataProvider : NSObject
{
    // Error parsing type: , name: $__lazy_storage_$_actionController
    // Error parsing type: , name: $__lazy_storage_$_libraryActionController
    // Error parsing type: , name: podcastStateController
    // Error parsing type: , name: episodePlayStateController
    // Error parsing type: , name: episodeSavedStateController
    // Error parsing type: , name: keyValueSyncUtil
    // Error parsing type: , name: reviewController
    // Error parsing type: , name: episodeStateController
    // Error parsing type: , name: episodeStateControllerProvider
    // Error parsing type: , name: managedContextProvider
    // Error parsing type: , name: hudPresenter
    // Error parsing type: , name: assetsFolder
    // Error parsing type: , name: downloadsRestoreController
    // Error parsing type: , name: topicScoresProvider
    // Error parsing type: , name: jobStorageFactory
}

- (void).cxx_destruct;
- (void)restorePreviouslyDownloadedEpisodes;
- (BOOL)handleEventsForBackgroundURLSessionWithIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)init;

@end

