//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LPCompiler, NSString;

__attribute__((visibility("hidden")))
@interface LPEngineCOFFEE : NSObject
{
    LPCompiler *_rootCompiler;
    NSString *_pathToCOFFEECompiler;
}

- (id)versionOfExecutableAtPath:(id)arg1;
- (id)version;
- (id)dataByConcatenatingFilesAtPathsAndEscapingJavascript:(id)arg1;
- (void)compileFile:(id)arg1 fromTaskGroup:(id)arg2 withResultInfo:(id)arg3;
- (BOOL)switchToCompilerType:(long long)arg1 withPathToExternalCompiler:(id)arg2;
- (void)dealloc;
- (id)initWithRootCompiler:(id)arg1;

@end

