//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreData/NSLocking-Protocol.h>

@class NSArray, NSManagedObjectModel, NSString, _PFModelMap;

@interface NSPersistentStoreCoordinator : NSObject <NSLocking>
{
    id _queueOwner;
    void *_dispatchQueue;
    struct _persistentStoreCoordinatorFlags {
        unsigned int _isRegistered:1;
        unsigned int _canUseDirectDispatch:1;
        unsigned int _reservedFlags:30;
    } _flags;
    unsigned int _reserved32;
    long long _miniLock;
    id *_additionalPrivateIvars;
    NSManagedObjectModel *_managedObjectModel;
    NSArray *_persistentStores;
}

+ (BOOL)removeUbiquitousContentAndPersistentStoreAtURL:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)alloc;
+ (id)metadataForPersistentStoreWithURL:(id)arg1 error:(id *)arg2;
+ (id)elementsDerivedFromExternalRecordURL:(id)arg1;
+ (BOOL)setMetadata:(id)arg1 forPersistentStoreOfType:(id)arg2 URL:(id)arg3 error:(id *)arg4;
+ (BOOL)setMetadata:(id)arg1 forPersistentStoreOfType:(id)arg2 URL:(id)arg3 options:(id)arg4 error:(id *)arg5;
+ (BOOL)_setMetadata:(id)arg1 forPersistentStoreOfType:(id)arg2 URL:(id)arg3 options:(id)arg4 error:(id *)arg5;
+ (id)metadataForPersistentStoreOfType:(id)arg1 URL:(id)arg2 options:(id)arg3 error:(id *)arg4;
+ (id)metadataForPersistentStoreOfType:(id)arg1 URL:(id)arg2 error:(id *)arg3;
+ (id)_metadataForPersistentStoreOfType:(id)arg1 URL:(id)arg2 options:(id)arg3 error:(id *)arg4;
+ (Class)_classForPersistentStoreAtURL:(id)arg1;
+ (id)registeredStoreTypes;
+ (void)registerStoreClass:(Class)arg1 forStoreType:(id)arg2;
+ (void)_registerCoreDataStoreClass:(Class)arg1 forStoreType:(id)arg2;
+ (void)__Multithreading_Violation_AllThatIsLeftToUsIsHonor__;
+ (BOOL)accessInstanceVariablesDirectly;
+ (void)initialize;
+ (id)ubiquityStoreURLForStoreURL:(id)arg1 ubiquityIdentityToken:(id)arg2 localPeerID:(id)arg3 ubiquityName:(id)arg4;
+ (id)ubiquityStoreURLForStoreURL:(id)arg1 ubiquityIdentityToken:(id)arg2 ubiquityName:(id)arg3;
+ (id)elementsDerivedFromSupportURL:(id)arg1;
+ (void)_registerDefaultStoreClassesAndTypes;
+ (Class)_storeClassForStoreType:(id)arg1;
+ (id)_storeTypeForStore:(id)arg1;
+ (void)_endPowerAssertionWithAssert:(unsigned long long)arg1 andApp:(id)arg2;
+ (id)_beginPowerAssertionNamed:(id)arg1 withAssert:(unsigned long long *)arg2;
+ (BOOL)removePersistentHistoryFromPersistentStoreAtURL:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (unsigned long long)__platformOptions;
- (id)executeRequest:(id)arg1 withContext:(id)arg2 error:(id *)arg3;
- (BOOL)_canRouteToStore:(id)arg1 forContext:(id)arg2;
- (id)_routableStoresForContext:(id)arg1 fromStores:(id)arg2;
- (void)_introspectLastErrorAndThrow;
- (void)_coordinator_you_never_successfully_opened_the_database_io_error:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_disk_full:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_cant_open:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_no_permission:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_missing_directory:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_device_locked:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_corrupted:(id)arg1;
- (void)_coordinator_you_never_successfully_opened_the_database_so_saving_back_to_it_is_kinda_hard:(id)arg1;
- (void)_coordinator_no_idea_what_kind_of_request_that_was_supposed_to_be;
- (id)_exceptionNoStoreSaveFailureForError:(id)arg1 recommendedFrame:(int *)arg2;
- (void)_coordinator_you_never_successfully_opened_the_database_schema_mismatch:(id)arg1;
- (id)_processStoreResults:(id)arg1 forRequest:(id)arg2;
- (id)importStoreWithIdentifier:(id)arg1 fromExternalRecordsDirectory:(id)arg2 toURL:(id)arg3 options:(id)arg4 withType:(id)arg5 error:(id *)arg6;
- (id)managedObjectIDForURIRepresentation:(id)arg1;
- (id)currentPersistentHistoryTokenFromStores:(id)arg1;
- (BOOL)replacePersistentStoreAtURL:(id)arg1 destinationOptions:(id)arg2 withPersistentStoreFromURL:(id)arg3 sourceOptions:(id)arg4 storeType:(id)arg5 error:(id *)arg6;
- (BOOL)destroyPersistentStoreAtURL:(id)arg1 withType:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)migratePersistentStore:(id)arg1 toURL:(id)arg2 options:(id)arg3 withType:(id)arg4 error:(id *)arg5;
- (BOOL)setURL:(id)arg1 forPersistentStore:(id)arg2;
- (id)URLForPersistentStore:(id)arg1;
- (id)persistentStoreForURL:(id)arg1;
- (BOOL)_removePersistentStore:(id)arg1 error:(id *)arg2;
- (BOOL)_removeAllPersistentStores:(id *)arg1;
- (BOOL)removePersistentStore:(id)arg1 error:(id *)arg2;
- (id)addPersistentStoreWithType:(id)arg1 configuration:(id)arg2 URL:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (void)addPersistentStoreWithDescription:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_doAddPersistentStoreWithDescription:(id)arg1 privateCopy:(id)arg2 completeOnMainThread:(BOOL)arg3 withHandler:(CDUnknownBlockType)arg4;
- (BOOL)_attemptRecoveryFromAddPersistentStoreError:(id)arg1 withDescription:(id)arg2;
- (BOOL)_checkForTombstoneSkew:(id)arg1 metadata:(id)arg2 configuration:(id)arg3;
- (BOOL)_checkForSkewedEntityHashes:(id)arg1 metadata:(id)arg2;
- (id)_retainedPersistentStores;
@property(readonly) NSArray *persistentStores;
- (BOOL)tryLock;
- (void)unlock;
- (void)lock;
@property(readonly) NSManagedObjectModel *managedObjectModel;
- (id)initWithManagedObjectModel:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)metadataForPersistentStore:(id)arg1;
- (void)setMetadata:(id)arg1 forPersistentStore:(id)arg2;
@property(copy) NSString *name;
- (void)_routeHeavyweightBlock:(CDUnknownBlockType)arg1;
- (void)_routeLightweightBlock:(CDUnknownBlockType)arg1 toStore:(id)arg2;
- (void)performBlockAndWait:(CDUnknownBlockType)arg1;
- (void)performBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _PFModelMap *modelMap;
- (BOOL)_isRegisteredWithUbiquity;
- (void)_setIsRegisteredWithUbiquity:(BOOL)arg1;
- (BOOL)_isRegisteredWithCloudKit;
- (void)_setIsRegisteredWithCloudKit:(BOOL)arg1;
- (id)_importedObjectForOriginalEntityName:(id)arg1 originalPrimaryKey:(id)arg2 newStoreID:(id)arg3 usingLookup:(id)arg4 inContext:(id)arg5 useClonedObjectIDs:(BOOL)arg6;
- (id)_importedObjectIDForOriginalEntityName:(id)arg1 primaryKey:(id)arg2 usingLookup:(id)arg3 inContext:(id)arg4;
- (BOOL)_importAttributes:(id)arg1 relationships:(id)arg2 fromExternalRecordDictionary:(id)arg3 intoInstance:(id)arg4 oldStoreID:(id)arg5 newStoreID:(id)arg6 useClonedObjectIDs:(BOOL)arg7 usingLookup:(id)arg8;
- (BOOL)_importExternalRecordsAtStoreUUIDPath:(id)arg1 intoStore:(id)arg2 batchSize:(unsigned long long)arg3 error:(id *)arg4;
- (id)_externalRecordsHelper;
- (BOOL)_checkForPostLionWriter:(id)arg1;
- (void)_copyMetadataFromStore:(id)arg1 toStore:(id)arg2 migrationManager:(id)arg3;
- (id)_retainedAllMigratedObjectsInStore:(id)arg1 toStore:(id)arg2;
- (id)_realStoreTypeForStoreWithType:(id)arg1 URL:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (void)_assignObject:(id)arg1 toPersistentStore:(id)arg2 forConfiguration:(id)arg3;
- (void)_postStoresChangedNotificationsForStores:(id)arg1 changeKey:(id)arg2 options:(id)arg3;
- (void)_postStoreRemoteChangeNotificationsForStore:(id)arg1 andState:(unsigned long long)arg2;
- (id)_fetchAllInstancesFromStore:(id)arg1 intoContext:(id)arg2 underlyingException:(id *)arg3;
- (Class)_storeClassForStoreWithType:(id)arg1 URL:(id)arg2 options:(id)arg3;
- (id)_qosClassOptions;
- (void)_setQosClassOptions:(unsigned int)arg1;
- (id)_saveRequestForStore:(id)arg1 withContext:(id)arg2 originalRequest:(id)arg3 andOptimisticLocking:(id)arg4;
- (id)_checkRequestForStore:(id)arg1 withContext:(id)arg2 originalRequest:(id)arg3 andOptimisticLocking:(id)arg4;
- (id)_conflictsWithRowCacheForObject:(id)arg1 withContext:(id)arg2 andStore:(id)arg3;
- (id)_newConflictRecordForObject:(id)arg1 andOriginalRow:(id)arg2 withContext:(id)arg3;
- (id)_newObjectGraphStyleRecordForRow:(id)arg1 andObject:(id)arg2 withContext:(id)arg3;
- (void)_doPreSaveAssignmentsForObjects:(id)arg1 intoStores:(id)arg2;
- (BOOL)_canSaveGraphRootedAtObject:(id)arg1 intoStore:(id)arg2 withPreviouslyChecked:(struct __CFSet *)arg3 withAcceptableEntities:(struct __CFSet *)arg4;
- (BOOL)obtainPermanentIDsForObjects:(id)arg1 error:(id *)arg2;
- (void)_assignObjects:(id)arg1 toStore:(id)arg2;
- (void)managedObjectContextDidUnregisterObjectsWithIDs:(id)arg1 generation:(id)arg2;
- (void)managedObjectContextDidRegisterObjectsWithIDs:(id)arg1 generation:(id)arg2;
- (id)_allOrderKeysForDestination:(id)arg1 inRelationship:(id)arg2 error:(id *)arg3;
- (id)_newOrderedRelationshipInformationForRelationship:(id)arg1 forObjectWithID:(id)arg2 withContext:(id)arg3 error:(id *)arg4;
- (id)newValueForRelationship:(id)arg1 forObjectWithID:(id)arg2 withContext:(id)arg3 error:(id *)arg4;
- (id)newValuesForObjectWithID:(id)arg1 withContext:(id)arg2 error:(id *)arg3;
- (id)persistentStoreCoordinator;
- (void)_addPersistentStore:(id)arg1 identifier:(id)arg2;
- (id)_persistentStoreForIdentifier:(id)arg1;
- (id)managedObjectIDForURIRepresentation:(id)arg1 error:(id *)arg2;
- (id)managedObjectIDFromUTF8String:(const char *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;
- (BOOL)_removePersistentStore:(id)arg1;
- (id)_lastOpenError;
- (id)persistentStoreForIdentifier:(id)arg1;
- (BOOL)_rekeyPersistentStoreAtURL:(id)arg1 type:(id)arg2 options:(id)arg3 withKey:(id)arg4 error:(id *)arg5;
- (BOOL)_destroyPersistentStoreAtURL:(id)arg1 withType:(id)arg2 error:(id *)arg3;
- (BOOL)_destroyPersistentStoreAtURL:(id)arg1 withType:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (BOOL)_replacePersistentStoreAtURL:(id)arg1 destinationOptions:(id)arg2 withPersistentStoreFromURL:(id)arg3 sourceOptions:(id)arg4 storeType:(id)arg5 error:(id *)arg6;
- (id)managedObjectIDFromUTF8String:(const char *)arg1 length:(unsigned long long)arg2;
- (BOOL)_validateQueryGeneration:(id)arg1 error:(id *)arg2;
- (id)_reopenQueryGenerationWithIdentifier:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;
- (id)_retainedCurrentQueryGeneration:(id)arg1;
- (id)_retainedIdentifierFromStores:(id)arg1;
- (BOOL)_refreshTriggerValuesInStore:(id)arg1 error:(id *)arg2;
- (BOOL)validateManagedObjectModel:(id)arg1 forHistoryTrackingWithOptions:(id)arg2 error:(id *)arg3;
- (id)_retainedCurrentChangeTrackingToken;
- (id)_retainedChangeTokenFromStores:(id)arg1;
- (BOOL)_hasHistoryTracking:(id)arg1;
- (id)_xpcProcessName;
- (id)_xpcBundleIdentifier;
- (void)_setXPCProcessName:(id)arg1;
- (void)_setXPCBundleIdentifier:(id)arg1;

@end

