//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PassKitCore/PKMicaLayer.h>

@class CAGradientLayer, CAShapeLayer;
@protocol PKCheckGlyphLayerDelegate;

@interface PKCheckGlyphLayer : PKMicaLayer
{
    struct CGColor *_primaryColor;
    CAShapeLayer *_shapeLayer;
    CAGradientLayer *_maskLayer;
    BOOL _covered;
    struct CATransform3D _uncoveredTransform;
    struct CATransform3D _coveredTransform;
    BOOL _revealed;
    id <PKCheckGlyphLayerDelegate> _checkGlyphDelegate;
}

@property(nonatomic) BOOL revealed; // @synthesize revealed=_revealed;
@property(nonatomic) __weak id <PKCheckGlyphLayerDelegate> checkGlyphDelegate; // @synthesize checkGlyphDelegate=_checkGlyphDelegate;
- (void).cxx_destruct;
- (double)_updateCovered:(BOOL)arg1;
- (double)setCovered:(BOOL)arg1 animated:(BOOL)arg2;
- (double)setRevealed:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setPrimaryColor:(struct CGColor *)arg1 animated:(BOOL)arg2;
- (struct CGColor *)primaryColor;
- (void)_createMask;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 package:(id)arg2;
- (id)init;

@end

