//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TeaUI/NSToolbarDelegate-Protocol.h>

@interface _TtCC5TeaUI21WindowToolbar2ManagerP33_9D719DE3261ED0E657EC37A0A994568215ToolbarDelegate : NSObject <NSToolbarDelegate>
{
    // Error parsing type: , name: layouts
    // Error parsing type: , name: item
}

- (void).cxx_destruct;
- (id)init;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;

@end

