//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSScrubberSelectionView.h>

@class NSColor;

@interface NSScrubberRoundedSelectionBackgroundView : NSScrubberSelectionView
{
    NSColor *_tintColor;
}

+ (id)keyPathsForValuesInvalidatingDisplay;
@property(copy) NSColor *tintColor; // @synthesize tintColor=_tintColor;
- (void)updateLayer;
- (struct NSEdgeInsets)alignmentRectInsets;
- (BOOL)wantsUpdateLayer;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)_roundedBackgroundCommonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

