//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLModel, NSString, _MLTLogger;

@interface _MLTInferenceTesterConfiguration : NSObject
{
    BOOL _measurePredictionPerformance;
    BOOL _measurePredictionCPUCycles;
    BOOL _measurePredictionCPUMemory;
    BOOL _measurePredictionGPUMemory;
    BOOL _measurePredictionANEMemory;
    MLModel *_model;
    NSString *_modelPath;
    id <_MLTInputProvider> _testDataProvider;
    NSString *_testDataPath;
    long long _computeUnit;
    _MLTLogger *_logger;
}

@property BOOL measurePredictionANEMemory; // @synthesize measurePredictionANEMemory=_measurePredictionANEMemory;
@property BOOL measurePredictionGPUMemory; // @synthesize measurePredictionGPUMemory=_measurePredictionGPUMemory;
@property BOOL measurePredictionCPUMemory; // @synthesize measurePredictionCPUMemory=_measurePredictionCPUMemory;
@property BOOL measurePredictionCPUCycles; // @synthesize measurePredictionCPUCycles=_measurePredictionCPUCycles;
@property BOOL measurePredictionPerformance; // @synthesize measurePredictionPerformance=_measurePredictionPerformance;
@property(retain) _MLTLogger *logger; // @synthesize logger=_logger;
@property long long computeUnit; // @synthesize computeUnit=_computeUnit;
@property(retain) NSString *testDataPath; // @synthesize testDataPath=_testDataPath;
@property(retain) id <_MLTInputProvider> testDataProvider; // @synthesize testDataProvider=_testDataProvider;
@property(retain) NSString *modelPath; // @synthesize modelPath=_modelPath;
@property(retain) MLModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)init;

@end

