//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, _INPBContact;

@protocol _INPBShareETAIntentResponse <NSObject>
+ (Class)recipientType;
@property(readonly, nonatomic) unsigned long long recipientsCount;
@property(copy, nonatomic) NSArray *recipients;
@property(readonly, nonatomic) unsigned long long mediumsCount;
@property(readonly, nonatomic) int *mediums;
- (_INPBContact *)recipientAtIndex:(unsigned long long)arg1;
- (void)addRecipient:(_INPBContact *)arg1;
- (void)clearRecipients;
- (int)StringAsMediums:(NSString *)arg1;
- (NSString *)mediumsAsString:(int)arg1;
- (void)setMediums:(int *)arg1 count:(unsigned long long)arg2;
- (int)mediumAtIndex:(unsigned long long)arg1;
- (void)addMedium:(int)arg1;
- (void)clearMediums;
@end

