//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

#import "NSTextFieldDelegate.h"

@class NSStepper, NSString;

@interface KIntegerTextField : NSTextField <NSTextFieldDelegate>
{
    BOOL _configured;
    NSStepper *_stepper;
    id _formatter;
    long long _lastValidValue;
    SEL _action;
    id _target;
}

- (void)textDidEndEditing:(id)arg1;
- (void)textDidChange:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (BOOL)control:(id)arg1 didFailToFormatString:(id)arg2 errorDescription:(id)arg3;
- (void)setCustomValue:(long long)arg1;
- (BOOL)isFirstResponder;
- (void)setCurrentValue;
- (void)callAction;
- (void)stepperAction:(id)arg1;
- (void)setStepper:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)setAction:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (id)delegate;
- (void)initialConfiguration;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

