//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_xpc_object>;

@interface RemoteDeviceManager : NSObject
{
    NSObject<OS_xpc_object> *_connection;
}

- (void)sendMessage:(const char *)arg1 args:(id)arg2;
- (void)disconnectDevice:(id)arg1;
- (void)dealloc;
- (id)init;

@end

