//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <InternetAccounts/IAAccountSetupResult.h>

@class NSError;

@interface IAServerAccountSetupResult : IAAccountSetupResult
{
    BOOL _isExistingAccount;
    NSError *_setupError;
}

@property(retain) NSError *setupError; // @synthesize setupError=_setupError;
@property BOOL isExistingAccount; // @synthesize isExistingAccount=_isExistingAccount;
- (void).cxx_destruct;

@end

