//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <BrowserKit/BKPaneCapItem.h>

@class NSView;

@interface BKPaneCapItemView : BKPaneCapItem
{
    NSView *_view;
    void *_reservedPaneCapItemView1;
    void *_reservedPaneCapItemView2;
    void *_reservedPaneCapItemView3;
}

@property(retain) NSView *view; // @synthesize view=_view;
- (void)dealloc;
- (void)setEnabled:(BOOL)arg1;
- (void)setHidden:(BOOL)arg1;

@end

