//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface AMSBagURLParser : NSObject
{
}

+ (struct _NSRange)_rangeOfTemplateInURLString:(id)arg1;
+ (struct _NSRange)_rangeofSubstringWithOpeningTag:(id)arg1 closingTag:(id)arg2 inString:(id)arg3;
+ (id)_firstVariableInTemplate:(id)arg1 includeTags:(BOOL)arg2;
+ (id)URLBySubstitutingVariablesInURLString:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;

@end

