//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WorkflowKit/WFQuantityFieldParameter.h>

@interface WFDurationQuantityFieldParameter : WFQuantityFieldParameter
{
}

+ (unsigned long long)calendarUnitFromUnitString:(id)arg1;
+ (BOOL)unitStringIsDurationUnit:(id)arg1;
- (id)defaultSerializedRepresentation;
- (id)localizedLabelForPossibleUnit:(id)arg1 magnitude:(id)arg2 style:(unsigned long long)arg3;
- (BOOL)parameterStateIsValid:(id)arg1;
@property(nonatomic) unsigned long long possibleCalendarUnits;
- (id)initWithDefinition:(id)arg1;

@end

