//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RichMessageCellBase.h"

@class MessageStatusStackView, NSAttributedString, NSImageView, NSTextField;

@interface RichMessageChildCellView : RichMessageCellBase
{
    NSImageView *_unreadView;
    NSImageView *_vipView;
    NSImageView *_statusView;
    NSTextField *_senderView;
    NSTextField *_dateView;
    NSTextField *_snippetView;
    NSImageView *_mutedView;
    MessageStatusStackView *_statusStack;
}

+ (id)keyPathsForValuesAffectingSnippetString;
- (void).cxx_destruct;
@property(retain, nonatomic) MessageStatusStackView *statusStack; // @synthesize statusStack=_statusStack;
@property(retain, nonatomic) NSImageView *mutedView; // @synthesize mutedView=_mutedView;
@property(nonatomic) __weak NSTextField *snippetView; // @synthesize snippetView=_snippetView;
@property(nonatomic) __weak NSTextField *dateView; // @synthesize dateView=_dateView;
@property(nonatomic) __weak NSTextField *senderView; // @synthesize senderView=_senderView;
@property(retain, nonatomic) NSImageView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) NSImageView *vipView; // @synthesize vipView=_vipView;
@property(retain, nonatomic) NSImageView *unreadView; // @synthesize unreadView=_unreadView;
- (void)_updateVIPIndicatorWithImage:(id)arg1;
- (void)_updateUnreadIndicatorWithImage:(id)arg1;
@property(readonly, nonatomic) unsigned long long numberOfSnippetLines;
- (void)setObjectValue:(id)arg1;
@property(readonly, nonatomic) NSAttributedString *snippetString;
- (id)snippetStringAttributes;
- (double)defaultRowHeight;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)awakeFromNib;
- (void)updateFontsUsingBold:(BOOL)arg1;

@end

