//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSObject, NSString, PortMO;

__attribute__((visibility("hidden")))
@interface VolumePolicyMO : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) NSObject *curveData; // @dynamic curveData;
@property(copy, nonatomic) NSString *curveType; // @dynamic curveType;
@property(nonatomic) float initialDB; // @dynamic initialDB;
@property(nonatomic) float maxDB; // @dynamic maxDB;
@property(nonatomic) float maxHybridHwDB; // @dynamic maxHybridHwDB;
@property(nonatomic) float minDB; // @dynamic minDB;
@property(nonatomic) float minHybridHwDB; // @dynamic minHybridHwDB;
@property(copy, nonatomic) NSString *mode; // @dynamic mode;
@property(nonatomic) float nominalHwDB; // @dynamic nominalHwDB;
@property(retain, nonatomic) PortMO *port; // @dynamic port;
@property(copy, nonatomic) NSString *softwareVolumeCapabilities; // @dynamic softwareVolumeCapabilities;

@end

