//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CHHapticPlayable.h"

@class NSArray, NSString;

@interface CHHapticEvent : NSObject <CHHapticPlayable>
{
    NSString *_type;
    unsigned long long _audioResID;
    NSArray *_eventParams;
    double _time;
    double _duration;
    double _fullDuration;
}

- (void).cxx_destruct;
@property(readonly) double fullDuration; // @synthesize fullDuration=_fullDuration;
@property(readonly) NSString *type; // @synthesize type=_type;
@property double duration; // @synthesize duration=_duration;
@property double relativeTime; // @synthesize relativeTime=_time;
@property(readonly) NSArray *eventParameters; // @synthesize eventParameters=_eventParams;
- (BOOL)resolveExternalResources:(id)arg1 error:(id *)arg2;
@property(readonly) NSArray *parameterCurves;
@property(readonly) NSArray *parameters;
@property(readonly) NSArray *events;
- (id)getType;
- (id)initWithAudioResourceID:(unsigned long long)arg1 parameters:(id)arg2 relativeTime:(double)arg3 duration:(double)arg4;
- (id)initWithAudioResourceID:(unsigned long long)arg1 parameters:(id)arg2 relativeTime:(double)arg3;
- (id)initWithEventType:(id)arg1 parameters:(id)arg2 relativeTime:(double)arg3 duration:(double)arg4;
- (id)initWithEventType:(id)arg1 parameters:(id)arg2 relativeTime:(double)arg3;
- (id)init;
@property(readonly) unsigned long long audioResID;
- (id)initWithAudioResourceIndex:(unsigned long long)arg1 parameters:(id)arg2 time:(double)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

